### ISSUE TITLE
The docker image with version 1.8 is missing

### ISSUE THREAD

**Issue by tarampampam** [Orange-OpenSource/hurl#1003]
Is something wrong with the CI?

![image](https://user-images.githubusercontent.com/7326800/202508411-3858331e-cae4-40b8-8daf-d514145579ba.png)

**Comment by lepapareil** [comment]
Hi @tarampampam, nothing wrong with ci here 😉.

Just a small licensing issue between our organization and dockerhub that is being resolved. We will be pushing 1.8.0 to docker hub as soon as possible but please note that we plan to use the https://ghcr.io registry for our future releases.

**Comment by tarampampam** [comment]
ghcr would be awesome! Could you publush at least the latest version there now?

> And if possible, could you share a story about what happened with the licensing? I ask because I have a lot of images on the docker hub, and have never heard about problems with it.

**Comment by lepapareil** [comment]
Don't panic :wink:, you are not concerned by the new docker license model. It only concerns our internal organization processes.
As you expected, I just pushed 1.8.0 on dockerhub, sorry for the delay.
