### ISSUE TITLE
Snapshot Download Link does not work

### ISSUE THREAD

**Issue by zdavatz** [Orange-OpenSource/hurl#1024]
1. This link does not work for downloading:
2. https://github.com/Orange-OpenSource/hurl/releases/download/1.9.0-SNAPSHOT/hurl-1.9.0-SNAPSHOT-x86_64-linux.tar.gz
3. Results in `not found`.
4. ;(

**Comment by lepapareil** [comment]
Hi @zdavatz,

As we do not provide any `SNAPSHOT` packages, you can clone the master branch and build it following this [doc](https://github.com/Orange-OpenSource/hurl#build-on-linux).

**Comment by zdavatz** [comment]
Thank you, but the link that does not work is mentioned here: https://github.com/Orange-OpenSource/hurl#linux

**Comment by fabricereix** [comment]
Sorry for the confusion.
The official releases (currently 1.8.0) are given in https://hurl.dev/docs/installation.html#linux.
The current SNAPSHOT version can not be downloaded. If you need it, you have to clone the repo and run a `cargo build`.
We need to remove this broken link from the README.

**Comment by zdavatz** [comment]
Ok, great, yes, that is why I opened the issue. 🙏🏼🫶

**Comment by zdavatz** [comment]
Thank you!
