### ISSUE TITLE
Awesome project. Is there a GitHub Action?

### ISSUE THREAD

**Issue by skhaz** [Orange-OpenSource/hurl#1025]
I have just found the project, and it is awesome! I was wondering if it has a GitHub Action; if not, I can create one.

**Comment by lepapareil** [comment]
Hi @skhaz, glad you like this project.

[@tarampampam](https://github.com/tarampampam) has already created a [github action](https://github.com/marketplace/actions/install-hurl-cross-platform), feel free to contibute 😀.
