### ISSUE TITLE
Query parameter starting with $ not accepted

### ISSUE THREAD

**Issue by ako** [Orange-OpenSource/hurl#1027]
Trying to use Hurl to query an OData Rest API. OData uses query parameters that start with a dollar, e.g., $top, $skip, $filter, etc.
Using a dollar throws an error, escaping dollar as %24 is also not accepted.

Example:

```
GET http://student-admin-app:8085/odata/StudentRegistrationApi/v1/Students
[QueryStringParams]
$top: 5
```

Result:

```
error: Parsing method
  --> c:\projects\mendix\EduMgmtDemo\test.hurl:3:1
   |
 3 | $top: 5
   | ^ the HTTP method is not valid. Available HTTP Methods are GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE or PATCH
   |

```

**Comment by jcamiel** [comment]
Hi, 
Thanks for this feedback, this should definitively work and we'll fix it.

If you need it now, you can do :

- either use a [unicode literal](https://hurl.dev/docs/hurl-file.html#special-characters-in-strings) for `$`:

```hurl
GET http://student-admin-app:8085/odata/StudentRegistrationApi/v1/Students
[QueryStringParams]
\u{24}top: 5
```

Or use the full url 

```hurl
GET http://student-admin-app:8085/odata/StudentRegistrationApi/v1/Students?$top=5
```
