### ISSUE TITLE
Ideas for better header assertions

### ISSUE THREAD

**Issue by jlecour** [Orange-OpenSource/hurl#1028]
First, let me thank you for making this tool, which is already awesome and so useful.

I'm part of a team that maintains some sort of CDN composed of HAProxy and Varnish to help web-sites and web-apps being faster and more reliable. I've recently presented this at HAProxyConf 2022 (video soon to be available).
I'd trying to build a test-suite for the various sites and apps behind this proxy, to verify that the behavious is and stays what is intended. **Hurl seems to be the perfect solution to that**.
I've tried a few things and I've found some things that could be improved.
I've browsed the documentation and the issues list. Maybe this is already possible and I'm just a looser for not looking enough, maybe it's already possible but not well-documented enough, or maybe it's not possible yet.
Anyways, here I go.

Some headers contain information more complicated than a simple string. Examples :

1. A list values that are **type-consistent** and **ordered**. That is when the values are **comma-separated**, like `X-Forwarded-For: 192.168.2.1, 10.0.0.20, 10.0.0.10`.
2. Multiple values that are **not necessarily type-consistent** and **their order doesn't matter**. That is when the values are **semicolon-separated**, like `Strict-Transport-Security: max-age=<expire-time>; includeSubDomains; preload`.

NB: A combination is also possible : `Forwarded: for=192.0.2.60;proto=http;by=203.0.113.43, for=198.51.100.17`

Currently, I find it difficult to make precise assertions on this kind of values.

For the **1st example**, consider this assertion :  `header "X-Forwarded-For" contains "10.0.0.1"`.
It will match my previous example because the string `10.0.0.1` matches `10.0.0.10` in the header value, but the value is not correct.

Maybe, multiple values could be turned into an array of strings.
That way something like could work :
* `header "X-Forwarded-For" includes "10.0.0.1"`
* `header "X-Forwarded-For" count == 3`

For the **2nd example**, I can't find a way to correctly test the `max-age` value alone.
I could use the `contains` matcher, but it has the same limitation as my first example.

Maybe, using the same approach as what is done with cookies could work : 
* `header "Strict-Transport-Security[Max-Age]" > 3600`
* `header "Strict-Transport-Security[Preload]" not exists`

Thanks again for making and maintaining Hurl. It's great.

**Comment by jcamiel** [comment]
Hi, and thanks for this good feedback!

Your use case is good and indeed we could improve support for it. It's not quite clear in the docs (and we'll improve it) but the queries can be refined with [filters](https://hurl.dev/docs/asserting-response.html#filters). In your case the query is `header "X-Forwarded-For"`. Filters are applied on query, you can think of it as a pipe of transform function. Currently we only have two filters `count` and `regex`but we plan to add more. For your first example, we can imagine this syntax:

```
GET https://foo.com

HTTP/* 200
[Asserts]
header "X-Forwarded-For" split ", " count == 3                      # split is a filter that splits a string to a list with a separator
header "X-Forwarded-For" split ", " nth 0 == "192.168.2.1"   # nth is a filter that take the nth value of a list 
header "X-Forwarded-For" split ", " nth 1 == "10.0.0.10"
header "X-Forwarded-For" split ", " nth 2 == "10.0.0.20"
```

With with idea in mind, we can use it also for your second example with `includes` that test if an element is in a list:

```
GET https://foo.com

HTTP/* 200
[Asserts]
header "Strict-Transport-Security" split ", " includes "includeSubDomains"
header "Strict-Transport-Security" split ", " not includes "preload"
```

Currently `split` and `nth` filters doesn't exist but your example are great issues to be adressed, we'll look into it quickly.
With Hurl actual version, you can also test values with `matches` : 

```
GET https://foo.com

HTTP/* 200
[Asserts]
header "Strict-Transport-Security" matches /max-age=\d+/
```

**Comment by jlecour** [comment]
Hi @jcamiel, and thanks for the quick response. I'm glad to be able to add something, even as a newcomer.

Using low-level concepts like filters is a great way to progress step by step.
I don't mind having something a little more verbose but more generic.
And if things go well and solidify, it will still be possible to add a higher-level concept (like in cookies) later.
An abstraction should be added too early in the process.

The `split` filter is great. I guess it should support regexp to split, because implementation might keep a space after the separator, or not.

The `nth` filter is also great, even if the syntax is a bit weird for me.
But I'm used to the Ruby syntax, so I'm spoiled ;)

In the meantime (before your response), I've indeed used the `matches` predicate to better assert my header values. This is what I've done to check these header values : `Content-Security-Policy: default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self' 'nonce-foobar'

```
header "Content-Security-Policy" matches /(^|;)\s*default-src 'none'\s*(;|$)/
header "Content-Security-Policy" matches /(^|;)\s*img-src 'self'\s*(;|$)/
header "Content-Security-Policy" matches /(^|;)\s*script-src 'self'\s*(;|$)/
header "Content-Security-Policy" matches /(^|;)\s*style-src 'self' 'nonce-foobar'\s*(;|$)/
```

That could be easier to maintain, but it works.

**Comment by jcamiel** [comment]
It _surprisingly_ works 😂, we will do better with your inputs!

**Comment by jcamiel** [comment]
@jlecour We have merged on `master` filters that can refined a query (works on asserts and captures): `split`, `replace`, `toInt`. We'll add more depending on the needs. These filters will be available in Hurl next version (maybe end of the month), with the doc updated with samples. Don't hesitate to test it and give us your feedbacks!

**Comment by jlecour** [comment]
Hi. I've followed this issue and was wondering what the next step would be.
Is there a simple way to test before the release (I haven't looked at how to compile Hurl myself from a branch), or should wait for it?

**Comment by jcamiel** [comment]
You can build and test the version on `master` rather easily, without waiting an "official" release.
You can find build from sources instructions here:
https://hurl.dev/docs/installation.html#building-from-sources

For instance, on a Debian, you will need:

1. install Rust 
    ```shell
    $ curl https://sh.rustup.rs -sSf | sh -s -- -y
    $ source $HOME/.cargo/env
    ```
2. Install Rust dependencies libssl, libcurl and libxml2
    ```shell
    $ apt install -y build-essential pkg-config libssl-dev libcurl4-openssl-dev libxml2-dev
    ```
3. Build Hurl
    ```shell
    $ git clone https://github.com/Orange-OpenSource/hurl
    $ cd hurl
    $ cargo build --release
    $ ./target/release/hurl --version
    ```
4 - Enjoy 🎉

You can find samples for filters in https://github.com/Orange-OpenSource/hurl/blob/master/integration/tests_ok/filter.hurl

For instance:

```hurl
GET http://localhost:8000/filter

HTTP 200
[Asserts]
jsonpath "$.ips" split ", " count == 3
jsonpath "$.ips" replace ", " "|" == "192.168.2.1|10.0.0.20|10.0.0.10"
```

Don't hesitate to ping me if you struggle to build Hurl from source. And also don't hesitate to give some feebacks / improve the documentation for building Hurl,

**Comment by jlecour** [comment]
Thanks for the clear instructions. I've been able to compile it.

I'll give the new filters a try as soon as I can.
