### ISSUE TITLE
header type casting missed opportunity

### ISSUE THREAD

**Issue by jlecour** [Orange-OpenSource/hurl#1029]
Hi,

Let's say I have an HTTP response with a numeic header : `Age: 1337`.

I I try to assert a numeric value  I get a type error.

`header "age" >= 0` gives this error :

```
error: Assert failure
  --> tests/foo.hurl:30:0
   |
30 | header "age" >= 0
   |   actual:   string <592>
   |   expected: greater or equal than int <0>
   |   >>> types between actual and expected are not consistent
   |
```

`header "age" isInteger` gives this error :

```
error: Assert failure
  --> tests/foo.hurl:30:0
   |
30 | header "age" isInteger
   |   actual:   string <1966>
   |   expected: integer
   |
```

Is there a filter to force the type casting ?
I feel like I'm missing something here.

I know I cound do this, but it's not great :

```
header "age" exists
header "age" != "0"
```

Thanks

**Comment by fabricereix** [comment]
Hi @jlecour,
your understanding is right, the value returned by the `header` query is always a String.
And having a cast filter would indeed feel quite natural. Thanks for your suggestion.
We plan to add a few more filters for the next release, we could include yours.

Something like that
```
header "age" toInt >= 0
```
