### ISSUE TITLE
Typo in greater than and less than JSON export

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#103]
When exporting "greater than" and "less than" predicates, the value for `type` in the JSON export should reflect the grammar naming;

For example:
"less than" predicate is defined as [less-predicate](https://hurl.dev/docs/grammar.html#less-predicate) in Hurl grammar and should be export as `{"type":"less"...}`

**Comment by fabricereix** [comment]
fix in #105
