### ISSUE TITLE
Additional assert failure output options

### ISSUE THREAD

**Issue by ad8lmondy** [Orange-OpenSource/hurl#1044]
Hello again :)

When I run a hurl file, and an assert fails, I get this output:

```
hurl --location --fail-at-end permission_tests/test_10.hurl 
error: Assert status code
  --> permission_tests/test_10.hurl:6:8
   |
 6 | HTTP/* 200
   |        ^^^ actual value is <401>
   |
```
Which is nice - however, it while it does correctly identify the issue, some more info would be useful (to me :sweat_smile: ), particularly in the context of a CI/CD run.

For example, if the output was more like:
```
hurl --location --fail-at-end permission_tests/test_10.hurl 
error: Assert status code
  --> permission_tests/test_10.hurl:6:8
   | GET www.example.com
   |
 6 | HTTP/* 200
   |        ^^^ actual value is <401>
   |
```
To put into words: the request URL and method are shown in the error message.

Similarly, when I run a bunch of hurl files with `--test`:
```
hurl --location --fail-at-end permission_tests/*.hurl --test
permission_tests/test_10.hurl: Running [1/6]
error: Assert status code
  --> permission_tests/test_10.hurl:6:8
   |
 6 | HTTP/* 200
   |        ^^^ actual value is <401>
   |

permission_tests/test_10.hurl: Failure (1 request(s) in 931 ms)
permission_tests/test_5.hurl: Running [2/6]
permission_tests/test_5.hurl: Success (1 request(s) in 869 ms)
permission_tests/test_6.hurl: Running [3/6]
permission_tests/test_6.hurl: Success (1 request(s) in 968 ms)
permission_tests/test_7.hurl: Running [4/6]
permission_tests/test_7.hurl: Success (1 request(s) in 816 ms)
permission_tests/test_8.hurl: Running [5/6]
permission_tests/test_8.hurl: Success (1 request(s) in 1022 ms)
permission_tests/test_9.hurl: Running [6/6]
permission_tests/test_9.hurl: Success (1 request(s) in 1123 ms)
--------------------------------------------------------------------------------
Executed files:  6
Succeeded files: 5 (83.3%)
Failed files:    1 (16.7%)
Duration:        5747 ms
```
Having the failed request URL and method in the output would mean that it is quick and easy to diagnose which request had an issue. I did think about making the test file name more useful, but most of the URLs I'm testing are different paths of various depths on the same server - so they don't lend well to linux file names ;)

Would it be possible to control the output of errors in the way described above?

Thanks!

**Comment by jcamiel** [comment]
At least you seem to like Hurl!
My two cents, it will be very difficult to more precise: for instance, if we give more context (show more lines around the asserts), it will not address files like that:

```
GET https://foo.com
header-a: toto
header-b:toto

HTTP/* 200
```

The error will be:

```
error: Assert status code
  --> permission_tests/test_10.hurl:6:8
   |
 4 | header-b:toto
 5 | 
 6 | HTTP/* 200
   |        ^^^ actual value is <401>
   |
```
Which is still not giving enough context.

For your particular case:

- quick and dirty: use an inline comment on the status code `HTTP/* 200   # testing https://foo.com`
- use and display an HTML report for the test session [--report-html](https://hurl.dev/docs/manual.html#report-html): the HTML report embeds all the tests and link to Hurl files with errors that can gives you the error context

**Comment by ad8lmondy** [comment]
> At least you seem to like Hurl!

Yes, very much - exactly what we're after, thanks :)

> quick and dirty: use an inline comment on the status code HTTP/* 200 # testing https://foo.com

This completely solves my issue - works great!

Thanks!
