### ISSUE TITLE
hurlfmt displays extra new line

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#1055]
Given this Hurl file: 

```
GET http://localhost:8000/hello
HTTP 200
```

With no new line at the end of HTTP 200 (beware that vim adds a newline by default), `hurlfmt` displays an extra new line:

```shell
$ cat test.hurl
GET http://localhost:8000/hello
HTTP 200%
$ hurlfmt --no-color /tmp/test.hurl
GET http://localhost:8000/hello
HTTP 200
$
```

(% is displayed by zsh when the file doesn't end with a newline)

**Comment by fabricereix** [comment]
`hurlfmt` improves an existing Hurl file.
I think this is good to add a trailing newline.
