### ISSUE TITLE
does hurl support to print the [Capture] value to stdout?

### ISSUE THREAD

**Issue by thesues** [Orange-OpenSource/hurl#1076]

**Comment by jcamiel** [comment]
Hi, 
For debugging purpose, you can use [`--verbose` option](https://hurl.dev/docs/manual.html#verbose) that will display captures on stderr. You can also use [`--json` option](https://hurl.dev/docs/manual.html#json) that will output all the requests/responses in JSON with captures on stdout. Piping this with `jq` should gives you the captured data.

**Comment by jcamiel** [comment]
Hi @thesues I hope you’re happy with my answer. If it is not the case, don’t hesitate to reopen it,
