### ISSUE TITLE
Asserts in custom script

### ISSUE THREAD

**Issue by tpluscode** [Orange-OpenSource/hurl#1115]
### Discussed in https://github.com/Orange-OpenSource/hurl/discussions/1032

<div type='discussions-op-text'>

<sup>Originally posted by **tpluscode** November 28, 2022</sup>
Is it possible to create more asserts to handle different response bodies in specific ways?</div>

My example from that discussion:

```
GET https://example.com/resource

HTTP/* 200
[Captures]
format: header "content-type"

> node ./test-body.js --format {{format}}
```

**Comment by jcamiel** [comment]
See also [#1072](https://github.com/Orange-OpenSource/hurl/issues/1072#issuecomment-1346135666). For the moment, this is not prioritized.

**Comment by jcamiel** [comment]
Closed for the moment, we'll reopen it eventually if the feature is prioritised.
