### ISSUE TITLE
colorized output

### ISSUE THREAD

**Issue by realtica** [Orange-OpenSource/hurl#1126]
The --color option doesn't work, I need some extra dependency?
```
Debian GNU/Linux 11 (bullseye)
Tested on: kitty, lxterminal, gnome-terminal, etc 
```
![hurl-bug](https://user-images.githubusercontent.com/852446/209190478-450f675f-61ec-48d3-b2e7-c090a6678804.png)

**Comment by jcamiel** [comment]
Hi, 

It's no very clear in the docs but the `--color`will colorize what you'll typically have on stderr:

- `hurl --verbose api.hurl`
- `hurl --very-verbose api.hurl`
- `hurl --test api.hurl`
- `hurl --include api.hurl` (output headers)
- any errors and warnings

If you use `hurl api.hurl` you will have the last HTTP response on stdout. This will be outputed "as it", without any modification, independently of `--color` option. In your case, as your response is a JSON, you can pipe with [jq](https://stedolan.github.io/jq/) for a nice output: `hurl api.hurl | jq`
I will update the manual and the doc as it's is not very well explained.
