### ISSUE TITLE
how can send bulk request

### ISSUE THREAD

**Issue by hemedani** [Orange-OpenSource/hurl#1139]
### Problem to solve

I want to send a bulk HTTP request for example 1000 req and get a benchmark from it.
 
I want to get results like the average time for each request and hardware resource usage.

**Comment by fabricereix** [comment]
Hi @hemedani,
we don't have an option yet  to run the same request several times.
For the time-being, you could generate the Hurl file with the 1000 requests.
```
$ for i in $(seq 0 1000);do echo GET http://google.com >> test.hurl; done
```

And run the file with the JSON output which contains the duration for each request.
```
$ cat test.hurl | hurl --json >results.json
$ cat results.json  | jq '.entries|.[]|.time'
75
28
27
...
```

**Comment by fabricereix** [comment]
But that's something we'd like to add in the future, especially with the possibility to run the requests concurrently.
What kind of options would you like to see?

**Comment by hemedani** [comment]
tanks @fabricereix ,
one good example is [wrk](https://github.com/giltene/wrk2). 
some good options are time duration, active connection, and thread use.
and it's very nice if we have a hardware resource usage report also

**Comment by jcamiel** [comment]
Initialisation of an architecture document here => [/docs/spec/runner/parallel.md](https://github.com/Orange-OpenSource/hurl/blob/master/docs/spec/runner/parallel.md)

**Comment by jcamiel** [comment]
@hemedani with Hurl 5.0.0, we've added a [`--parallel`option](https://hurl.dev/docs/manual.html#parallel) and a `--repeat` option. Parallel run is activated by default with `--test` so if you have one file `foo.hurl`, you can run now:

```shell
$ hurl --test --repeat 1000 foo.hurl
```

That will runs 1000 foo.hurl in parallel (numbers of threads can be set with [`--jobs`option](https://hurl.dev/docs/manual.html#jobs))
