### ISSUE TITLE
Support key with '-' in jsonpath is raising an error

### ISSUE THREAD

**Issue by imsVLC** [Orange-OpenSource/hurl#1174]
Hi all,

I'm facing an error when my json support key has a '-' 

How to reproduce ?
With this assert block:

[Asserts]
jsonpath "$.data.invoiceaddress" exists
jsonpath "$.data.invoice-address"exists
The first assertion works but the second raises the error:.

jsonpath "$.data.relationships.invoice-address" exists
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the JSONPath expression '$.data.invoice-address" is not valid

Is that a bug or there is something I could do to avoid it? 

Thanks in advance!

Regards,

**Comment by fabricereix** [comment]
Hi @imsVLC ,
Thanks for reporting this bug. We should indeed support `-` in the dot notation like jsonpath.com.

For the time-being, you can use the bracket notation
`jsonpath "$.data.relationships['invoice-address']" exists`
