### ISSUE TITLE
libxml/xpath feature flag

### ISSUE THREAD

**Issue by gregwebs** [Orange-OpenSource/hurl#1191]
### Problem to solve

Fewer C dependencies helps build the project.
For my usage of hurl (JSON APIs), I don't need libxml.

### Proposal

If libxml usage was guarded by a feature flag, then I wouldn't have to install it.
It appears that libxml is used solely for the xpath feature, so an xpath feature flag would make sense.

### Tasks to complete

- [ ] create a feature flag for xpath usage
- [ ] ensure build does not use libxml when the xpath feature flag is disabled

**Comment by jcamiel** [comment]
Hi, 

I understand your issue but I think there is very few chance we'll do it. Today, Hurl is mainly a CLI tool, usage as a lib/crate is not our first goal. We actually promote that JSONPath and XPath are first class citizen. For instance, on https://hurl.dev this snippet is displayed on the home page:

```hurl
# Get home:
GET https://example.org

HTTP/1.1 200
[Captures]
csrf_token: xpath "string(//meta[@name='_csrf_token']/@content)"

# Do login!
POST https://example.org/login?user=toto&password=1234
X-CSRF-TOKEN: {{csrf_token}}

HTTP/1.1 302
```

I'm not confortable having to support Hurl that will not be able to run this snippet (plus the additional complexity to support this use case in code.)

That said (and I hope my response is not too harsh), we really want to avoid Hurl users to compile the tool and have proper packet management support. On Linux, that would imply to have a proper `apt-get install hurl` that will do the job of getting dependencies and build a proper binary.

Can I ask why do you need to compile Hurl from source (just to see if we can avoid it) ?
Thanks !

**Comment by gregwebs** [comment]
This issue wasn't targeting lib/crate usage but instead CLI usage. I though that at least this issue would be helpful as documentation for others- I was able to build it without too much hassle.

I was building with Apline Linux in a docker image.

```
RUN apk add --no-cache cargo libxml2-dev openssl-dev \
 && mkdir /download \
 && cd /download \
 && git clone https://github.com/Orange-OpenSource/hurl \
 && cd hurl \
 && cargo build --release \
 && cp ./target/release/hurl* /usr/local/bin/ \
 && cd / \
 && rm -rf /download \
 && apk del cargo libxml2-dev openssl-dev
```

**Comment by jcamiel** [comment]
Ok, I'm not really versed with Alpine; if we have provide an `apk` packet for hurl, would you have used it instead of recompiling Hurl?

Something like:

```
RUN apk add --no-cache hurl
```
?
In any case, I will update the installation docs https://hurl.dev/docs/installation.html#building-from-sources for Alpine with your instructions !

**Comment by gregwebs** [comment]
That would be great!

```
#5 15.94 ERROR: unable to select packages:
#5 15.98   hurl (no such package):
#5 15.98     required by: world[hurl]
```

**Comment by jcamiel** [comment]
I'm closing this one as not planned and opens #1213 for proper Alpine Hurl packet.
