### ISSUE TITLE
Adding datetime type

### ISSUE THREAD

**Issue by fabricereix** [Orange-OpenSource/hurl#1206]
Add a datetime type to the possible values (returned by a query or filter).
One of the motivations is using reusable filters such as `daysFromNow`, `year`, ...

`format/parse` filters will have to be used to convert Date to String/String to Date.

The datetime format can be specified explicitely (https://docs.rs/chrono/latest/chrono/format/strftime/)
`formatDate "%y/%m/%d"`  :: date -> str
`parseDate "%y/%m/%d" `  :: str -> date

Example
The query `cookie "SESSION_ID[Expires]"` could return a datetime value.
`cookie "SESSION_ID[Expires]" formatDate "%y/%m/%d %H:%M:%S" == "2021/01/13 22:23:01"`
`cookie "SESSION_ID[Expires]" formatDate  "%y" == "2021"`

The `header` query always returns a String, thus, its value could be converted explicitly.
`header "Expires" parseDate "%a, %d %b  %H/%M/%S" `

We could also add specific parse methods:
`header "Expires" parseDateRFC822 year == 2022 `

Similarly with formatting
`cookie "SESSION_ID[Expires]" formatDateRFC822 == "Tue, 1 Jul 2003 10:52:37 +0200"`

For the `==` predicate,
we could maybe accept `date_value == string_value`
where the string_value is parsed automatically/implicitly as a date (tries common date format)
That will enable to keep the existing assert
`cookie "SESSION_ID[Expires]" == "Wed, 13 Jan 2021 22:23:01 GMT"`

**Comment by fabricereix** [comment]
or the queries do not return dates (as now) and the values always needs to be converted explictly.
`cookie "SESSION_ID[Expires]" == "Wed, 13 Jan 2021 22:23:01 GMT"` is still an equality of strings.

Using date filter
`cookie "SESSION_ID[Expires]" parseDateRFC822 minutesFromNow < 15`

**Comment by jcamiel** [comment]
I prefer that `cookie "SESSION_ID[Expires]"` returns a Date type. The format is standard (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date) so there is no point to ask the user to provide the right format to parse this string.

**Comment by lepapareil** [comment]
What about :

>For the == predicate,
>we could maybe accept date_value == string_value
>where the string_value is parsed automatically/implicitly as a date (tries common date format)
>That will enable to keep the existing assert
>cookie "SESSION_ID[Expires]" == "Wed, 13 Jan 2021 22:23:01 GMT"

@jcamiel ?

**Comment by jcamiel** [comment]
I the cookie "Expires" query  returns only a Date, you can still have the string value:

Either use a header query:

```
header "Set-Cookie" regex /SESSION_ID=.*Expires=(.*?);/ == "Wed, 13 Jan 2021 22:23:01 GMT"
```

Or use a filter on cookie query:

```
cookie "SESSION_ID[Expires]" formatDate "%y/%m/%d %H:%M:%S" == "2021/01/13 22:23:01"
```
 I prefer the query to returns

**Comment by fabricereix** [comment]
relating to the naming of the datetime filters,
`parseDatetime`/`formatDatetime` versus `datetimeParse`/`datetimeFormat` ?

I would tend to prefer the second form to be consistent with `htmlEscape`/`htmlUnescape`
We should also probably use the fullname `datetime` everywhere rather `date`.
We will not have (at least for the time-being) a value that does not include the time.

we could also have a more generic filter `format FORMAT_STRING` that will depend on the value type.
`format "%06d"`   for an integer value
`format "%.2f"`   for a float input
`format "%y/%m/%d` for a datetime value

**Comment by fabricereix** [comment]
Example with format
```
cookie "SESSION_ID[Expires]" format "%y"== "2021"
cookie "SESSION_ID[Expires]" year == 2021
```

**Comment by fabricereix** [comment]
The `Date` type will also implicity encapsulates the time (like javascript Date (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)
