### ISSUE TITLE
Persistent variables from test file to next test file?

### ISSUE THREAD

**Issue by F1r3Hydr4nt** [Orange-OpenSource/hurl#1208]
### Problem to solve
I am trying to "capture" a variable in one test file and use it in the next sequential test file

### Question
How might variable persistency be achieved?
Can I capture into a $HURL_var or it even possible to set an env var in a .hurl file?

**Comment by F1r3Hydr4nt** [comment]
Or can we separate out multiple tests per file?

**Comment by F1r3Hydr4nt** [comment]
Thank you very much for the explanation, it is a good workaround.

I guess I will wrap the order of testing in a bash script unless there is a better solution?

Thanks, closing

**Comment by lepapareil** [comment]
> Thank you very much for the explanation, it is a good workaround.
> 
> I guess I will wrap the order of testing in a bash script unless there is a better solution?
> 
> Thanks, closing

If you have hurl files:

```
a.hurl
b.hurl
c.hurl
```

And you run hurl with

```
hurl --test *.hurl
```

Then if you want captures from `a.hurl` to be available to `b.hurl` or `c.hurl` you can

```
cat *.hurl | hurl --test
```

**Comment by jcamiel** [comment]
Smart!

**Comment by F1r3Hydr4nt** [comment]
There doesn't seem to be an example of how to access a HURL_ env var in a .hurl file, any ideas?
I have tried multiple arrangements of {{HURL_/$HURL_/HURL_ ... }} etc.

**Comment by F1r3Hydr4nt** [comment]
Nevermind I get it now, I drop the HURL_ prefix in the .hurl file, thanks!

**Comment by jcamiel** [comment]
Yes you can also check the documentation https://hurl.dev/docs/templates.html#injecting-variables
