### ISSUE TITLE
Add support for hooks (before, beforeEach, after, afterEach)

### ISSUE THREAD

**Issue by ad-si** [Orange-OpenSource/hurl#1226]
### Problem to solve

I need to create a resource before running my tests, and afterwards I want to delete it again (even if a test fails).

### Proposal

Add support for hooks like e.g. Cypress supports: https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Hooks.

Could maybe also be a `always` request, which will even be executed if a request before fails.

**Comment by fabricereix** [comment]
Hi @ad-si ,
For the moment, this is not prioritized.
The recommended way is to use additional simple shell scripts.

```
./create_resource.sh
hurl test.hurl.hurl || ./clean_resources.sh
```

**Comment by ad-si** [comment]
But if you need a variable (e.g. ID) from `test.hurl` in order to clean the resource with that ID, how would that work?

**Comment by fabricereix** [comment]
Currently, you can get a capture value after the test has finished from its JSON output (`--json`)
