### ISSUE TITLE
Add failure detail on html report

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#1286]
### Actual

![image](https://user-images.githubusercontent.com/15672496/219069684-221d6cb0-49c0-48a9-b75b-e03287e6589b.png)

### Proposal

![image](https://user-images.githubusercontent.com/15672496/219072158-eaa43fc3-9f9b-446d-9f7e-5e70c73aa93c.png)

**Comment by jcamiel** [comment]
I think we should revisit the way we construct our HTML report. Currently, if you run:

```shell
$ hurl --test --report-html /tmp a.hurl a.hurl a.hurl
```

We produce the following report:
<img width="395" alt="Screenshot 2023-02-15 at 21 30 18" src="https://user-images.githubusercontent.com/16323814/219147197-2b525d88-eac1-4b42-9df7-c365817c8677.png">

Each of the three links is pointing to the same file. If we want to display error in the Hurl files, or if we want to have statistics for each of the files, we need to __decorrelate__ the HTML filename with the Hurl filename (it's really the ghost of #521 which is coming back 😅).

A better way would be to use a kind of unique id (@jleverenz proposed a hash but I think a uuid would be better suited).

For instance, the following command:

```shell
$ hurl --test --report-html /tmp a.hurl a.hurl a.hurl
```
 Would produce this structure:

```
/tmp
├── index.html
└── store
    ├── c7fc2dc6-86f7-4009-abfb-21f2e54599a2.html
    ├── e32206a1-67b3-4d40-b325-aaa6cf3fda7a.html
    └── eebf6799-55b0-4793-97ab-38af3fdf3bc7.html
```

We would not need to normalize the filename anymore, and for instance, we could also add run with the standard input:

```
$ echo 'HEAD https://hurl.dev' | hurl --test --report-html /tmp
$ echo 'HEAD https://hurl.dev' | hurl --test --report-html /tmp
```

Will just add two more files to the store:

```
/tmp
├── index.html
└── store
    ├── 1d785bc8-a884-476f-a306-196beffe4d36.html
    ├── c7fc2dc6-86f7-4009-abfb-21f2e54599a2.html
    ├── dc515444-55aa-4e90-8df3-3685448353ed.html
    ├── e32206a1-67b3-4d40-b325-aaa6cf3fda7a.html
    └── eebf6799-55b0-4793-97ab-38af3fdf3bc7.html
```
