### ISSUE TITLE
Adding date-specific Filters

### ISSUE THREAD

**Issue by fabricereix** [Orange-OpenSource/hurl#1309]
We can add data-specific filters to make it easier to use our new date type in our asserts.

To test a date value than can change (such an SSL certification expiration date), we can use the interval between this date and the current execution time (`now`)

Starting with a duration in days: `daysFromNow and/or daysUntilNow`

Should we allow negative value?
`daysFromNow` would be positive if the date in the future while `daysUntilNow` would be positive if the date is in the past.

Or provide these 2 filters and only allow positive value?

**Comment by jcamiel** [comment]
`daysAfterNow` `dayBeforeNow`?

**Comment by fabricereix** [comment]
we will therefore implement the 2 flavors xxxAfterNow/xxxBeforeNow for each duration unit: days, hours, minutes, ....
They can both return negative value, but using the one returning the positive value will be recommended.

For example, assert that the certificate is still valid for the next 30 days.
```
[Asserts]
certificate "Expire-Date" daysAfterNow > 30
```
