### ISSUE TITLE
assert both response and header

### ISSUE THREAD

**Issue by chenrui333** [Orange-OpenSource/hurl#1342]
Looks like I cannot assert both response body and response header at the same time?

```
GET http://localhost:9000/hello

HTTP/1.1 200
`Hello world!`
[Asserts]
header "Content-Type" == "text/plain;charset=UTF-8"
```

Got something like this

```
error: Parsing method
  --> hurl/basic.hurl:5:1
   |
 5 | HTTP/1.1 200
   | ^ the HTTP method is not valid. Valid values are GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH, LINK, UNLINK, PURGE, LOCK, UNLOCK, PROPFIND or VIEW
```

**Comment by jcamiel** [comment]
You can, the `[Asserts]` section (we call it explicit asserts) should be first, then you can add an implicit response body to test against. You can see the expected structure here: https://hurl.dev/docs/response.html

**Comment by chenrui333** [comment]
I see, somehow missed the structure section. Thanks @jcamiel!!
