### ISSUE TITLE
WIldcard test triggering in a Windows DOS box does not work

### ISSUE THREAD

**Issue by linker3000** [Orange-OpenSource/hurl#1353]
### Summary
Following the instructions on how to trigger multiple tests results in an error in a Windows 10 DOS box and Powershell

The example below shows a network drive being used, but the same error occurs on a local C: drive.

EDIT: Tried on the (Debian) command line in WSL2 on the same PC and wildcards work fine, so this seems to be a 'DOS'-related issue.

### Steps to reproduce
Create some valid .hurl files in a subfolder
Try and bulk-execute the tests - for example: 

`hurl --variable toaddr=someadddress@test.com --test mytest\*.hurl  `

or from within the folder:

`hurl --variable toaddr=someadddress@test.com --test *.hurl  `

NB: The .hurl files include a substitution variable for {{toaddr}}. The tests were also run without defining the variable and the files were still 'not found'.

### Example Project
N/A

### What is the current *bug* behavior?
Error message - example:

`error: hurl: cannot access 'mytest\*.hurl': No such file or directory`

### What is the expected *correct* behavior?
All matching tests should be found and run

### Output of checks

- Version (`hurl --version`): 

```
hurl 2.0.1 libcurl/7.87.0-DEV Schannel zlib/1.2.13
Features (libcurl):  alt-svc AsynchDNS HSTS IPv6 Largefile libz NTLM SPNEGO SSL SSPI Unicode UnixSockets
Features (built-in): brotli
```

- Operating system and version:

`Windows 10 21H2 Build 19044.2604`

### Possible fixes

Not a fix, but a workaround is to use a command line or batch file:

for %%i in (*.hurl) do hurl --test "%%i" --variable toaddr=someadddress@test.com

**Error Example:**

![hurl-error](https://user-images.githubusercontent.com/19429471/224300716-8b1a6220-fe46-4742-b07e-9262610e4b4b.png)

**Comment by jcamiel** [comment]
Hi @linker3000 could you use the [`--glob`](https://hurl.dev/docs/manual.html#glob) option ?
For instance:
```
$ hurl --variable toaddr=someadddress@test.com --test --glob 'mytest\*.hurl'
```

**Comment by linker3000** [comment]
Works, but must use double quotes around the wildcard otherwise hurl throws an error:

`C:\Utils\sgrid-test>dir
 Volume in drive C is Acer
 Volume Serial Number is 4E9C-C3E2

 Directory of C:\Utils\sgrid-test

10/03/2023  13:02    <DIR>          .
10/03/2023  13:02    <DIR>          ..
10/03/2023  10:27                81 dotemplates.bat
10/03/2023  09:37             1,294 t1.hurl
10/03/2023  10:05             1,294 t2.hurl
10/03/2023  10:11             1,316 t3.hurl
               4 File(s)          3,985 bytes
               2 Dir(s)  278,234,771,456 bytes free

C:\Utils\sgrid-test>hurl --variable toaddr=[snip] --test --glob "*.hurl"
t1.hurl: Running [1/3]
t1.hurl: Success (1 request(s) in 296 ms)
t2.hurl: Running [2/3]
t2.hurl: Success (1 request(s) in 305 ms)
t3.hurl: Running [3/3]
t3.hurl: Success (1 request(s) in 300 ms)
--------------------------------------------------------------------------------
Executed files:  3
Succeeded files: 3 (100.0%)
Failed files:    0 (0.0%)
Duration:        913 ms`
