### ISSUE TITLE
When running the hurl command in a hurl file I get the message `hurl: no protocol specified`.

### ISSUE THREAD

**Issue by anderson-silva-concordia** [Orange-OpenSource/hurl#1354]
### Summary
When running the hurl command in a hurl file I get the message `hurl: no protocol specified`.

### Steps to reproduce
Just run the command in any .hurl file.

The file in question is this one.

```
GET http://httpbin.org/get

HTTP 200
```

**Comment by jcamiel** [comment]
Hi @anderson-silva-concordia can you run the following commands just to know what' your platform:

```
$ hurl --version
$ echo 'GET http://httpbin.org/get' | hurl
```

And if you have curl:

```
$ curl 'http://httpbin.org/get'
```

**Comment by anderson-silva-concordia** [comment]
I was using the wrong hurl package from archlinux. That was the issue.

Thank you @jcamiel
