### ISSUE TITLE
Using the --glob command for parsing Windows filenames seems to break depending on the glob pattern

### ISSUE THREAD

**Issue by linker3000** [Orange-OpenSource/hurl#1365]
### Summary
A simple -- glob of '\*.hurl' works fine, but using the wildcard '*' with text either side is not parsed and hurl displays its help menu.

### Steps to reproduce
Create some valid .hurl files in a subfolder
Try and bulk-execute the tests - for example: 

`hurl --variable toaddr=[snip] --test --glob "*.hurl"`

The above will work, but the variations below won't:

`hurl --variable toaddr=[snip] --test --glob "w*.hurl"  `

`hurl --variable toaddr=[snip] --test --glob "*-remind.hurl"`

### Example Project
N/A

### What is the current *bug* behavior?
hurl does not parse the glob pattern and displays its help text

### What is the expected *correct* behavior?
All matching tests should be found and run

### Relevant logs and/or screenshots
N/A

### Output of checks

- Version (`hurl --version`): 

```
hurl 2.0.1 libcurl/7.87.0-DEV Schannel zlib/1.2.13
Features (libcurl):  alt-svc AsynchDNS HSTS IPv6 Largefile libz NTLM SPNEGO SSL SSPI Unicode UnixSockets
Features (built-in): brotli
```

- Operating system and version:

`Windows 10 21H2 Build 19044.2604`

### Possible fixes

Not a fix, but a workaround is to use a batch file:

```
setlocal EnableExtensions EnableDelayedExpansion
for %%i in (pattern-to-match) do hurl --test "%%i" --variable toaddr=%EMAIL%

```
**Error Example:**

[hurl help text]

**Comment by fabricereix** [comment]
Hi @linker3000,
in order to reproduce, could you give the output of `find`?
Thanks

**Comment by jcamiel** [comment]
`--glob` option should work like classic [glob pattern](https://en.wikipedia.org/wiki/Glob_(programming)). For instance, if you want to target all Hurl file in any subfolder, you should do something like this:

```
$ hurl --glob "**/*.hurl"
```

**Comment by linker3000** [comment]
> in order to reproduce, could you give the output of `find`?
> Thanks

Not sure what you want here!?

**Comment by linker3000** [comment]
Just for clarification, using traditional DOS-style pattern matching gives - for example:

![image](https://user-images.githubusercontent.com/19429471/224712014-944a4757-ee5b-4f48-9092-654f8cadaf05.png)

**Comment by linker3000** [comment]
Just for clarity, using traditional DOS-type pattern matching gives:

![image](https://user-images.githubusercontent.com/19429471/224712355-f2e8ce84-7fdc-4b5c-b186-03684b5273b3.png)

**Comment by linker3000** [comment]
> Can you test if this is a problem of case sensitivity? What's the result if your run `hurl --test --glob TPL-MOU*.hurl`?
> Ripgrep has a `--glob-case-insensitive` along with `--glob` option that we could implement.

Yes, this appears to be a case-sensitive issue,: **using TPL-MOU* works**.

Implementing the 'insensitive' option would be helpful. For now I am converting the input to all upper case with extra code in the batch file.

**Comment by jcamiel** [comment]
Hi @linker3000 with #1446 we'll implement taking directory as input: for instance, 

```
$ hurl --test .
```

Will search recursively in the current folder and all subfolder for '*.hurl' file. While it's not a proper replacement for `--glob`, it can replace certainly most usages of `--glob`(case insensitive or not) so we're not going to implement `--glob-case-insensitive`. Fell free to comment if you don't agree :) !
