### ISSUE TITLE
Read missing variables from prompt in interactive mode

### ISSUE THREAD

**Issue by tnicolaisen-snabble** [Orange-OpenSource/hurl#1370]
### Problem to solve

I found myself writing a hurl script to ease some admin task, like creating an account for a user:

```
hurl create-account.hurl --variable email='firstname.lastname@mycompany.com'
```

However, as the amount of required variables increases, it becomes a bit of a trial to execute the script.

```
hurl create-account.hurl \
    --variable email='firstname.lastname@snabble.io' \
    --variable role='manager' \
    --variable project="/this-project"
```
Each time I run it hurl will only complain about one missing variable, even if there are more.

### Proposal

Offer to read variable values from the prompt when running in `--prompt` mode:

```
hurl create-account.hurl --prompt
? Please provide a value for the variable email:
> [here I can enter 'firstname.lastname@mycompany.com' and press enter.]
? Please provide a value for the variable type:
> [and so on]
```

Alternatively, I could wrap the hurl call with shellscripts that provide the variables, but this seemed like it might be a good feature.

I'm not sure if this falls within the desired simplicity of hurl (which I love, btw), so please close this if it feels too complicated.

**Comment by jcamiel** [comment]
Hi, 
Thanks for the feedback. It's true that we have a tension between adding new features and keeping the core of Hurl simple. Given that we have already [multiple way to initialize variables](https://hurl.dev/docs/templates.html#injecting-variables) (using [`--variable` option](https://hurl.dev/docs/manual.html#variable),  using [`--variables-file`](https://hurl.dev/docs/manual.html#variables-file), or even defining environment variables, for instance HURL_foo=bar), and that, as you said, you can write a simple script to address your use case, I would prefer not to add another way.

You can also define variables inside a Hurl file with using [`[Options]`](https://hurl.dev/docs/request.html#options) section. For instance:

```hurl
GET https://foo.com
[Options]
variable: login=alice
variable: password=1234
HTTP 200
```

You could use it to perform an "early" check and test from the first request that all your variables are defined, even if you need those variables later.

Given this file:

```hurl
GET https://foo.com
[Options]
variable: login={{login}}
variable: password={{password}}
HTTP 200
```

```shell
$ hurl file.hurl
error: Undefined variable
  --> file.hurl:3:19
   |
 3 | variable: login={{login}}
   |                   ^^^^^ you must set the variable login
   |

$ hurl --variable login=alice file.hurl
error: Undefined variable
  --> file.hurl:4:22
   |
 4 | variable: password={{password}}
   |                      ^^^^^^^^ you must set the variable password
   |
$ hurl --variable login=alice --variable password=1234 file.hurl
<!DOCTYPE html>
<html>
...
```

It's kind of a trick and maybe not ideal for your use case but that's another option.

**Comment by Zegnat** [comment]
I ran into this as well, but with a slightly different use-case. I understand that it is out of scope for Hurl, but would like to mention it  just so it is written down somewhere.

I would like to prompt the user for a variable value during a request chain. I need to prompt for this as the value of the variable is unknowable at the start of the chain. This happens to me when a chain requests an API that triggers a 2FA SMS to be sent. The next request in the chain requires the digit that has not been provided out of band.
