### ISSUE TITLE
Capture specific value from request response collection

### ISSUE THREAD

**Issue by janstrohschein** [Orange-OpenSource/hurl#1408]
### Problem to solve
I interact with an API that returns an array of objects. I need to retrieve a value from a specific item of this collection for subsequent requests. Which item is based on another value in this object. For example I would like to capture the id of the item where the clientId == "account" as seen in the following json object:

```
[
  {
    "id": "c665feac-a6c4-46e6-a914-f669a3a7d79b",
    "clientId": "account"
  },
  {
    "id": "2eb6dc0e-55aa-446f-9c14-137130d5d49b",
    "clientId": "account-console"
  }
]
```

### Proposal
It is possible to access the jsonpath contents for assertions like this:
`jsonpath "$.books[0].name" == "Dune"
`
It would be nice if I could do something like this to capture another value of that object:
```
[Captures]
id: jsonpath find("$.[].clientId" == "account").id

```

### Additional context and resources
The functionality is available in Postman and jq. I would like to switch for our use cases from Postman to hurl but right now I cant chain the requests.

In a Postman Test I can save the id as follows:
```
var client_item = jsonData.find(cr => cr.clientId === "account")
pm.collectionVariables.set("client_id", client_item.id);
```

In jq I can do the following:
`jq '.[] | select(.clientId == "account").id'`

I searched the documentation to solve this use case but please let me know if I can achieve this with the current functions.
Best regards,
Jan

**Comment by jcamiel** [comment]
Hi,
You can use [JSONPath expression](https://goessner.net/articles/JsonPath/) that act like filter to target specific JSON nodes. In your example, the query can be `$[?(@.clientId == 'account')]`:

```hurl
GET https://api.pet.com

HTTP 200
[Captures]
id: jsonpath "$[?(@.clientId == 'account')]"
```

I will update the docs at <https://hurl.dev> to emphasize that JSONPath expression are supported and can be used to refine queries.

**Comment by janstrohschein** [comment]
Thank you very much for your help and the detailled explanation! I was not aware that it works like this but it solves my use case perfectly.

Have a nice afternoon!
Jan
