### ISSUE TITLE
Add rss/atom feed to the blog

### ISSUE THREAD

**Issue by Kaligule** [Orange-OpenSource/hurl#1489]
### Problem to solve

following the blog automatically is not possible at the moment

### Proposal

Add an atom/rss feed to the blog

### Additional context and resources
https://en.wikipedia.org/wiki/Web_feed
### Tasks to complete

- Add feed to block
- link it on the blog

**Comment by jcamiel** [comment]
@Kaligule I've published the blog feed at <https://hurl.dev/blog/feed.xml>, can you check that it is ok with your usual reader? I'm doing some checks before making it visible on <https://hurl.dev>

**Comment by Kaligule** [comment]
Looks awesome. I love full text feeds :) Didn't find any problems (using newsblur as a reader).

The w3c feed validator finds some very minor issues, but this is nothing to worry about: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhurl.dev%2Fblog%2Ffeed.xml

**Comment by Kaligule** [comment]
RSS Feed is found on the website now, can be found automatically or with the link that is on the blog. Thanks (and props for being really fast about this).
