### ISSUE TITLE
Publish new container image version

### ISSUE THREAD

**Issue by hinricht** [Orange-OpenSource/hurl#1490]
### Problem to solve

The [current official container image](https://hub.docker.com/r/orangeopensource/hurl/tags) is outdated: 

    1.8.0  Last pushed 5 months ago by nicott

### Proposal

Please push a new version, either manually or integrated in CI (for future versions as well).

### Additional context and resources

Thanks !

**Comment by muffl0n** [comment]
https://github.com/Orange-OpenSource/hurl/pkgs/container/hurl
