### ISSUE TITLE
Implement isDate predicate

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#1520]
Since 3.0.0, dates are first type citizen in Hurl format. As there are `isFloat`, `isInteger`, `isString`, `isCollection` predicates, we could add `isDate`:

```
GET https://example.org
HTTP 200
[Asserts]
certificate "Expire-Date" isDate == true
```

**Comment by guilherme-puida** [comment]
I'd like to work on this if there isn't anyone else currently implementing this :^)

**Comment by jcamiel** [comment]
Hi @guilherme-puida you can work on it if you want, there is nobody for the moment! We've a [contributing guide](https://github.com/Orange-OpenSource/hurl/blob/master/CONTRIBUTING.md) to help you start if you want, and also [some documentation on how we test Hurl](https://github.com/Orange-OpenSource/hurl/blob/master/integration/README.md). Don't hesitate to give us feebacks on the source code, onboarding on the project etc... Thanks for your help!

**Comment by guilherme-puida** [comment]
> ```
> GET https://example.org
> HTTP 200
> [Asserts]
> certificate "Expire-Date" isDate == true
> ```

Is this correct? Looking at the `isInteger/...` docs I assumed it would be just `certificate "Expire-Date" isDate` (without the `== true`).

**Comment by jcamiel** [comment]
No you're right, it's just `isDate`!

```hurl
GET https://example.org
HTTP 200
[Asserts]
certificate "Expire-Date" isDate
```
