### ISSUE TITLE
Identical textual body for different line terminators    

### ISSUE THREAD

**Issue by fabricereix** [Orange-OpenSource/hurl#153]
Hurl supports both line terminators '\n' and '\r\n'. 
Currently, the textual body (json, xml, raw-string) depends on the line terminator used.

It can be confusing that the same hurl file encoded with 2 different line-terminators have different textual body.
For that reason, the textual body should only contain the '\n' line terminator which should be the most common one.

If one wish to send a textual body with '\r\n', it will have to be done through a binary body (base64, file) .

**Comment by jcamiel** [comment]
On windows, \r\n is the separator commonly used,  I find it very confusing to explain that some part of the Hurl file could used \r\n while other part must use \n. 
- could we trigger an error at the first difference in line terminator, and have a message when detecting line terminator error ?
- with hurlfmt can we force the LF terminator ?

**Comment by fabricereix** [comment]
That's not what I meant.
on the opposite, Hurl files encoded with either '\n' or '\r\n' should have exactly the same meaning.
It is similar for a file encoded with a BOM or without a BOM, Hurl should see the same input.

**Comment by fabricereix** [comment]
after discussing with @lepapareil, it probably makes more sense to leave it as it is.
In terms of body, Hurl send exactly the line terminators it had parsed in the file.
