### ISSUE TITLE
Make Http module public

### ISSUE THREAD

**Issue by Laeri** [Orange-OpenSource/hurl#1546]
### Problem to solve
I would like to use hurl as a library (the client and curl generation part).
However, the http module is private which contains `RequestSpec` and `Client` for example.

### Proposal
Making the `http` module public would allow to use the `RequestSpec`, `Client` and other classes for directly running a request or converting a `RequestSpec` to a curl.

### Tasks to Complete
- [ ] Marking the http module as public in the hurl package

**Comment by jcamiel** [comment]
Hi @Laeri we have specifically clean the public apis of the `hurl` crates in the last version, in order not to expose implementation details (see https://github.com/Orange-OpenSource/hurl/issues/1259).
If you want to use, you should use the `run` method:

```rust
// A simple Hurl sample
let content = r#" 
GET http://localhost:8000/hello 
HTTP 200 
"#;

// Define runner options and logger
let options = RunnerOptionsBuilder::new()
    .follow_location(true)
    .verbosity(Some(Verbosity::Verbose))
    .build();
let logger = LoggerBuilder::new().build();

// Set variables
let mut variables = HashMap::default();
variables.insert("name".to_string(), Value::String("toto".to_string()));

// Run the Hurl sample
let result = runner::run(
    content,
    &options,
    &variables,
    &logger
);
assert!(result.unwrap().success);
```

`RequestSpec` is not exposed any more, you have to construct a Hurl content to specify your request.
Is there anything you can't currently do with this api ?

**Comment by Laeri** [comment]
Thanks for the quick reply.
Sorry I should have explained my use case better:

I am parsing a different file format than hurl uses (the intellij .http/.rest file spec) into my own request model. I would like to run a request from this model and I saw that hurl exists and I thought using hurl as a library would be nice as it already does provide the same functionality for a similar format.

However, `runner::run` function requires content to be of a string but I would like to use the existing hurl `RequestSpec` together with the `Client`. 
As I have already a model built from my own parser I would like to convert it into the `RequestSpec` model so I can use the client as well as any utilities centered around `RequestSpec`.
Also the `client::curl_command_line` function that transforms a `RequestSpec` into a curl string would be nice to use.

In the issue mentioned I saw that the focus is on hurl's usage as a cli program which makes sense.
However, at least for my use case and I think also for general library usage it would help to have access to client methods as well as the models used for running requests.

**Comment by jcamiel** [comment]
Thanks for your explanation, it's very clear!

My two cents:
- we have a "companion" tool, `hurlfmt`, which can export Hurl files to JSON, `curl` etc... We have done this to facilitate migrating your tests from Hurl file to something else. You want the other way, but I mention it anyway as we haven't make a lot publicity about it! `hurlfmt` is also available as a crate, so you can use it in your Rust program or as a cli tool
- now that you've parsed the IntelliJ file, you could export your intermediate format to the Hurl file format. It's doable (maybe not easy), this way you could use our `run` public APIs.
- last but not least, you can by-pass the Hurl format and directly use the `curl` HTTP engine through [`curl-rust`](https://github.com/alexcrichton/curl-rust) crate. Our own internal engine (that is not public) is just a very thin wrapper over it, so maybe you'd benefit for using `libcurl` directly (through the Rust binding)

**Comment by Laeri** [comment]
I saw that curl is used behind the hood. I have already written a mockup of the same tool in go also using libcurl so I will port it probably that way.

Not making the http module public makes sense for a cli tool, therefore I will close this issue.
Thanks for your help
