### ISSUE TITLE
Valid jsonpath not accepted as valid

### ISSUE THREAD

**Issue by phaza** [Orange-OpenSource/hurl#1555]
### What is the current *bug* behavior?
Getting error:
```
error: Invalid JSONPath
translation: jsonpath "$.[?(@.id == 23628)].content"
…
the JSONPath expression '$.[?(@.id == 23628)].content' is not valid
```

### Steps to reproduce
Given a json like this:
```json
[
  {
    "id": 23628,
    "language": "Some",
    "sectionId": 292,
    "key": "Key",
    "content": "Some content"
  },
 {
    "id": 23627,
    "language": "Some",
    "sectionId": 291,
    "key": "Key2",
    "content": "Some other content"
  }
]
```

### What is the expected *correct* behavior?
I expect the json path to return "Some content".
Testet via [jp](https://github.com/jmespath/jp) and [jsonpath.com](https://jsonpath.com/)

### Execution context
linux container running on a windows host.
Passing environment variables via .env file.

- Hurl Version (`hurl --version`):
hurl 3.0.0 libcurl/8.0.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.3840 nghttp2/1.51.0
Features (libcurl):  alt-svc AsynchDNS brotli HSTS HTTP2 IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
Features (built-in): brotli
- Operating system and version:
docker: ghcr.io/orange-opensource/hurl:latest

**Comment by fabricereix** [comment]
Thanks @phaza for reporting the bug.
The parsing fails because of the dot after the `$`.
The jsonpath expression without it should work
`jsonpath "$[?(@.id == 23628)].content"`.

We will fix it in the next release.
