### ISSUE TITLE
hurl-3.0.1-arm64-macos.tar.gz is not found

### ISSUE THREAD

**Issue by suzuki-shunsuke** [Orange-OpenSource/hurl#1590]
The asset for darwin/arm64 wasn't released at 3.0.1.

https://github.com/Orange-OpenSource/hurl/releases/tag/3.0.1

<img width="402" alt="image" src="https://github.com/Orange-OpenSource/hurl/assets/13323303/8303ee44-1343-464b-9a3e-b4096c2a91ae">

https://github.com/Orange-OpenSource/hurl/blob/0ec43dd8774d8b748f484f889e78f334340d58e4/README.md?plain=1#L1012

> Precompiled binary is available at [hurl-3.0.1-x86_64-macos.tar.gz](https://github.com/Orange-OpenSource/hurl/releases/download/3.0.1/hurl-3.0.1-x86_64-macos.tar.gz) for x86 CPUs and [hurl-3.0.1-arm64-macos.tar.gz](https://github.com/Orange-OpenSource/hurl/releases/download/3.0.1/hurl-3.0.1-arm64-macos.tar.gz) for ARM CPUS.

The link [hurl-3.0.1-arm64-macos.tar.gz](https://github.com/Orange-OpenSource/hurl/releases/download/3.0.1/hurl-3.0.1-arm64-macos.tar.gz) is broken.

The release job for darwin/arm64 seems not to be run.

https://github.com/Orange-OpenSource/hurl/actions/runs/5145645993

<img width="331" alt="image" src="https://github.com/Orange-OpenSource/hurl/assets/13323303/b2d3359f-be5b-4a25-b2f5-359910a5a51b">

**Comment by suzuki-shunsuke** [comment]
GitHub Actions and CircleCI weren't changed between 3.0.0 and 3.0.1. 🤔

https://github.com/Orange-OpenSource/hurl/compare/3.0.0...3.0.1

**Comment by jcamiel** [comment]
Hi @suzuki-shunsuke you can install Hurl 3.0.1 on macOS with brew for all version (x86 and arm) `brew install hurl`. The binary will be available in a few hours on GitHub. The release cycle is not the same with other variants, so you can have a slight delay before the arm binary is available for download on our GitHub release page.

**Comment by suzuki-shunsuke** [comment]
>  The binary will be available in a few hours on GitHub. The release cycle is not the same with other variants, so you can have a slight delay before the arm binary is available for download on our GitHub release page.

Oh, I see. Thank you for your explanation. It's interesting.

This is just curious. Why is the release cycle different?
Isn't the release automated by CI? I thought the release workflow is triggered by Git tag or something.

**Comment by jcamiel** [comment]
Sure! We use GitHub actions and runners for the construction of the binaries. For the moment, GitHub doesn't provide arm64 macOS runner so we can't release the arm64 binary at the same time. We doesn't use CircleCI in hope for GitHub to enable arm64 runner but it seems really uncertain now (see https://github.com/actions/runner-images/issues/2187).

For the packet manager (choco, brew, npm, apk etc...), the process is still different. Sometimes the creation of the GitHub release triggers the update of the packet. Usually, maintainers of those packets update manually their packet, so you can have a slight delay between the GitHub release and the availability on a given packet manager.

**Comment by suzuki-shunsuke** [comment]
Oh, I understood. Thank you for your explanation!

**Comment by jcamiel** [comment]
@suzuki-shunsuke the arm64 binary has been uploaded to the 3.0.1 GitHub release.

**Comment by suzuki-shunsuke** [comment]
Thanks!
