### ISSUE TITLE
add length predicate

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#161]
An api returns a dynamic generated `fixed_id` that must contain `8 chars`, it would be helpful if i could test it with a simple `length` predicate:

```
GET https://my_api.com

[Asserts]
jsonpath "$.fixed_id" length 8
```

what do you think about it ?

**Comment by jcamiel** [comment]
Could you use a `matches` predicate in this case ?

```
GET https://my_api.com
HTTP/1.1 200
[Asserts]
jsonpath "$.fixed_id" matches ".{8}"
```
 
A `length` predicate could also be confusing with a `countEquals` predicate when the query returns a collection...

**Comment by lepapareil** [comment]
I agree, `matches` makes it possible to achieve this result.
The idea is to add a predicate to simplify the human reading of the hurl file, indeed matches can also replace existing predicates such as `contains`, `exists` or `startsWith`, but in terms of ease of reading, I'm quite happy that these predicates exist :).

**Comment by fabricereix** [comment]
length is often used for string, which is good.
but also for collection.

It conflicts with our existing count. Note that Rust have both a count and a length method on the iterator, and this is not that easy to understand the difference.
Therefore, if we add a length predicate, it would probably makes sense to use it for both collection and string and remove the count predicate.

**Comment by lepapareil** [comment]
I agree

**Comment by lepapareil** [comment]
So we have 3 possibilities:

- using `countEquals` for collection and `matches expression` for string
- using `countEquals` for collection and `length` for string
- using `length` for string and collection

It can be interesting to look at what is being done in the different most used languages on this topic ([ref1](https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(string_functions)#length), [ref2](http://rigaux.org/language-study/syntax-across-languages.html#BagAndLstListSize)):

| usage                        | languages |
|-|-|
| string length/len | perl, python, go, c, #, c++, php, javascript, java, haskell, objective-c, rust |
| string size | c++, ruby |
| string count | clojure, swift |
| collection/list length/len | python, c#, common lisp, haskell, Java, JavaScript, ruby, rust |
| collection/list size | c++, Fortran |
| collection/list count  | clojure, swift, Objective-C, PHP |

**Comment by fabricereix** [comment]
we are going to make the `countXXX` predicates deprecated in favor of the subquery count (#127)
