### ISSUE TITLE
 Support for Default Values in Hurl Variable Injection

### ISSUE THREAD

**Issue by MdTeach** [Orange-OpenSource/hurl#1621]
Currently, Hurl supports variable injection using the `--variable` flag, but it lacks a built-in mechanism for providing default values when variables are not explicitly provided. 

It streamlines variable handling for users opting for the default configuration.

For local env:
```curl
hurl test.hurl
```

Prod env:
```curl
hurl --variable host=prodserver.url test.hurl
```

**Comment by fabricereix** [comment]
Hi @MdTeach ,
I'm not sure I understand your requirement. You may have a look at the `--variable-file` option.
https://hurl.dev/docs/manual.html#variables-file

**Comment by Kinrany** [comment]
Is there a way to store default values implicitly, without pointing hurl at the file with default values with every invocation?

**Comment by jcamiel** [comment]
Hi @Kinrany maybe you can use environment variables? You can look at the doc for [injecting variables](https://hurl.dev/docs/templates.html#injecting-variables) to see how to use env vars.

**Comment by ShaddyDC** [comment]
I know this issue has been closed for a while, but I just wanted to also express my interest in this feature, and it has been asked in [other places](https://github.com/Orange-OpenSource/hurl/discussions/1349) as well.
It's particularly useful when you have a bunch of parameters, only some variable amount of which users usually have to care about, but which all need to be flexible to support different environments such as CI and dev environments.
You either require every user to set all the variables in their environment to the defaults or you require them to pass a bunch of variables or variable files with the same values each invocation. Neither of which is the end of the world, but they make working with hurl more cumbersome than it feels like it should be.

A simple workaround it to make a simple bash script wrapper which only calls hurl with the default arguments or given overwrites from arguments or the environment, though native support in hurl itself would be nice.
