### ISSUE TITLE
add isNull predicate

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#163]
An api returns a json `empty` field with `null` data type, it would be helpful if i could test it with a simple `isNull` predicate:

```
GET https://my_api.com

[Asserts]
jsonpath "$.empty" isNull
```
what do you think about it ?

**Comment by fabricereix** [comment]
Yes, you can add this kind of shortcuts
`isNull`  for `equals null`

similarly, we thought about adding
`true` for `equals true`

**Comment by fabricereix** [comment]
Finally, we are going to add operators such as '==' for equality (https://github.com/Orange-OpenSource/hurl/issues/171)
Using shortcut predicates such as `isNull` or `true` won't be really useful anymorel

```
[Asserts]
jsonpath "$.empty" == null
jsonpath "$.status" == true
```
