### ISSUE TITLE
Move query processing to filter

### ISSUE THREAD

**Issue by fabricereix** [Orange-OpenSource/hurl#1632]
Queries such as `xpath`/`jsonpath` take implicitly the response body as its textual input.
It would be interesting to move this processing to a filter so that it can be reusable.
for example, if the body is an HTML encoded in gb2312 (as described in #1560), we could use the following assert
```
bytes decode "gb2312" xpath "string(/html/head/title)" contains "Example" 
```

We will still keep the existing queries `xpath`/`jsonpath`.
They will be simply syntactic sugar. They will assume an UTF-8 encoded textual body.
```
xpath "string(/html/head/title)" contains "Example"         # xpath as a query (Sugar)
body xpath "string(/html/head/title)" contains "Example"    # xpath as a filter

```

**Comment by jcamiel** [comment]
See related #440
