### ISSUE TITLE
add beetween or within or inRange or range predicate

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#164]
An api returns a json value `beetween two int` or `beetween two float`, actually we can test it using `greaterThanOrEquals` mixed with `lessThanOrEquals`:

```
GET https://my_api.com

[Asserts]
jsonpath "$.my_int" greaterThanOrEquals 11
jsonpath "$.my_int" greaterThanOrEquals 36
```

 It would be helpful if i could test it with a simple `beetween` or `within` or `inRange` or `range` predicate:

```
GET https://my_api.com

[Asserts]
jsonpath "$.my_int" beetween 11-36
```

what do you think about it ?

**Comment by fabricereix** [comment]
I'm not too keen on this between operator.
But why not a `in` predicate. That's quite the opposite of the `include` predicate that we already have.

**Comment by jcamiel** [comment]
I agree that checking a range is a bit cumbersome with the current syntax.

```
GET http://sample.com
HTTP/1.1 *
status greaterThanOrEquals 200
status lessThan 300
```

What I don't like with a `inRange` predicate is:

1. it's consise, but not precise:
    ```
    GET http://sample.com
    HTTP/1.1 *
    status inRange 200-300
    ```
    Should status code be strictly less than 300 or can it be equal to 300 ? 
2. actual predicates values types (boolean, string, numbers, null) can be the result of various
   queries, and used in various predicates. No actual query result is a range, and the "range" type will be uniq to `inRange` predicates.
3. I don't think it's play well with templating
    Should we allow:
    ```
    GET http://sample.com
    HTTP/1.1 *
    status inRange {{min}}-{{max}}
    ```
    or
    ```
    GET http://sample.com
    HTTP/1.1 *
    status inRange {{range}}
    ```

Point 2 can maybe be adressed with different syntax: 

- in Python `range(a,b)` is a range >= a and < b
- in Kotlin `a..b` is a range >=a and <= b
- in Swift `a...b` is a range >=a and <=b, where `a..<b` is a range where >=a and <b

I like the Swift one and we could reuse it:

```
GET http://sample.com
HTTP/1.1 *
status inRange 200..<300
```

I wonder if an `inRange` predicate should be necessary if we had shorhand notation for common 
predicates:

```
GET http://sample.com
HTTP/1.1 *
status >= 200
status < 300
```

| Literal predicates  | Shorthand |
| --- | --- | 
| equals              | == (or =) |
| not equals          | !=        |
| greaterThan         | >         |
| greaterThanOrEquals | >=        |
| lessThan            | <         |
| lessThanOrEquals    | <=        |
| countEquals         | count ==  |

An Hurl snippet using litteral predicates:

```
GET http://sample.com
HTTP/1.1 *
[Asserts]
status greaterThanOrEquals 200
status lessThan 300
jsonpath "$.validated" equals true
jsonpath "$.userInfo.firstName" equals "Franck"
jsonpath "$.userInfo.lastName" equals "Herbert"
jsonpath "$.links" countEquals 12
jsonpath "$.state" not equals null
```

An Hurl snippet using shorthand predicates:

```
GET http://sample.com
HTTP/1.1 *
[Asserts]
status >= 200
status < 300
jsonpath "$.validated" == true
jsonpath "$.userInfo.firstName" == "Franck"
jsonpath "$.userInfo.lastName" == "Herbert"
jsonpath "$.links" count == 12
jsonpath "$.state" != null
```

This way, we could also support the following predicates:

| Literal predicates | Shorthand
|--- | --- |
| countGreaterThan         | count >   |
| countGreaterThanOrEquals | count >=  |
| countLessThan            | count <   |
| countLessThanOrEquals    | count <=  |

```
GET http://sample.com
HTTP/1.1 *
[Asserts]
status >= 200
status < 300
header "Set-Cookie" count == 3
jsonpath "$.validated" == true
jsonpath "$.userInfo.firstName" == "Franck"
jsonpath "$.userInfo.lastName" == "Herbert"
jsonpath "$.links" count >= 12
jsonpath "$.state" != null
```

**Comment by lepapareil** [comment]
I like the way swift and kotlin manages range function, and i think that swift gramar clearly meets all the need.

I also agree with you, shortand predicate is an expected functionality, from my point of view this is not incompatible with the existence of a range predicate as you describe:

```
GET http://sample.com
HTTP/1.1 *
status inRange 200..<30
```

**Comment by fabricereix** [comment]
The and logical operator should have condition on both sides
```
status >= 200 and status < 300
````

which can be simply written into the current format with 2 lines
```
status >= 200
status < 300
```


For the range, I would also like to have one the `from..to` notation
It is a shame that the `to` is not always inclusive or exclusive (inclusive in kotlin and exclusive in rust)
Rust has `..=` for inclusive range.

But I would use the range operator to simply create a list literal, no the predicate.
I would use it with the `in` predicate.
```
GET http://sample.com
HTTP/1.1 *
[Asserts]
status in 200..<300
```

**Comment by lepapareil** [comment]
re-up ! 😸
