### ISSUE TITLE
adding tls configuration to request section

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#166]
An api uses an old tls version, or an specific cert, in general, existing http clients (like curl) allow to set `tls configuration`, it would be helpful if i could specify `tls parameters` in `request section`:

```
GET https://my_api.com

[Tls]
tls-version: <1.0|1.1....>
ca-cert: <certificate[:password]>
ca-path: <path>
cert-status: <true|false>
cert-type: <type>
```

what do you think about it ?

**Comment by fabricereix** [comment]
We should indeed be able to set all these options.
So far, we have been using command-line options to specify "curl" options.
Matching the curl options is very clear and already known by curl users.

We plan to add these ssl-related options in the near future:
```
--cacert <file>
--capath <dir>
...
```

**Comment by jcamiel** [comment]
We the 1.7.0 `[Options]` section we can cons specify these _per request_:

```hurl
GET https://example.org
# An options section, each option is optional and applied only to this request...
[Options]
cacert: /etc/cert.pem   # a custom certificate file
insecure: true          # allows insecure SSL connections and transfers
```

Maybe @lepapareil @fabricereix we can close this one?
