### ISSUE TITLE
Undocumented breaking changes about the retry option

### ISSUE THREAD

**Issue by jcornaz** [Orange-OpenSource/hurl#1701]
### What is the current *bug* behavior?

With hurl `3.0.1` we could use a retry option:

```
[Options]
retry: true
```

But since hurl `4.0.0`, it now fails with:

```
   |
 3 | retry: true
   |        ^ expecting 'natural'
   |
```

### Steps to reproduce

create a `demo.hurl` file:
```
GET https://github.com/Orange-OpenSource/hurl
[Options]
retry: true
HTTP 200
```

and run `hurl demo.hurl`.

### What is the expected *correct* behavior?

As the [4.0.0](https://github.com/Orange-OpenSource/hurl/releases/tag/4.0.0) doesn't mention any breaking change, it should continue to accept the file as valid syntax and behave as `hurl 3.0.1` does.

 
### Execution context

- Hurl Version (`hurl --version`): 4.0.0
- Operating system and version: Linux pop-os 6.2.6

### Possible fixes

probably introduced by this commit: https://github.com/Orange-OpenSource/hurl/commit/b5277b33490079295865e9ee7c7ae2a23c6cf594

**Comment by fabricereix** [comment]
Hi @jcornaz,
yes we modified the `--retry` option to match the same curl option.
This is written in the release note as follows:
```
* Update --retry option to match curl option [#1475](https://github.com/Orange-OpenSource/hurl/issues/1475)
```
We are going to update the release note to make it clearer.

**Comment by jcornaz** [comment]
> Hi @jcornaz, yes we modified the `--retry` option to match the same curl option. This is written in the release note as follows:
> 
> ```
> * Update --retry option to match curl option [#1475](https://github.com/Orange-OpenSource/hurl/issues/1475)
> ```
> 
> We are going to update the release note to make it clearer.

Ok, thanks. How should we use it now?

Can you also consider to *not* break the API? (at least for future releases).

**Comment by fabricereix** [comment]
Like curl, it now takes a number (https://hurl.dev/docs/manual.html#retry).
Relating to the API, we don't plan to break it for the next few releases.
When we do it, we will update the major version as we did for this one.

**Comment by jcamiel** [comment]
Just to complete, you can see `--retry` in action on the documentation https://hurl.dev/docs/entry.html#retry and here https://hurl.dev/docs/samples.html#polling-and-retry.

```hurl
# Create a new job
POST http://api.example.org/jobs

HTTP 201
[Captures]
job_id: jsonpath "$.id"
[Asserts]
jsonpath "$.state" == "RUNNING"


# Pull job status until it is completed
GET http://api.example.org/jobs/{{job_id}}
[Options]
retry: 10   # maximum number of retry, -1 for unlimited

HTTP 200
[Asserts]
jsonpath "$.state" == "COMPLETED"
```

Basically, if you want to retry until every assert is ok without any maximum retry count, you can write `retry: -1`.

You can also see the tests suite: https://github.com/Orange-OpenSource/hurl/blob/master/integration/tests_ok/retry_option.hurl

Concerning breaking change, we try to respect semantic versioning now. A change of major version (from 3.0.1 to 4.0.0) indicates that we've big new features and potential breaking changes. Hurl 3.0.1 is working perfectly fine if you dont want to upgrade. Thats said, you're right, we will update the breaking change (feature-wise and binary-wise for Rust users) more prominently in the change log. Note also that we have a blog with an RSS feed and that we explain in details what and why we made some changes => https://hurl.dev/blog/ (post for 4.0.0 in a few days)

**Comment by jcornaz** [comment]
> Like curl, it now takes a number (https://hurl.dev/docs/manual.html#retry).

Ok, thanks.

> Relating to the API, we don't plan to break it for the next few releases.

Awesome, thanks.

> When we do it, we will update the major version as we did for this one.

I don't care much about the version number. It is breaking changes themselves that are annoying. We use hurl as part of our testing automation and daily developer tool. If it is reasonably easy to pin the version on CI, it is quite painful to align all developer workspaces as the most package managers (like `brew` or `cargo install`) silently update to the latest version, breaking or not, and we have to synchronize the update for all developers and all projects.
