### ISSUE TITLE
Replace `sxd_document` with an adequate alternative, e.g. xml-rs

### ISSUE THREAD

**Issue by bnoctis** [Orange-OpenSource/hurl#1702]
I'm looking into [packaging `hurl` for Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001779). The `hurl_core` crate depends on `sxd_document`, a long inactive crate that depends on another long inactive crate `peresil` and an extremely old version of `typed-arena`. All `sxd_document` does there is to provide a `is_valid()` function, matching its output to `Ok(_)`.

I suggest `xml-rs`, a widely used XML library with no dependency, already packaged in Debian.

**Comment by jcamiel** [comment]
Hi, first of all thank you for looking into Debian packaging. We're a bit stuck on this, we've struggled to start and need some help on this for sure (see #366).
Nice catch for `sxd_document`, we'll see how to remove the dependency asap indeed.
Some thing to know: we have two depedencies that _may_ need a bit of work for a proper Debian package: 

- `curl-rust` which is a binding to curl
- `libxml` which is a binding to libxml (for evaluating XPath expression).

A part from these core dependencies, don't hesitate to make issues if you see other dependencies that could be remove / replaced to make a Debian package easier.

**Comment by bnoctis** [comment]
I'm not asking to replace it because it's not in Debian ;) but rather, it's long inactive (aka unmaintained) and has a higher chance of being vulnerable (especially so handling XML). We are happy to package the deps as long as they are useful.
