### ISSUE TITLE
Support Shorthand Predicates

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#171]
## Rational

Current Hurl predicates syntax is text based and can be a little tedious (see #164):

```
GET https://my_api.com

[Asserts]
jsonpath "$.my_int" greaterThanOrEquals 11
jsonpath "$.my_int" lessThan 36
```

A more "natural" way of writting this snippet could be:

```
GET https://my_api.com

[Asserts]
jsonpath "$.my_int" >= 11
jsonpath "$.my_int" < 36
```

## Shorthand Proposed Syntax

Predicate textual | Predicate shorthand
--- |:---:
equals | ==
greaterThan | >
greaterThanOrEquals | >=
lessThan | <
lessThanOrEquals | <=
countEquals | count ==
startsWith | 
contains | 
includes | 
matches | =~
exists |
isInteger |
isFloat |
isBoolean |
isString |
isCollection |

> `matches` shorthand is `~=` based on [Ruby matching operator](https://ruby-doc.org/core-2.3.0/Object.html#method-i-3D~) 
> and [Perl matching operator](https://perldoc.perl.org/overload#Overloadable-Operations)

And the following predicates (not present in Hurl 1.1.0 grammar)

Predicate textual | Predicate shorthand
--- |:---:
notEquals | !=
countGreaterThan | count >
countGreaterThanOrEquals | count >=
countLessThan | count <
countLessThanOrEquals | count <=
countNotEquals | count !=

Negate a predicate is still possible :

```hurl
GET https:/sample/api
HTTP/* *
[Asserts]
jsonpath "$.name" not == "toto"
jsonpath "$.count" not > 12
jsonpath "$.id" not != "dude"
```

Even if there is a "better" way of writing these asserts: (somethong maybe adressable by `hurlfmt`?)

```hurl
GET https:/sample/api
HTTP/* *
[Asserts]
jsonpath "$.name" != "toto"
jsonpath "$.count" <= 12
jsonpath "$.id" == "dude"
```

## Comparison

An Hurl snippet using litteral predicates:

```
GET http://sample.com
HTTP/1.1 *
[Asserts]
status greaterThanOrEquals 200
status lessThan 300
jsonpath "$.validated" equals true
jsonpath "$.userInfo.firstName" equals "Franck"
jsonpath "$.userInfo.lastName" equals "Herbert"
jsonpath "$.links" countEquals 12
jsonpath "$.state" not equals null
```

An Hurl snippet using shorthand predicates:

```
GET http://sample.com
HTTP/1.1 *
[Asserts]
status >= 200
status < 300
jsonpath "$.validated" == true
jsonpath "$.userInfo.firstName" == "Franck"
jsonpath "$.userInfo.lastName" == "Herbert"
jsonpath "$.links" count == 12
jsonpath "$.state" != null
```

### Questions

- Do we keep textual predicates ? Note that certains predicates doesn't have a shorthand (like `contains`, `exist`, etc...). Maybe `hurlfmt` can raise a warning. in this case. Hurl syntax is not too popular and can be modified.
- In case we keep the textual and shorthand predicates, we should act a preferred one and updates the samples accordingly.

**Comment by lepapareil** [comment]
Can we use `^ ` for `startWith` ?

**Comment by jcamiel** [comment]
`matches` proposed shorthand (`~=`) is based on [Ruby matching operator](https://ruby-doc.org/core-2.3.0/Object.html#method-i-3D~) and [Perl matching operator](https://perldoc.perl.org/overload#Overloadable-Operations).

If we keep the two syntax (textual and shorthand) why not having a shorthand for `startsWith`, if we found something similar in other languages. If we keep only shorthand, I think that we should keep the usual ones (`==`, `!=`, `>`, `<`, `>=`, `<=`) and some textual for the other. In this case, I'm not sure bout `matches` vs `~=`

**Comment by jcamiel** [comment]
Literal | ShortHands | Lint (preferred)
--- | --- | ---
jsonpath "$.books" equals 12 | jsonpath "$.books" == 12 | jsonpath "$.books" == 12  
jsonpath "$.books" not equals 12 | jsonpath "$.books" not == 12 | jsonpath "$.books" != 12
jsonpath "$.books" notEquals 12 | jsonpath "$.books" != 12 | jsonpath "$.books" != 12
jsonpath "$.books" not notEquals 12 | jsonpath "$.books" not != 12 | jsonpath "$.books" == 12
jsonpath "$.books" countEquals 12 | jsonpath "$.books" count == 12 | jsonpath "$.books" count == 12  
jsonpath "$.books" not countEquals 12 | jsonpath "$.books" not countEquals 12 | jsonpath "$.books" count != 12
jsonpath "$.books" countNotEquals 12 | jsonpath "$.books" count != 12 | jsonpath "$.books" count != 12  
jsonpath "$.books" not countNotEquals 12 | jsonpath "$.books" not count != 12 | jsonpath "$.books" count == 12 
jsonpath "$.books" countLessThan 12 | jsonpath "$.books" count <= 12 | jsonpath "$.books" count <= 12  
jsonpath "$.books" not countLessThan 12 | jsonpath "$.books" not count <= 12 | jsonpath "$.books" count > 12  
jsonpath "$.books" countLessThanOrEquals 12 | jsonpath "$.books" count <= 12 | jsonpath "$.books" count <= 12  
jsonpath "$.books" not countLessThanOrEquals 12 | jsonpath "$.books" not count <= 12 | jsonpath "$.books" count > 12  
jsonpath "$.books" lessThan 12 | jsonpath "$.books" < 12 | jsonpath "$.books" < 12  
jsonpath "$.books" not lessThan 12 | jsonpath "$.books" not < 12 | jsonpath "$.books" >= 12  
jsonpath "$.books" lessThanOrEquals 12 | jsonpath "$.books" <= 12 | jsonpath "$.books" <= 12  
jsonpath "$.books" not lessThanOrEquals 12 | jsonpath "$.books" not <= 12 | jsonpath "$.books" > 12  
jsonpath "$.books" greaterThan 12 | jsonpath "$.books" > 12 | jsonpath "$.books" > 12  
jsonpath "$.books" not greaterThan 12 | jsonpath "$.books" not > 12 | jsonpath "$.books" <= 12  
jsonpath "$.books" greaterThanOrEquals 12 | jsonpath "$.books" >= 12 | jsonpath "$.books" >= 12  
jsonpath "$.books" not greaterThanOrEquals 12 | jsonpath "$.books" not >= 12 | jsonpath "$.books" < 12  
jsonpath "$.books" contains "12" | jsonpath "$.books" contains "12" | jsonpath "$.books" contains "12"
jsonpath "$.books" not contains "12" | jsonpath "$.books" not contains "12" | jsonpath "$.books" not contains "12"
jsonpath "$.books" startsWith "12" | jsonpath "$.books" startsWith "12" | jsonpath "$.books" startsWith "12"
jsonpath "$.books" not startsWith "12" | jsonpath "$.books" not startsWith "12" | jsonpath "$.books" not startsWith "12"
jsonpath "$.books" exists | jsonpath "$.books" exists | jsonpath "$.books" exists
jsonpath "$.books" not exists | jsonpath "$.books" not exists | jsonpath "$.books" not exists
