### ISSUE TITLE
Feature request: allow variable in header name

### ISSUE THREAD

**Issue by iredmail** [Orange-OpenSource/hurl#1710]
### Problem to solve

Currently we have to write raw header name used in a request, for example, `X-MY-PRODUCT-API-Key: <my-key>`. We have many http requests for testing, so we want to use a variable name to define the header name in a variable file, for example: `header_api_key=X-MY-PRODUCT-API-Key`, then use this variable in request:
```
GET https://...
{{header_api_key}}: <my-key>
```

hurl reports error:
```
error: Parsing literal
  --> mytest.hurl:5:19
   |
 5 | {{header_api_key}}: {{global_admin_api_key}}
   |                   ^ expecting 'line_terminator'
   |
```

### Proposal

Allow variable in http header name.

**Comment by iredmail** [comment]
Similar issue: #898

**Comment by fabricereix** [comment]
Hi @iredmail,
we plan to support more and more curl options.
The `--header` option seems to match your usecase.

```
GET https://...
[Options]
header: {{header_api_key}}: <my-key>
```

We could support it for the next release.

**Comment by iredmail** [comment]
Thanks for the update and great work.
I will wait for next release. :)

**Comment by Vadim-devs** [comment]
The same for cookie btw, it will be great feature to add more variants with vars :)
Thank you!

**Comment by jcamiel** [comment]
@iredmail @vadimgodev landing no master, you can now use templates in header name/values, and also in cookie sections:

```hurl
GET https://...
{{header_api_key}}: {{global_admin_api_key}}
```

Should work :

```shell
$ hurl --test --variable header_api_key=MY_KEY global_admin_api_key=FOO test.hurl
```

You can use also `[Options]` section:

```hurl
GET https://...
{{header_api_key}}: {{global_admin_api_key}}
[Options]
variable: header_api_key= MY_KEY
variable: global_admin_api_key=FOO
HTTP 200
```

**Comment by iredmail** [comment]
@jcamiel Thanks for the great work. :)

**Comment by vadimgodev** [comment]
Nice, thank you so much! Now I can short my python wrapper for tests :)
