### ISSUE TITLE
support variable when sourcing payload from file

### ISSUE THREAD

**Issue by teto** [Orange-OpenSource/hurl#1731]
### Problem to solve

I would like to be able to use a variable in the statement referencing an external payload
`file,{{TEST_DATA_FOLDER}}/v2/payload.json;`

but that doesn't seem supported at the moment.

### Proposal

Interpolate .env variables in the `file,<path>` statement

### Additional context and resources

I am a user/maintainer of https://github.com/rest-nvim/rest.nvim and I would be ready to have rest.nvim format converge to hurl's format that looks easier to parse with e.g., tree-sitter.  https://github.com/rest-nvim/rest.nvim/issues/195 . 
rest.nvim has some advantages over hurl.nvim (can run per-request, I can select their order interactively etc) but hurl is more robust. I would like to be able to use both tools on the same file (or the ability to export/import from both formats easily).

### Tasks to complete

- [ ] ...

**Comment by jcamiel** [comment]
Hi @teto, at least reading our grammar it should be actually supported  => https://hurl.dev/docs/grammar.html#filename

Yet, we haven't implemented it. See also #464 with the same issue. We should really implement it asap!

**Comment by teto** [comment]
feel free to close as duplicate then. when you mention a grammar, there is no tree-sitter grammar implemented yet ? I ask because I've written one (incomplete) for rest.nvim but it's nice to list query, filter them etc. The way hurl is used, I dont think it's necessary but that might be a fun project if someone wanna play with tree-sitter :)

**Comment by jcamiel** [comment]
We've have to work around tooling, a tree-sitter parser is certainly on our radar! No work has started yet though.

**Comment by teto** [comment]
Is there a reason why absolute paths can't be used ? 
```
$ hurl v2/trial.hurl --variables-file .env
error: Unauthorized file access
   --> v2/trial.hurl:8:6
    |
  8 | file,/home/teto/test/data/payloads/v2/ComputationalModel.json;
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unauthorized access to file /home/teto/test/data/payloads/v2/ComputationalModel.json, check --file-root option
```
It works with --file-root but still I was surprised :)

**Comment by jcamiel** [comment]
We have make this constraint for security reason. If the included file is in a children directory of the Hurl file parent folder, file inclusion should work without `--file-root`. If you want to include files that are in a very different directory (let's say for instance `/etc/passwd`) you have to explicitly use `--file-root` (unless there is a bug of course)

**Comment by teto** [comment]
about the treesitter grammar, there is already one actually ^^' 
https://github.com/pfeiferj/tree-sitter-hurl/

**Comment by ppaulweber** [comment]
@jcamiel is there any update in using and loading a file-based content (e.g. for the request body or only a JSON value) in a `hurl` request specification?

**Comment by jcamiel** [comment]
Hi @ppaulweber you can use a file body now (see https://hurl.dev/docs/request.html#file-body)
For instance, you can send a JSON body with this kind of file:

```hurl
POST https://example.org/api/foo
Content-Type: application/json
file,data.bin;
HTTP 201
```

Do you have something else in mind (or needs)?

**Comment by ppaulweber** [comment]
@jcamiel great, thx for the quick reply ... yes, my use case would be more in the sense to include a file contents as e.g. JSON string value in the form of:

```
POST https://example.org/api/foo
{
    "key": {{file,data.bin;}}
}
HTTP 200
```

The problem with using just directly variables is on the newline and escape encoding in the variable string itself. Therefore, a "include" or "file load" on specific positions in the JSON payload would be one of my current needs.

**Comment by jcamiel** [comment]
OK, that's very clear. We have already [`filters`](https://hurl.dev/docs/filters.html) that allow to transform value and we have in mind kind of "generators" to create/inject data (like random data or file inclusion in JSON parts). That will address your use case, we just need to prioritize it.

**Comment by ppaulweber** [comment]
@jcamiel perfect, good to know ... let me know if I can help out with the implementation or is there already a dedicated issue or PR for this?

**Comment by jcamiel** [comment]
Thanks, first we need to state and finalize what will be the syntax (and what we can support for generators). I'll link here the PR/issues as soon as we advance.
