### ISSUE TITLE
add ToFloat filter

### ISSUE THREAD

**Issue by claytonneal** [Orange-OpenSource/hurl#1732]
### Problem to solve

When json response contains a string quoted float number, cannot use isFloat assertion

### Proposal

add toFloat filter

**Comment by beaterblank** [comment]
I can take this issue very similar to previous issue I have worked on.

**Comment by chengyu2000311** [comment]
Hey, I made a pr to add this feature https://github.com/Orange-OpenSource/hurl/pull/2772? BTW, I really love the idea of hurl :)
