### ISSUE TITLE
option to "keep going" when entry connection fails

### ISSUE THREAD

**Issue by khimaros** [Orange-OpenSource/hurl#1734]
### Problem to solve

i'd like to test a number of endpoints from a single hurl file and continue testing other entries when one or more of them have a connection timeout.

### Proposal

add a `--keep-going` flag to the command line or a configuration option which can be specified on a per-entry basis. i see benefits to either, with the former being less work when there are many entries which should run through to the end regardless, and with the latter being a bit more flexible.

### Additional context and resources

when a single endpoint times out, i'd still like to see the success report eg. `7/8 entries passed`

**Comment by jcamiel** [comment]
Hi, we have [`--fail-at-end` option](https://hurl.dev/docs/manual.html#fail-at-end) that continue the execution of an Hurl file when there are asserts errors. I don't know what we do in case of timeout but it's worth trying.

**Comment by khimaros** [comment]
@jcamiel that did the trick, thanks!

i interpreted that option to mean "always fail at the end, even if all tests pass" :)

perhaps the flag description in `--help` could be improved?

**Comment by jcamiel** [comment]
Agreed, I had to double checked myself

**Comment by fabricereix** [comment]
we could maybe have ` --ignore-assert-error`
