### ISSUE TITLE
Add non-default vendored-openssl feature flag

### ISSUE THREAD

**Issue by stefankreutz** [Orange-OpenSource/hurl#1746]
### Problem to solve

I cannot compile hurl on OpenBSD -current because the `openssl-sys` crate is incompatible with the (unreleased) development version of LibreSSL.

The relevant output of `cargo check` is:

```
   Compiling curl-sys v0.4.63+curl-8.1.2
   Compiling curl v0.4.44
error: failed to run custom build command for `openssl-sys v0.9.90`
...
  This crate is only compatible with OpenSSL (version 1.0.1 through 1.1.1, or 3.0.0), or LibreSSL 2.5
  through 3.8.0, but a different version of OpenSSL was found. The build is now aborting
  due to this version mismatch.
```

### Proposal

Add a non-default `vendored-openssl` feature flag to `packages/hurl/Cargo.toml` to enable the corresponding `static-ssl` feature flags of the `curl` and `curl-sys` crates.

I'd be willing to prepare a pull request.

### Additional context and resources

Many crates provide a non-default `vendored-openssl` feature flag to address the same problem. Hence I would prefer this name over e.g. `static-ssl`.

The feature flag would effectively enable the `vendored` feature flag for the [openssl crate](https://docs.rs/openssl/latest/openssl/).

An alternative could be to use Rustls instead of OpenSSL. But this is experimental for now.

### Tasks to complete

- [ ] Add `vendored-openssl` feature flag to Cargo.toml.
- [ ] Ensure that CI tests at least without the `vendored-openssl` feature flag.

**Comment by jcamiel** [comment]
Hi @stefankreutz thank you for the issue. I must admit it is not my zone of knowledge! You say "Many crates provide a non-default vendored-openssl", do you have any crates in mind that we could analyse to understand what we have to do? Thanks!

**Comment by stefankreutz** [comment]
Hi @jcamiel 

Thanks for asking. [Here](https://doc.rust-lang.org/cargo/reference/features.html) is the reference for Cargo's feature flags, [here](https://github.com/rust-lang/cargo/blob/master/Cargo.toml#L206) is an example of a crate using a `vendored-openssl` feature flag (Cargo itself), and [here](https://github.com/search?q=vendored-openssl+path%3A**%2FCargo.toml&type=code) are lots of other crates on Github using a similar feature flag.

In case of the binary crate Hurl, my request boils down to changing Hurl's Cargo.toml file as follows:

```
[features]
strict = []
vendored-openssl = ["curl/static-ssl", "curl-sys/static-ssl"]
default = []
```

With this, Hurl can be installed with a statically linked vendored OpenSSL as follows:

```
$ cargo install --features vendored-openssl hurl
```

Without the `--features` flag, everything is as before.

Regarding CI, we should ensure that Cargo isn't (only) invoked with the `--all-features` flag like so (which is a common pattern):

```
cargo check/test/foo --all-features
```

PS: I'll be unavailable for some days after Friday.

**Comment by jcamiel** [comment]
Thanks for the feedback, it really helps us. Two others maintainers and me are going in summer holidays so things are going a little slower now. We keep your issue in mind and update Hurl asap.

**Comment by jcamiel** [comment]
Hi @stefankreutz I've made a branch with the new feature flag here => origin/1746-add-non-default-vendored-openssl-feature-flag
I've struggle to compile Hurl with this flag on OpenBSD -current, could you test it on your side when you've time to see if it's OK?

**Comment by stefankreutz** [comment]
Hey @jcamiel. I can build and run Hurl from this branch on OpenBSD/amd64 -current 👍

**Comment by jcamiel** [comment]
Top, I'll merge it on master then
