### ISSUE TITLE
Missing "sudo" in the README.md

### ISSUE THREAD

**Issue by komark06** [Orange-OpenSource/hurl#1752]
In the [Debian / Ubuntu installation](https://github.com/Orange-OpenSource/hurl#debian--ubuntu), there is a missing sudo in the second apt command.

### Possible fixes

 [PR](https://github.com/Orange-OpenSource/hurl/pull/1751)

**Comment by jcamiel** [comment]
Thanks @komark06 for the issue and PR. I will tag this one as documentation
