### ISSUE TITLE
Generate emails and dates

### ISSUE THREAD

**Issue by lukackaadam** [Orange-OpenSource/hurl#1758]
### Problem to solve
Is there a way to generate random string? I need to generate random emails to test sign ups but can't find anything how to do this.

Also I need generate dates and also have not seen an option ho to do this.

**Comment by jcamiel** [comment]
Hi @lukackaadam yes currently there is no way to generate data inside a Hurl file. We have syntax and solution in mind but nothing really ready. For the moment, you can generate data outside Hurl with a script and inject it through various way:

- by using [--variable option](https://hurl.dev/docs/manual.html#variable)
- by using [--variables-file option](https://hurl.dev/docs/manual.html#variables-file)
- by defining environment variables, for instance HURL_foo=bar
- by defining variables in an [[Options] section](https://hurl.dev/docs/request.html#options)

(See [Injecting Variables](https://hurl.dev/docs/templates.html#injecting-variables) in the docs)

Hope you can workaround it!

**Comment by jcamiel** [comment]
Hi @lukackaadam 

With Hurl 6.0.0, we’re introducing [functions](https://hurl.dev/docs/templates.html#functions) to generate dynamic values. Current functions are:

- newUuid to generate an [UUID v4 random string](https://en.wikipedia.org/wiki/Universally_unique_identifier),
- newDate to generate an [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339) UTC date string, at the current time.
In the following example, we use the newDate function to generate a dynamic query parameter:

```
GET https://example.org/api/foo
[QueryStringParams]
date: {{newDate}}
HTTP 200
```

Run a GET request to https://example.org/api/foo?date=2024%2D12%2D02T10%3A35%3A44%2E461731Z where the date query parameter value is 2024-12-02T10:35:44.461731Z URL encoded.


```
POST https://example.org/api/foo
{
  "name": "foo",
  "email": "{{newUuid}}@test.com"
}
```

When run, the request body will be:

```
{
  "name": "foo",
  "email": "0531f78f-7f87-44be-a7f2-969a1c4e6d97@test.com"
}
```
