### ISSUE TITLE
hurlfmt standalone option only with html output not working

### ISSUE THREAD

**Issue by jlazic** [Orange-OpenSource/hurl#1759]
### What is the current *bug* behavior?
Exporting standalone HTML of hurl file with format option says format is deprecated and to use out instead
```
hurlfmt --format html --standalone site.hurl
--format is deprecated. use --out instead.
```

But when format is replace with out, standalone option errors out with

```
hurlfmt --out html --standalone site.hurl
use --standalone option only with html output
```

hurlfmt 4.0.0
OpenSUSE Thumbleweed

**Comment by jcamiel** [comment]
Thanks for the bug report @jlazic
