### ISSUE TITLE
😎☀️Hurl Summer Holidays🏄‍♂️🏝

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#1762]
```hurl
GET https://hurl.dev/api/maintainers
HTTP 200
[Asserts]
jsonpath "$.state" == "HOLIDAYS"
```

# Summer Holidays

Hi! Things will be a little slower here. Our maintainers are taken a well deserved summer break, for a few weeks.
Don't hesitate to send us issues and enhancements requests, we'll treat them as usual, just a little bit slower!

Regards, 

@jcamiel, @fabricereix and @lepapareil

**Comment by chenrui333** [comment]
I just want to say thank you for the great work!! And enjoy the well deserved summer time.
