### ISSUE TITLE
Intercept / assert multiple redirects?

### ISSUE THREAD

**Issue by Nezteb** [Orange-OpenSource/hurl#1763]
### Problem to solve

I'm trying to test some endpoints that include 3 redirects. As a redacted/contrived/janky example:

1. Initial request: `GET /auth`
2. `/auth` redirects to `GET /validateAge`
2. `/validateAge` redirects to `GET /validateLocation`
4. `/validateLocation` redirects to `GET /home`

I want to follow each redirect and validate the `Location` header of the each response.

Let's say my `hurl` file looks like:
```
GET http://localhost:8080/auth

HTTP 302
Location: http://localhost:8080/validateAge
```

This works, but I want to validate the other redirects as well. So I add the following to my `hurl` file:
```
GET http://localhost:8080/auth
[Options]
location: true

HTTP 200
Location: http://localhost:8080/home
```

This works but doesn't let me validate the other redirects.

### Proposal

My "simple" idea is to allow an option such as:
```
location: n
```
Where `n` is how many redirects to actually follow.

So in my case, I could do:
```
GET http://localhost:8080/auth
[Options]
location: 2

HTTP 302
Location: http://localhost:8080/validateLocation
```

It follows the first two redirects and then stops so I can validate the result. This still isn't ideal because to test all 3 redirects I'd need to duplicate the `GET` entries with `location: false`, `location: 1`, `location: 2`, and `location: true`.

A more "complex" solution would be to allow something like:
```
GET http://localhost:8080/auth
[Options]
location: true

HTTP 302
Location: http://localhost:8080/validateAge
REDIRECT 302
Location: http://localhost:8080/validateLocation
REDIRECT 302
Location: http://localhost:8080/home
HTTP 200
```

I opted for a new keyword because instead of `HTTP` because it'd probably be easier to implement but may not be "correct".

### Additional context and resources

The closest thing I can find to this is [the `--max-redirs` flag](https://hurl.dev/docs/manual.html#max-redirs), but that errors out instead of ignoring future redirects.

Let me know what y'all think! There may be something else I can do with `hurl` to accomplish what I'm trying to do, or there may be an even simpler way to implement this functionality. 😄

**Comment by jcamiel** [comment]
Hi @Nezteb usually what we would do is to decompose the redirection step by step and add assert on header location.
For instance, in your case:

```hurl
GET https://foo.com/auth
HTTP 302
[Asserts]
header "Location" == "/validateAge"

GET https://foo.com/validateAge
HTTP 302
[Asserts]
header "Location" == "/validateLocation"

GET https://foo.com/validateLocation
HTTP 302
[Asserts]
header "Location" == "/home"

GET https://foo.com/home
HTTP 200
```

This is idiomatic Hurl as it explicitely shows the request/response run.

We have also a proposal to implement a `redirect` query (#922) that could return a collection of redirection from a certain request.
For instance, in your case, the Hurl file could be:
 
```hurl
GET https://foo.com/auth
[Options]
location: true     # Configure Hurl to follow redirection instead of decomposing steps
HTTP 200
url == "https://foo.com/home"            # The final URL, this query is already implemented 
redirect count 3                         # Query redirect not yet implemented
redirect nth 0 == "/validateAge"
redirect nth 1 == "/validateLocation"
redirect nth 2 == "/home"
```

**Comment by Nezteb** [comment]
Ahh that does make sense. I tried it, and in my case (using [Supabase Edge Functions](https://supabase.com/edge-functions)), I'm running into a werid issue where one of the redirects in this change is redirecting to itself through Cloudflare, so I'll give more details with only a few redactions:

My `hurl` file:
```
GET http://{{supabase_project_id}}.supabase.co/functions/v1/app-auth-proxy
Authorization: Basic {{api_key}}
[QueryStringParams]
url: draftbit://SomeScreen?access_token=xxx
[Options]
location: true
```

```
> hurl supabase.hurl --verbose
* Options:
*     fail fast: true
*     follow redirect: false
*     insecure: false
*     max redirect: 50
*     retry: 0
* Variables:
*     api_key: mylongjwtauthtokenfromsupabase
*     supabase_project_id: myuniqueaccountid
* ------------------------------------------------------------------------------
* Executing entry 1
*
* Entry options:
* location: true
*
* Cookie store:
*
* Request:
* GET http://myuniqueaccountid.supabase.co/functions/v1/app-auth-proxy
* Authorization: Basic mylongjwtauthtokenfromsupabase
* [QueryStringParams]
* url: draftbit://SomeScreen?access_token=xxx
*
* Request can be run with the following curl command:
* curl --header 'Authorization: Basic mylongjwtauthtokenfromsupabase' --location 'http://myuniqueaccountid.supabase.co/functions/v1/app-auth-proxy?url=draftbit%3A%2F%2FSomeScreen%3Faccess%5Ftoken%3Dxxx'
*
> GET /functions/v1/app-auth-proxy?url=draftbit%3A%2F%2FSomeScreen%3Faccess_token%3Dxxx HTTP/1.1
> Host: myuniqueaccountid.supabase.co
> Accept: */*
> Authorization: Basic mylongjwtauthtokenfromsupabase
> User-Agent: hurl/4.0.0
>
* Response: (received 0 bytes in 211 ms)
*
< HTTP/1.1 301 Moved Permanently
< Date: Fri, 14 Jul 2023 00:00:36 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: max-age=3600
< Expires: Fri, 14 Jul 2023 01:00:36 GMT
< Location: https://myuniqueaccountid.supabase.co/functions/v1/app-auth-proxy?url=draftbit%3A%2F%2FSomeScreen%3Faccess_token%3Dxxx
< Server: cloudflare
< alt-svc: h3=":443"; ma=86400
<
*
* => Redirect to https://myuniqueaccountid.supabase.co/functions/v1/app-auth-proxy?url=draftbit%3A%2F%2FSomeScreen%3Faccess_token%3Dxxx
*
> GET /functions/v1/app-auth-proxy?url=draftbit%3A%2F%2FSomeScreen%3Faccess_token%3Dxxx HTTP/1.1
> Host: myuniqueaccountid.supabase.co
> Accept: */*
> User-Agent: hurl/4.0.0
>
* Response: (received 0 bytes in 379 ms)
*
< HTTP/1.1 303 See Other
< Date: Fri, 14 Jul 2023 00:00:36 GMT
< Content-Length: 0
< Connection: keep-alive
< Location: draftbit://SomeScreen?access_token=xxx
< CF-Cache-Status: DYNAMIC
< Strict-Transport-Security: max-age=2592000; includeSubDomains
< Vary: Accept-Encoding
< Via: 1.1 google
< alt-svc: h3=":443"; ma=86400
< x-deno-timing: system;dur=0,deployment;dur=2
< x-deno-utilization: 0.300
< Server: cloudflare
<
*
* => Redirect to draftbit://SomeScreen?access_token=xxx
*
error: HTTP connection
  --> supabase.hurl:1:5
   |
 1 | GET http://{{supabase_project_id}}.supabase.co/functions/v1/app-auth-proxy
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ (1) Protocol "draftbit" not supported or disabled in libcurl
   |
```

So the flow is something like:
```mermaid
sequenceDiagram
    participant h as Hurl (Client)
    participant p as Supabase Proxy<br/>(or Cloudflare?)
    participant f as My Supabase<br/>Edge Function
    participant m as Mobile App<br/>Deep Link

    h->>p: Intercepted by proxy
    Note over p: URL is supposedly:<br/>id.supabase.co<br>/functions/v1/myfunc
    p->>f: Redirect to m<br/> actual function
    Note over f: URL is also:<br/>id.supabase.co<br>/functions/v1/myfunc
    f->>m: My actual redirect<br/>(that I want to test)
```

If a proxy is intercepting my request and "redirecting" back to the same URL, I'm not sure I can emulate that with `hurl` alone? 🤔

**Comment by jcamiel** [comment]
Hi, 

Your test is very clear. What you should do is __not use location=true__, neither `--location`. If you ask Hurl to follow redirect, invevitably, Hurl is going to try to go to the scheme "draftbits://" and fail so.

You should try to decompose and play the redirection "by hand". Your Hurl file could be:

```hurl
GET http://{{supabase_project_id}}.supabase.co/functions/v1/app-auth-proxy
Authorization: Basic {{api_key}}
[QueryStringParams]
url: draftbit://SomeScreen?access_token=xxx
HTTP 302
[Asserts]
header "Location" == "https://{{supabase_project_id}}.supabase.co/functions/v1/app-auth-proxy?url=draftbit%3A%2F%2FSomeScreen%3Faccess_token%3Dxxx"


GET "https://{{supabase_project_id}}.supabase.co/functions/v1/app-auth-proxy?url=draftbit%3A%2F%2FSomeScreen%3Faccess_token%3Dxxx"
HTTP 303
[Asserts]
header "Location" == "draftbit://SomeScreen?access_token=xxx"
```

The final assert insure that the redirection will be on "draftbit://". You can also capture Location header to simplify the Hurl file but I prefer the first one, completely explicit:

```hurl
GET http://{{supabase_project_id}}.supabase.co/functions/v1/app-auth-proxy
Authorization: Basic {{api_key}}
[QueryStringParams]
url: draftbit://SomeScreen?access_token=xxx
HTTP 302
[Asserts]
header "Location" == "https://{{supabase_project_id}}.supabase.co/functions/v1/app-auth-proxy?url=draftbit%3A%2F%2FSomeScreen%3Faccess_token%3Dxxx"
[Captures]
next_url: header "Location"


GET {{next_url}}
HTTP 303
[Asserts]
header "Location" == "draftbit://SomeScreen?access_token=xxx"
```

In both case, you don't ask Hurl to follow location, you run one GEt request, check the Location header and run the next request with this header.

**Comment by Nezteb** [comment]
@jcamiel You're the greatest. That works flawlessly. This makes `hurl` easily the best HTTP testing tool I've ever used.

Thank you for all the help. 💙
