### ISSUE TITLE
IsEmpty doesn't seem to work on Object Collections

### ISSUE THREAD

**Issue by taigrr** [Orange-OpenSource/hurl#1788]
### What is the current *bug* behavior?
I have a server returning the following JSON:
`{
  "a":{
    "b":{
      "c":{},
      "d":{}
      }
    }
}`

And I have a hurl file with the following assertions:
```
# request endpoint:
POST http://server/request
{
   "x":"y",
   "z":420
}
HTTP 200
[Asserts]
jsonpath "$.a.b.c" != null
jsonpath "$.a.b.c" isCollection
jsonpath "$.a.b.c" isEmpty
```
1. Set up a server to return that response
2. Hit it with hurl `hurl --test   *.hurl`
3. See an assertion failure:

```
test.hurl: Running [1/1]
error: Assert failure
  --> test.hurl:11:0
   |
13 | jsonpath "$.a.b.c" isEmpty
   |   actual:   object
   |   expected: count equals to 0
   |   >>> types between actual and expected are not consistent
   |


test.hurl: Failure (1 request(s) in 2 ms)
--------------------------------------------------------------------------------
Executed files:  1
Succeeded files: 0 (0.0%)
Failed files:    1 (100.0%)
Duration:        2 ms
```

According to the documentation:

isEmpty | Query returns an empty collection | jsonpath "$.movies" isEmpty
-- | -- | --

Since isCollection returns true, my `c` object is a collection. It's clearly empty, why am I getting a type error?

### What is the expected *correct* behavior?
I should not get a type error

### Execution context
hurl 4.0.0 libcurl/8.2.0 OpenSSL/3.1.1 zlib/1.2.13 brotli/1.0.3840 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.55.1
Features (libcurl):  alt-svc AsynchDNS brotli HSTS HTTP2 IDN IPv6 Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
Features (built-in): brotli

archlinux, 6.4.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 19 Jul 2023 19:19:38 +0000 x86_64 GNU/Linux

### Possible fixes
It's possible isEmpty only works for arrays/slices, not all collection types, it looks to me like it's just implemented as an alias to `count == 0`. Probably need to do a type check and have multiple codepaths instead.

**Comment by jcamiel** [comment]
Hi @taigrr thanks for you detailed report. It's effectively a bug, `isEmpty` should have been OK in this case.

**Comment by jcamiel** [comment]
Thanks @taigrr for the issue, it should be fixed on master, you can test it if you know how to build a Rust application (see => [Build & Test](https://github.com/Orange-OpenSource/hurl/blob/master/CONTRIBUTING.md#build-and-test)) or wait for the next Hurl release landing in September. One thing that we can improve (I just need to check with @fabricereix) is do we allow `count` on an object ?

```hurl
POST http://server/request
{
   "x":"y",
   "z":420
}
jsonpath "$.a.b.c" != null       # OK
jsonpath "$.a.b.c" isCollection  # OK
jsonpath "$.a.b.c" isEmpty       # OK
jsonpath "$.a.b.c" count == 0    # ??
```

**Comment by taigrr** [comment]
Thanks! For my personal use case I am ok with this as-is, and I don't know of a use case for count on an object. I could check individual properties on the object, or I would want to know if it's null or empty or non-empty, but I don't know a real-world use case for count.
