### ISSUE TITLE
Does it support http3 later?

### ISSUE THREAD

**Issue by kingluo** [Orange-OpenSource/hurl#1804]
curl has [--http3](https://curl.se/docs/http3.html) option now, although it's not stable yet, anyway, is there a plan to support http3 in hurl?

**Comment by jcamiel** [comment]
Hi @kingluo yes Hurl uses libcurl under the hood so if you libcurl version has support for HTTP3, Hurl will benefit from it for free. We need to expose `--http1.0`, `--http1.1`, `--http2` and `--http3` flag though (see #1155)

**Comment by kingluo** [comment]
@jcamiel Thanks for your reply.
I'm wondering if it's possible to use libcurl's arbitrary parameters instead of restricting it in the code, would that add flexibility and make curl easy to upgrade? As said in this [previous issue.](https://github.com/Orange-OpenSource/hurl/issues/378)

**Comment by kingluo** [comment]
By the way, what's the timeline for 4.1.0?

**Comment by jcamiel** [comment]
Hurl is a Rust program that uses libcurl through programmatic binding. libcurl has "arbitrary" parameters through libcurl's C API so we have to make explicit code for each option.
4.1.0 will be released around mid-September (you can still build your own version from the main branch though if you need it)

**Comment by jcamiel** [comment]
Yes exactly, you can see the bulk of the code to create HTTP requests here for instance:

https://github.com/Orange-OpenSource/hurl/blob/b2f9e35db80b58360027d25b97a69a520bc3a7bd/packages/hurl/src/http/client.rs#L116-L194

To expose `--http2` option, we have to:

- make an `--http2` option for the Rust binary Hurl
- pass this option to the [Rust crate libcurl](https://github.com/alexcrichton/curl-rust)  `self.handle.http_version(HttpVersion::V2)`
- the Rust binding make a C call to libcurl `curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, (long)CURL_HTTP_VERSION_2TLS);`

These options are easy to implement in Hurl (it's a simple call to libcurl), so we could try to make it for Hurl 4.1.0

**Comment by kingluo** [comment]
Okay, got it. Thanks.

**Comment by jcamiel** [comment]
@kingluo on master (Hurl version 4.2.0+) we've now HTTP options version (`--http1.0`, `--http1.1`, `--http2`or `--http3`), provided the underlying libcurl supports the queried HTTP version.

You can specify it on CLI:

```shell
$ hurl --http3 foo.hurl
```

Or per request in a Hurl file:

```hurl
GET https://foo.com
[Options]
http3: true
HTTP 200

GET https://foo.com
[Options]
http2: true
HTTP 200
```

Cheers !

**Comment by kingluo** [comment]
@jcamiel Thanks for your reply.

FYI, I implemented a bash-based test framework for apisix, which looks like hurl.
If you are interested, please take a look. Thanks.
https://github.com/kingluo/apisix/blob/quic-tmp2/t/http3/test-limit-count.sh
