### ISSUE TITLE
Does hurlfile support `skip` semantics?

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#1815]
### Discussed in https://github.com/Orange-OpenSource/hurl/discussions/1810

<div type='discussions-op-text'>

<sup>Originally posted by **chenrui333** August  2, 2023</sup>
I am curious if I can `skip` the test cases in the hurlfile or skip the entire file.</div>

**Comment by egoarka** [comment]
Any thoughts about implementing it as `priority` option?

```
[Options]
priority: skip # skips only this test
priority: only # runs only this test
```

while for conditional test run, `Test` section might be added (might act as `Asserts`, but runs before test).

```
DELETE {{host}}/users/{{user_uuid}}
Authorization: Bearer {{access_token_admin}}
[Test]
captures {{user_uuid}} exists
```

or there is a way to make global variables and then combined with `Test` section:

```
GLOBAL
[Variables]
priority: only
test_token: 123
secret_token: ${SECRET_TOKEN} # env variable

GET http://localhost:8000/{{test_token}}

GET http://localhost:8000/2
[Test]
priority: only
```

**Comment by fabricereix** [comment]
Hi @egoarka,
I normally see a priority semantic with a numeric/increasing value.

What exactly is your case? You want to execute only one entry?
we currently have `--to-entry` option, we could also naturally add `--from-entry`
and thus, it would possible to execute only one entry.

**Comment by egoarka** [comment]
> I normally see a priority semantic with a numeric/increasing value.

Yeah, I thought that way at first and added example with numeric values, but changed my mind and deleted as it would be a bit more complex, although I didn't think of better name.


> What exactly is your case? You want to execute only one entry?
only one, or skip specific entries and run rest

**Comment by fabricereix** [comment]
Maybe `--entries 2,4`
It is similar to specifying pages when printing a document.

**Comment by egoarka** [comment]
That might work too, also what about declarative way of specifying it in hurl file?

**Comment by fabricereix** [comment]
that's where you would use the `skip` option.

```
GET {{url1}} 

GET {{url2}}
[Options]
skip: {{skip}}

GET {{url3}}

GET {{url4}}
[Options]
skip: {{skip}}
```

```
hurl --variable skip=true test.hurl
```
The entries 2 and 4 will be skipped.

**Comment by egoarka** [comment]
yeah, that works, but what if I have a ton of tests and I wanna run only the one in the middle, should I manually just find it's index and run with `--to-entry` option?

**Comment by egoarka** [comment]
But if let's say you add test above, test below, you should always keep in mind you have to use new line number to make it work, labeling specific tests might be better, so you just remember name of it and run it

**Comment by jcamiel** [comment]
@egoarka landing on master, you can use now skip:


```hurl
GET https://foo.com

GET https://bar.com
[Options]
skip: true

GET https://baz.com
```
