### ISSUE TITLE
PR offer: Support for adding AWS SigV4 Authorization headers

### ISSUE THREAD

**Issue by apparentorder** [Orange-OpenSource/hurl#1840]
### Problem to solve

I'd like to make authenticated requests to AWS API endpoins and GraphQL APIs with Hurl.

This is not possible with Hurl today, as it requires a custom Authorization request header with a cryptographic signature over several parts of the request (see [AWS SigV4](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html)).

### Proposal

Curl has built-in support for this, so it's basically a matter of adding an `aws-sigv4` option (command line and per-request) to Hurl and passing it through to Curl.

An example Hurlfile might look like this:
```
POST https://sts.eu-central-1.amazonaws.com/
[Options]
aws-sigv4: aws:amz:eu-central-1:sts
[FormParams]
Action: GetCallerIdentity
Version: 2011-06-15

HTTP 200
[Asserts]
xpath "string(//_:GetCallerIdentityResponse/_:GetCallerIdentityResult/_:Account)" == "123456789012"

# ----------------------------------------------------------------------

POST https://xxx.appsync-api.eu-central-1.amazonaws.com/graphql
[Options]
aws-sigv4: aws:amz:eu-central-1:appsync
\```graphql
query {
	listBadebombeWeisheitens { items { uuid } }
}
\```

HTTP 200
[Asserts]
jsonpath "$.errors" not exists
jsonpath "$.data.listBadebombeWeisheitens.items" count > 0
```

The required authentication data (secret key to generate the signature with) is passed via the `--user` flag (same as in Curl).

### Additional context and resources

In a "classic me", I have already patched Hurl to implement this – before reading CONTRIBUTING.md.

The patch is rather simple and does work as expected: it successfully makes signed requests against AWS API endpoints. Two small issues cropped up, one if which might be a bug in Curl's SigV4 implementation.

Before I take the time to dig deeper into those issues and create a PR, I'd like to await your feedback on the proposal, as suggested by CONTRIBUTING.md.

**Comment by jcamiel** [comment]
Seems very interesting to me! We're in "summer vacation mode" so don't worry if things are going a little slower.

**Comment by fabricereix** [comment]
I'm not familiar with this AWS signature. It would be great if you can add an integration test for it.

**Comment by apparentorder** [comment]
Thanks! Opened #1844 -> closing this issue
