### ISSUE TITLE
host precompiled arm binary for linux

### ISSUE THREAD

**Issue by softprops** [Orange-OpenSource/hurl#1873]
### Problem to solve

I'd like to be able to install hurl from a prebuild binary to run on linux. this relates to https://github.com/Orange-OpenSource/hurl/issues/536 but is focused on having the binary downloadable, as with other prebuild binaries, rather that embedded within an docker image. The reason being is that I already have a docker image which I'd like to install hurl into.

### Proposal

add a build pipeline step to build and host a release binary with github actions capable running on linux arm based systems

### Additional context and resources

I'd like to install a hurl binary within an existing docker container in aws ecs to facilitate hurl based container health checking within fargate. This is possible today but only when running on the more expensive non arm compute. This prevents me from using hurl if we switch to the cheaper aws arm architecture which we'd love to do.

### Tasks to complete

- [ ] ...

**Comment by lepapareil** [comment]
Hi @softprops, can you provide technical informations about the os/version (FROM section) of your custom Docker image in which you'd like to install hurl into ?

**Comment by lepapareil** [comment]
Hi @softprops, can you test this [beta arm64 generic linux binary](https://github.com/lepapareil/hurl/releases/download/4.0.0/hurl-4.0.0-generic-arm64.tar.gz) built with raspbian ?

**Comment by softprops** [comment]
Hi @lepapareil I'll try to test that this week. Thanks for the fast turn around on this

**Comment by softprops** [comment]
this might be me in I found this in a quick test

Im cross building a docker file for ecr (aws container registry) `docker buildx build . --platform=linux/amd64,linux/arm64 -t MY_ECR_TAG --push`

here's my abbreviated my docker file

```dockerfile
FROM amazoncorretto:17
ARG TARGETPLATFORM

# snip other things

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
  yum install -y tar gzip \
  && curl -sL https://github.com/Orange-OpenSource/hurl/releases/download/4.0.0/hurl-4.0.0-x86_64-linux.tar.gz \
  | tar xvz -C /tmp && echo "97bf2453f3d83c062ed3a72336bbdef9 /tmp/hurl-4.0.0/hurl" \
  | md5sum -c; \
  fi

RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
  yum install -y tar gzip \
  && curl -sL https://github.com/lepapareil/hurl/releases/download/4.0.0/hurl-4.0.0-test-generic-linux-arm64.tar.gz \
  | tar xvz -C /tmp && echo "60734668f51301f66c938ce0fc4fb5b6 /tmp/hurl-4.0.0/hurl" \
  | md5sum -c; \
  fi

ENV PATH="$PATH:/tmp/hurl-4.0.0"
```


I'm deploying this to ECS with an task definition targeted to run on arm

```yaml
      RuntimePlatform:
        CpuArchitecture: ARM64
        OperatingSystemFamily: LINUX
```

and then ecs exec'ing into this service (you can get a shell to do other testing) to get the arch type and run hurl --version as a smoke test

```sh
aws ecs execute-command \                                                                                                              
  --cluster MY_ECS_CLUSTER \
  --task $(aws ecs list-tasks \
  --cluster MY_ECS_CLUSTER \
  --output text \
  --query 'taskArns[*] | [0]' \
  | cut -d'/' -f3) \
  --container MY_CONTAINER_NAME \
  --interactive --command "/bin/sh -c 'uname -m && hurl --version'"

...

aarch64
hurl: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by hurl)
hurl: /lib64/libcurl.so.4: no version information available (required by hurl)
```

this output suggests the binary is recognized on arm but that maybe there is a problem with a glibc and curl dependency.

I ran the same to get the curl version installed and got

```
curl 8.0.1 (aarch64-koji-linux-gnu) libcurl/8.0.1 OpenSSL/1.0.2k-fips zlib/1.2.7 libidn2/2.3.0 libssh2/1.4.3 nghttp2/1.41.0
Release-Date: 2023-03-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets
```

**Comment by softprops** [comment]
this image is based on amazonlinux 2

I ecs exec'd into the container and looked in the /lib64 directory for those so files

```
sh-4.2# ls /lib64 | grep libcurl.so
libcurl.so.4
libcurl.so.4.8.0
sh-4.2# ls /lib64 | grep libc.so
libc.so.6
```

**Comment by lepapareil** [comment]
Unfortunately, `amazonlinux 2` uses `glibc 2.26`, you have to use `amazoncorretto:17-al2023` to get a newer version of `glibc`.

**Comment by softprops** [comment]
Thanks for the tip. I've almost got this.

I realized I could try this locally . here's my new test

```sh
docker run --platform=linux/arm64 -it --rm amazoncorretto:17-al2023 bash
```

```
dnf install -y tar gzip \
  && curl -sL https://github.com/lepapareil/hurl/releases/download/4.0.0/hurl-4.0.0-test-generic-linux-arm64.tar.gz \
  | tar xvz -C /tmp && echo "60734668f51301f66c938ce0fc4fb5b6 /tmp/hurl-4.0.0/hurl" \
  | md5sum -c; 

export PATH="$PATH:/tmp/hurl-4.0.0"

echo 'GET https://postman-echo.com/get?foo1=bar1&foo2=bar2' > test.hurl
hurl test.hurl

bash-5.2# hurl test.hurl 
hurl: /lib64/libcurl.so.4: no version information available (required by hurl)
{
  "args": {
    "foo1": "bar1",
    "foo2": "bar2"
  },
  "headers": {
    "x-forwarded-proto": "https",
    "x-forwarded-port": "443",
    "host": "postman-echo.com",
    "x-amzn-trace-id": "Root=1-64f66196-01f45fc07a63d42d0c6451ec",
    "accept": "*/*",
    "user-agent": "hurl/4.0.0"
  },
  "url": "https://postman-echo.com/get?foo1=bar1&foo2=bar2"
}

echo $?
0
```

there's only 1 minor dx drawback. I see `hurl: /lib64/libcurl.so.4: no version information available (required by hurl)` in hurls output but it doesn't seem to have a functional impact on its behavior

```
hurl --version
hurl: /lib64/libcurl.so.4: no version information available (required by hurl)
hurl 4.0.0 libcurl/8.0.1 OpenSSL/3.0.8 zlib/1.2.11 libidn2/2.3.2 nghttp2/1.55.1
Features (libcurl):  alt-svc AsynchDNS HSTS HTTP2 IDN IPv6 Largefile libz SPNEGO SSL UnixSockets
Features (built-in): brotli
```

**Comment by softprops** [comment]
Just tried the same test but with ECS exec on a container deployed to arm compute and got the same output. functionally these seems working to me

```
aws ecs execute-command \                                      
  // snip
  --interactive --command "/bin/sh -c 'hurl --version'"

The Session Manager plugin was installed successfully. Use the AWS CLI to start a session.


Starting session with SessionId: ecs-execute-command-09e686e91b91f4436
hurl: /lib64/libcurl.so.4: no version information available (required by hurl)
hurl 4.0.0 libcurl/8.0.1 OpenSSL/3.0.8 zlib/1.2.11 libidn2/2.3.2 nghttp2/1.55.1
Features (libcurl):  alt-svc AsynchDNS HSTS HTTP2 IDN IPv6 Largefile libz SPNEGO SSL UnixSockets
Features (built-in): brotli


Exiting session with sessionId: ecs-execute-command-09e686e91b91f4436.```

**Comment by lepapareil** [comment]
We've already seen `hurl: /lib64/libcurl.so.4: no version information available` using generic x64 binary on some linux distros. Hurl seems to be working well, but we clearly need to look further on this https://github.com/Orange-OpenSource/hurl/issues/1890.

**Comment by lepapareil** [comment]
Hi @softprops, https://github.com/Orange-OpenSource/hurl/releases/download/4.1.0/hurl-4.1.0-aarch64-unknown-linux-gnu.tar.gz is now officially available, we'll wait for your feedback to close this issue 😀.

**Comment by softprops** [comment]
Thanks I'll give this a api. And check back in

**Comment by softprops** [comment]
we're all good here @lepapareil !

I updated my ecs container docker file to download the lastest 4.1.0 prebuilt binaries 

```
FROM amazoncorretto:17-al2023
ARG TARGETPLATFORM

...

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
  dnf install -y tar gzip \
  && curl -sL https://github.com/Orange-OpenSource/hurl/releases/download/4.1.0/hurl-4.1.0-x86_64-unknown-linux-gnu.tar.gz \
  | tar xvz -C /tmp && echo "ccc8faf705f67aad5667eda1108c0a72 /tmp/hurl-4.1.0-x86_64-unknown-linux-gnu/hurl" \
  | md5sum -c \
  && mv /tmp/hurl-4.1.0-x86_64-unknown-linux-gnu /tmp/hurl; \
  fi

RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
  dnf install -y tar gzip \
  && curl -sL https://github.com/Orange-OpenSource/hurl/releases/download/4.1.0/hurl-4.1.0-aarch64-unknown-linux-gnu.tar.gz \
  | tar xvz -C /tmp && echo "fa56d8dee4aadeb4ee65338c558145ba /tmp/hurl-4.1.0-aarch64-unknown-linux-gnu/hurl" \
  | md5sum -c \
  && mv /tmp/hurl-4.1.0-aarch64-unknown-linux-gnu /tmp/hurl; \
  fi

ENV PATH="$PATH:/tmp/hurl"
```

and ECS exec'd in to a container deployed to an arm based dev deployment target and ran a basic set of checks. all looks well. thank you for this new addition.

```
bash-5.2# uname -m
aarch64

bash-5.2# hurl --version
hurl: /lib64/libcurl.so.4: no version information available (required by hurl)
hurl 4.1.0 (aarch64-amazon-linux-gnu) libcurl/8.2.1 OpenSSL/3.0.8 zlib/1.2.11 libidn2/2.3.2 nghttp2/1.55.1
Features (libcurl):  alt-svc AsynchDNS HSTS HTTP2 IDN IPv6 Largefile libz SPNEGO SSL UnixSockets
Features (built-in): brotli

bash-5.2# echo 'GET https://postman-echo.com/get' | hurl 
hurl: /lib64/libcurl.so.4: no version information available (required by hurl)
{
  "args": {},
  "headers": {
    "x-forwarded-proto": "https",
    "x-forwarded-port": "443",
    "host": "postman-echo.com",
    "x-amzn-trace-id": "Root=1-650fab01-4fbc382626b526ed2108a924",
    "accept": "*/*",
    "user-agent": "hurl/4.1.0"
  },
  "url": "https://postman-echo.com/get"
}
```
