### ISSUE TITLE
Using variables in MultipartFormData field names

### ISSUE THREAD

**Issue by janwytze** [Orange-OpenSource/hurl#1877]
### Problem to solve

Some of our endpoints do not have fixed form field names, but using variables in `MultipartFormData` is not possible.

### Proposal
Make it possible to use variables in `MultipartFormData` field names:

```
POST http://localhost/...
[MultipartFormData]
file_{{tag_name}}: file,image1.png;
HTTP 201
```

### Additional context and resources

For JSON files I do have a solution:
````
POST http://localhost/...
Content-Type: multipart/form-data; boundary="boundary"
```
--boundary
Content-Disposition: form-data; name="file_{{tag_name}}"; filename="test.json"
Content-Type: application/json

{"test": "test"}
--boundary
```
HTTP 201
````

**Comment by fabricereix** [comment]
Hi @janwytze ,
We could indeed support variable field name.
in this case,  we should also support it for all the other sections `[QueryParams]`, `[FormParams]`, `[BasicAuthen]`, `[Cookies]`

**Comment by janwytze** [comment]
@fabricereix That would be awesome!

**Comment by jcamiel** [comment]
hi @janwytze this issue is now merged on master.
You can now write:

```hurl
POST http://localhost/...
[MultipartFormData]
file_{{tag_name}}: file,image1.png;
HTTP 201
```

and runs:

```shell
$ hurl --test --variable tag_name=foo test.hurl
```

You can also use `[Options]` section:

```hurl
POST http://localhost/...
[Options]
variable: tag_name=foo
[MultipartFormData]
file_{{tag_name}}: file,image1.png;
HTTP 201
```
