### ISSUE TITLE
Ability to set working directory to start glob matching in 

### ISSUE THREAD

**Issue by serle** [Orange-OpenSource/hurl#1916]
### Problem to solve

Installed hurl with npm and want to run it as a script, so others get it automatically with an npm install in the project. Glob matching no longer works and I have no idea where its is applying the glob matching from. 

### Proposal

Add a new command line option to specify the root test directory, don't assume its the cwd or where the hurl executable is installed.

**Comment by jcamiel** [comment]
Hi @serle, can you give-us mored details about your workflow? For instance, how do you install install Hurl, what's your platform and what command with `--glob` do you test?

Usually, all references to files (including `--glob` pattern), are dependent on the current directory, whatever where is installed the `hurl` binary. This is to mimic usual tool like `grep` or `ls`. You can also use an absolute path with `--glob` (in case of a potential bug with Hurl)

**Comment by jcamiel** [comment]
@serle Do you have more details on this issue? If you can give use more details, feel free to reopen it, 
Regards,
