### ISSUE TITLE
Building hurl with modified build of curl (for example curl-impersonate)

### ISSUE THREAD

**Issue by Ghxst** [Orange-OpenSource/hurl#1938]
I suppose I'm asking both whether it's possible to build hurl including a modified version of (lib)curl and if so, what the build instructions / process would look like. I'm targeting [curl-impersonate](https://github.com/lwthiker/curl-impersonate) specifically, but I guess this would help others that maybe have a different use case in mind as well.

**Comment by lepapareil** [comment]
You only have to install your version of libcurl before building Hurl, following https://github.com/Orange-OpenSource/hurl#building-from-sources doc and replacing libcurl installation steps by yours :)

**Comment by lepapareil** [comment]
Hi @Ghxst, I'll wait for your feedback to close this issue 😄.

**Comment by Ghxst** [comment]
I haven't had time yet to try this, if you wish we can close the issue and if I run into issues I can reopen it. Apologies.
