### ISSUE TITLE
Regression in v4.1 not accepting --path_as_is

### ISSUE THREAD

**Issue by Thomasdezeeuw** [Orange-OpenSource/hurl#1960]
### What is the current *bug* behavior?

I think v4.1 broke the `--path_as_is` flag. We're getting the following error

```
error: error: unexpected argument '--path_as_is' found

  tip: a similar argument exists: '--path-as-is'

Usage: hurl --test --path-as-is [input_files]...
```

Maybe it's https://github.com/Orange-OpenSource/hurl/pull/1944?

### Steps to reproduce

Run `hurl --path_as_is $file.hurl`.

### What is the expected *correct* behavior?

Expects it to work line in v4.

### Execution context
hurl --test --path_as_is

- Hurl Version (`hurl --version`):
```
hurl 4.1.0 (x86_64-pc-linux-gnu) libcurl/8.3.0 OpenSSL/3.1.2 zlib/1.3 brotli/1.0.3840 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.56.0
Features (libcurl):  alt-svc AsynchDNS brotli HSTS HTTP2 IDN IPv6 Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
Features (built-in): brotli
```
- Operating system and version: Linux Thomas-Arch 6.5.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:40 +0000 x86_64 GNU/Linux

### Possible fixes

Revert to accepting `--path_as_is`.

**Comment by fabricereix** [comment]
Hi @Thomasdezeeuw,
yes it has been fixed to `--path-as-is `
The documentation https://hurl.dev/docs/manual.html#path-as-is was correct by there was a typo in the program.

**Comment by Thomasdezeeuw** [comment]
> Hi @Thomasdezeeuw, yes it has been fixed to `--path-as-is ` The documentation https://hurl.dev/docs/manual.html#path-as-is was correct by there was a typo in the program.

I think I was using the `--help` to determine useful arguments, hence I was use the "wrong" version. But this is a breaking change. It's not even called out in the release notes and broke our CI.

**Comment by fabricereix** [comment]
I have updated the release note.
