### ISSUE TITLE
adding integer comparison predicates to collection

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#199]
In order to guarantee the coherence of predicates, It would be helpful that hurl should allow to realize all integer comparison on collection:

- countEquals ✔
- countGreaterThan: ❌
- countGreaterThanOrEquals: ❌
- countlLessThan: ❌
- countLessThanOrEquals: ❌

**Comment by fabricereix** [comment]
Using the subquery `count` will enable to do that (#217)
