### ISSUE TITLE
print detailed console reporting

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#208]
`hurl version = 1.2.0`

### I write 4 test files, all 4 will succeed.

Currently I get:

```
$ hurl --output /dev/null /tmp/test*.hurl

```

What i expect using the new parameter (--console, --console-report, --summary, etc...)

```
$ hurl --output /dev/null --console /tmp/test*.hurl
/tmp/test1.hurl: success
/tmp/test2.hurl: success
/tmp/test3.hurl: success
/tmp/test4.hurl: success
------------------------------------------------------
executed: 4
success: 4 (100%)
failed: 0 (0%)
execution time: 1s
```

### I write 4 test files, 3 will succeed, 1 will fail.

Currently I get:

```
$ hurl --output /dev/null /tmp/test*.hurl
error: Assert Status
  --> /tmp/test2.hurl:2:10
   |
 2 | HTTP/1.1 302
   |          ^^^ actual value is <301>
   |
```

what i expect using the new parameter (--console, --console-report, --summary, etc...)

```
$ hurl --output /dev/null --console /tmp/test*.hurl
/tmp/test1.hurl: success
/tmp/test2.hurl: failed
error: Assert Status
  --> /tmp/test2.hurl:2:10
   |
 2 | HTTP/1.1 302
   |          ^^^ actual value is <301>
   |
/tmp/test3.hurl: success
/tmp/test4.hurl: success
------------------------------------------------------
executed: 4
success: 3 (75%)
failed: 1 (25%)
execution time: 1s
```

**Comment by fabricereix** [comment]
what about `--test-summary` ?

**Comment by lepapareil** [comment]
Without parameters, hurl will only print errors on console. 

Printing more informations makes console output looks like a real report (as json or html).

I think that --console-report is more accurate. All other reports parameters should then be renamed with -report extension, like --json-report and --html-report.

**Comment by fabricereix** [comment]
The 3 options would be similar. 
with --console-report, we could either specify an optional output filename, or none at all
```
--console-report [TEXT_FILE]
--json-report JSON_FILE
--html-report HTML_FILE
```

we could also prefix by report- instead
```
--report-console [TEXT_FILE]
--report-json JSON_FILE
--report-html HTML_FILE
```

**Comment by lepapareil** [comment]
i prefer

```
--console-report [TEXT_FILE]
--json-report JSON_FILE
--html-report HTML_FILE
```

**Comment by fabricereix** [comment]
This console output is especially useful during manual run.
`--progress` could be used for that.

**Comment by lepapareil** [comment]
--progress looks more like a progressive bar printing live progression of the number of tests for example:

```
=====6/14=========>
```
```
======7/14========>
```
```
============13/14=>
```

**Comment by lepapareil** [comment]
@jcamiel @fabricereix what do you think if:

- printing success and fail become the standard stderr output (without any parameter)
- `--errors` as a dedicated parameter printing only fails (actual standard output behaviour)
- `--summary` as a dedicated parameter printing total, success, failed and total-time metrics
- `--duration` as a dedicated parameter printing total time spent by hurl file
- `--progress` as a dedicated parameter printing a live progression bar of the number of tests executed
- `--verbose` as a dedicated parameter printing complete stacks like a full debug mode (for success and errors)

So we can decide to display the metrics or not, the success or not, the duration or not etc... the real big change is that by default, the standard stderr output will not only display errors but also successes.

**Comment by fabricereix** [comment]
Relating to the behaviour by default, 
Hurl can print to the standard error the line  `FILENAME: Running` when the test is being run.
At the end of the test, the line will be updated to  `FILENAME: Success | Failure (duration)`.

Therefore the options `--duration` and `--progress` are "turned on" by default and are not necessary.

If we want to be less verbose and display only the tests in error, we could add the option ``--hide-success`.

**Comment by lepapareil** [comment]
i've created `--summary` issue at https://github.com/Orange-OpenSource/hurl/issues/232

**Comment by lepapareil** [comment]
i've created --progress issue at https://github.com/Orange-OpenSource/hurl/issues/236
