### ISSUE TITLE
Use one Assert for multiples Requests

### ISSUE THREAD

**Issue by thasos** [Orange-OpenSource/hurl#2090]
### Problem to solve

Same assert for multiples Requests

### Proposal
Hello, I didn't found a way to do an Assert for multiples tests, shomethink like this :
```
{
    GET https://server01:443/api/v1/healthcheck
    GET https://server02:443/api/v1/healthcheck
    GET https://server03:443/api/v1/healthcheck
}
HTTP 200
[Asserts]
jsonpath "$.status" == "ok"
```

### Additional context and resources
I was looking for that for testing all my servers behind a virtual IP : they must all have the same response.
I can chain the 3 tests, but I have to repeat the `[Assert]` for each (who can be more complicated than the example)

**Comment by jcamiel** [comment]
Hi @thasos 

Thanks for the issue

The file format doesn't support this kind of feature. We've chosen it to be simple and explicit, to the detriment of repeating things. We may close this issue in the few days, and sorry for this!

**Comment by lepapareil** [comment]
Another way to achieve this with sh:

- Create a `url.list` file containing your urls, for example:

```
{
echo https://hurl.dev
echo https://hurl.dev/docs/manual.html
echo https://hurl.dev/blog
} > url.list
```

- Create your `uniq-test.hurl` file to test your generic asserts with variabilized url, for example:

```
{
echo "GET {{url}}"
echo "HTTP 200"
echo "[Asserts]"
echo "xpath \"string(/html/head/title)\" contains \"Hurl\""
} > uniq-test.hurl
```

- Loop over `url.list` and inject url variable to execute your `uniq-test.hurl` over your urls, for example:

```
while read -r url ; do
    echo -n "######### testing ${url} \n"
    hurl --variable url="${url}" \
         --test \
         --location \
         uniq-test.hurl
done < url.list
```

- Results on:

![image](https://github.com/Orange-OpenSource/hurl/assets/15672496/f209dba2-c018-4fc8-b487-f097c5566785)

We can see that `https://hurl.dev/docs/manual.html` does not contain Hurl in his title :).

**Comment by jcamiel** [comment]
Hi @thasos I'm closing this issue as "Won't fix", don't hesitate to create new issue/enhancement for Hurl!
