### ISSUE TITLE
[Question] json and output

### ISSUE THREAD

**Issue by iBicha** [Orange-OpenSource/hurl#2104]
### Problem to solve
Is there a way to get both the json run (`--json` flag) and the raw output into separate files?
I do want the whole body of the response in a file, and I want the hurl run with the variable captures in a different file.

I know it's possible to capture the body in a variable, and that will end up in the `--json` file, but it will be escaped and included as a string, which is not at all nice to work with.

I really prefer to have both things separate if possible.

Right now I'm forced to make to calls, one with `--json` flag and one without, which is not great

**Comment by jcamiel** [comment]
Hi @iBicha 
Would it be ok it you get the raw response in the JSON output?
This way:

```shell
$ hurl --json foo.hurl
```

will output a JSON file with actual values (captures, headers, etc...) plus raw HTTP response.

**Comment by iBicha** [comment]
> Hi @iBicha Would it be ok it you get the raw response in the JSON output? This way:
> 
> ```shell
> $ hurl --json foo.hurl
> ```
> 
> will output a JSON file with actual values (captures, headers, etc...) plus raw HTTP response.

If the raw HTTP response is also json, then the output is basically encoded as a string in a single line, which is not easy to inspect.

**Comment by jcamiel** [comment]
We could add the raw response depending on the content-type of the reponse, for instance:

If the "Content-Type" is "JSON" like, we can use the response body "as it":

```json
"response": {
  "type": "json"
  "body": {
     "success": true,
     "date":"2020-11-23"
   }
}
...
```
otherwise, if the body is text, we can encode the body in a JSON string

```json
"response": {
  "type": "text"
  "body": "a text body \"hello\""
}
...
```

otherwise (binary) content, we could use Base64 encoding


```json
"response": {
  "type": "binary"
  "body": "bGlnaHQgd29yay"
}
...
```

I'm thinking on this possibility because there are other people asking for response with --json option (see #1907 and #1969)

**Comment by iBicha** [comment]
Thanks! Let's close this issue, I'll add my input in the discussion

**Comment by iBicha** [comment]
Linking my thoughts on this here https://github.com/Orange-OpenSource/hurl/discussions/1969#discussioncomment-7418291
