### ISSUE TITLE
Invalid json when composing a POST json payload

### ISSUE THREAD

**Issue by iBicha** [Orange-OpenSource/hurl#2106]
### What is the current *bug* behavior?

Error of including a json object into another one.

### Steps to reproduce

Have a .env file, something like:
MY_SUB_JSON={"key1":"value1"}

then use hurl
POST url
{"my_payload": {{MY_SUB_JSON}}}

This would fail error: Invalid JSON (and shows actual value is (and prints MY_SUB_JSON which is a valid json))

### What is the expected *correct* behavior?

I expect the request to work, since the payload consists of a valid json

### Execution context

- Hurl Version (`hurl --version`):
hurl 4.1.0 (x86_64-apple-darwin21.0) libcurl/8.1.2 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1
Features (libcurl):  alt-svc AsynchDNS HSTS HTTP2 IPv6 Largefile libz NTLM NTLM_WB SPNEGO SSL UnixSockets
Features (built-in): brotli
- Operating system and version: MacOS

**Comment by jcamiel** [comment]
Hi @iBicha 

I think we're escaping the variable when we're rendering the JSON body. We can't know or make an assumption about wether you want to use a string or a JSON object. For this use case, you can use multiline string with a `json` identifier:


~~~
POST https://foo.com
```json
{
  "state":{{MY_VAR}}
}
```
HTTP 200
~~~

I've not tested it but it should be ok (if you can confirm it).

**Comment by iBicha** [comment]
That's fantastic, thank you!

**Comment by jcamiel** [comment]
I've not tested it, I hope it's OK 😅!

**Comment by iBicha** [comment]
> I've not tested it, I hope it's OK 😅!

Yes it works as intended!
