### ISSUE TITLE
improve error messages when syntax is not recognized

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#213]
`hurl version: 1.2.0`

what i get:

```
error: Parsing section name
  --> test.hurl:3:2
   |
 3 | [asserts]
   |  ^ the section asserts is not valid
   |
```

what i expect:

```
error: Parsing section name
  --> test.hurl:3:2
   |
 3 | [asserts]
   |  ^ the section asserts is not valid, did you mean --> [Asserts] ?
   |
```

I think that at first, when an unknown syntax is found, it is enough to compare it in [[lower]] mode to the list of known syntaxes at the expected position and then propose the correction (this can also happen on countEquals etc...)

**Comment by fabricereix** [comment]
We decided to accept only section with the first uppercase letter so that hurl files look more similar/uniform.
But yes, in this case, we can indeed be more helpful in the error message

**Comment by fabricereix** [comment]
We can also make suggestion for HTTP methods.
for example:

```
error: Parsing Method
  --> tests_error_parser/method.hurl:1:1
   |
 1 | GeT http://localhost:8000/hello
   | ^ The HTTP method is not valid. Did you mean GET?
```
