### ISSUE TITLE
Error deserializing large u64 values in responses

### ISSUE THREAD

**Issue by mihirn** [Orange-OpenSource/hurl#2132]
Hurl (4.0.0) panics while deserializing large `u64` values in the response body.

```
< HTTP/1.1 200 OK
< content-type: application/json
.....
<
* Response body:
* [{"max":18446744073709551615},{"max":4294967296}]
*
....
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value' (hurl-4.0.0/src/runner/query.rs:359:47)
```

If one changes the response so the first value is in `i64` range, it runs fine.

This seems to be caused by the fact that `from_json` attempts to deserialize serde numbers into `f64`s or `i64`s, but not `u64`s.
(https://github.com/Orange-OpenSource/hurl/blob/master/packages/hurl/src/runner/query.rs#L359)

**Comment by fabricereix** [comment]
Thanks @mihirn for your detail description.
We will remove the unwrap/panic and deal with the out of range explicitly.
We could also add support for BigInteger.

**Comment by mihirn** [comment]
Thanks! Is it worth just adding one more `if..else` case to the ladder with `is_u64` in case the `i64` check fails?

Obviously this doesn't fix the issue completely since input can be arbitrarily large so explicitly handling out of range values needs to happen anyway, but that much support for large values would be sufficient for my use case, even without full BigInteger support.

**Comment by fabricereix** [comment]
Hi @mihirn,
We have now introduced a new BigInteger variant that solves this bug.
You can have a look at this [test](https://github.com/Orange-OpenSource/hurl/blob/master/integration/hurl/tests_ok/predicates_number.hurl)
