### ISSUE TITLE
Support simple response transformations

### ISSUE THREAD

**Issue by gmetal** [Orange-OpenSource/hurl#2134]
### Problem to solve

For testing AWS Lambdas, there are Docker images provided, which produce responses  that embed your Lambda response (which may be a JSON document) as a string in the base Lambda JSON response. Currently, the only way to work with this kind of response to use Regex, which would make it impractical for large JSON responses. It would be nice if there was a way to extract the specific string and treat it as a JSON.

### Proposal

There is a need to perform some type of string transformation in the responses, and potentially change their content type. 

### Additional context and resources

This idea mostly applies to AWS Lambdas, but it could also apply in other scenarios where a response may be embedded in a larger resource. 
The Official AWS Lambda images can be found [here](https://gallery.ecr.aws/lambda?page=1)

**Comment by fabricereix** [comment]
Ho @gmetal,
We also have a simlar need. We plan to add `jsonpath` as filter (like `xpath`)
Hopefully for the next release.

**Comment by fabricereix** [comment]
Here an example mixing XML/JSON
```
<data>
{"message": "Hello"}
</data>
```
Processed with `xpath` query/`jsonpath` filter
```
xpath "//data/text()" jsonpath "$.message" == "Hello"
```
What about your response?
Can you provide an example?
Thanks

**Comment by jcamiel** [comment]
See #440

**Comment by gmetal** [comment]
> What about your response? Can you provide an example? Thanks

For example,  this may be a Lambda response:

```
{
  "statusCode": 200,
  "body": "[{\"id\":\"ecce3ef4-7469-4d1a-bb6c-151fb93a7d31\",\"key\":\"sample-key\",\"value\":\"sample-value\"}]",
  "isBase64Encoded": false,
  "multiValueHeaders": {
    "Content-Type": [
      "application/json"
    ]
  }
}
```

The contents of the `body` attribute may be (in this case) extracted and converted into an actual JSON response.

**Comment by fabricereix** [comment]
ok thanks

**Comment by jcamiel** [comment]
Hi @gmetal, the `jsonpath` filter has been merged on master. If you know how to build Hurl on master, you can test it and provide us remarks/improvments!

**Comment by gmetal** [comment]
@jcamiel I can verify that the `jsonpath` filter works great for my case. Thank you for your prompt resolution of this issue!
