### ISSUE TITLE
arch doc  for build from source

### ISSUE THREAD

**Issue by thasos** [Orange-OpenSource/hurl#2138]
### What is the current *bug* behavior?
Hello, I just wanted to point a minor problem in the doc https://hurl.dev/docs/installation.html#arch-based-distributions :
`pacman -Sy --noconfirm pkgconf gcc glibc openssl libxml2`

With arch, you should never do `pacman -Sy <package>`  : refreshing the database (`-y`) without upgrade all the system (`-u`) can break a dependency, see [arch wiki](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported) for more details.

### Steps to reproduce
N/A

### What is the expected *correct* behavior?
It should be `pacman -S --noconfirm pkgconf gcc glibc openssl libxml2`
(just remove `-y`)

### Execution context
N/A

### Possible fixes
N/A

**Comment by lepapareil** [comment]
You're absolutely right @thasos 👍🏻.
