### ISSUE TITLE
Add curl -H/--header option to add a request header one each request

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#2144]
Add support for curl -H/--header option to add a request header on each request:

```shell
$ hurl --header "foo: bar" test.hurl
```

Adding multiple header is possible:

```shell
$ hurl --header "foo: bar" --header "bar: baz" test.hurl
```

To define: while redundant with header, per request header option should be also possible ?

```hurl
GET https://foo.com
[Options]
header: "foo: bar"
HTTP 200
```

**Comment by jcamiel** [comment]
@theoforger if you're interesting by this issue, you're good to go!

This option is a curl option and it makes sense to be exposed by Hurl.

For a start, we could implement in a first PR this option:

```shell
$ hurl --header "foo: bar" test.hurl
```

Multiple headers could be added 

```shell
$ hurl --header "foo: bar" --header "baz:bar" test.hurl
```

That will a a request header `foo:bar` to every request of a Hurl file.


It will make also sense to implement it on `[Options]`section (in another PRs of course):

```hurl
GET https://foo.com
[Options]
header: toto:tutu
HTTP 200
```

This can be redundant with our header syntax 

```hurl
GET https://foo.com
toto: tutu
HTTP 200
```

But in the future we plan to implement `[Options]` section at the start of a Hurl file that will be apply to every entry of a file. For instance:

```hurl
[Options]
insecure: true
header: token:xxx

GET https://foo.com

GET https://bar.com

GET https://baz.com
```

Will add a header on every request of the Hurl file

**Comment by theoforger** [comment]
@jcamiel I noticed that the curl option also supports input through a file:

```bash
curl -H @filename https://example.com
```

or through stdin:

```bash
curl -H @- https://example.com
```

Do we want to implement them as well?

**Comment by jcamiel** [comment]
For the moment, it doesn't seem necessary. We can implement it later if someone has a strong need of it!

**Comment by theoforger** [comment]
@jcamiel Hello again! I just submitted a PR for this. Any feedback is appreciated 🙏

**Comment by theoforger** [comment]
> It will make also sense to implement it on `[Options]`section (in another PRs of course):
> 
> ```
> GET https://foo.com
> [Options]
> header: toto:tutu
> HTTP 200
> ```
> 
> This can be redundant with our header syntax
> 
> ```
> GET https://foo.com
> toto: tutu
> HTTP 200
> ```
> 
> But in the future we plan to implement `[Options]` section at the start of a Hurl file that will be apply to every entry of a file. For instance:
> 
> ```
> [Options]
> insecure: true
> header: token:xxx
> 
> GET https://foo.com
> 
> GET https://bar.com
> 
> GET https://baz.com
> ```
> 
> Will add a header on every request of the Hurl file

@jcamiel Hello again! I'll work on this next. Just want to confirm that it's still relevant before I start 😄

**Comment by jcamiel** [comment]
Yes it's still OK, I will make an issue for it. This one _should_ be simpler, as the hard work is done is the `--header` PR. Don't hesitate to ping if you have any question

**Comment by theoforger** [comment]
@jcamiel Happy (belated) new year! Just in case you forgot, did you create the issue? 😆

**Comment by jcamiel** [comment]
Hi @theoforger I've forgotten! I'll make it asap

**Comment by jcamiel** [comment]
@theoforger can you add a quick comment on issue #3575 (it's the only way I will be able to assign it to you...)
