### ISSUE TITLE
Extract from response body with jsonpath does not yield result

### ISSUE THREAD

**Issue by janstrohschein** [Orange-OpenSource/hurl#2183]
We receive a json body that we want to check for a specific value in a field via a condition in the jsonpath and then return another field from that entry.

JSON Body: 
```
{
"content":[
{"id":28,
"type":"Feature",
"geometry":{"type":"Polygon","coordinates":[[[10.386228119568509,50.26892221483541],[11.153042016206681,50.006680680863724],[11.868734986402304,50.399504242118724],[10.386228119568509,50.26892221483541]]]},
"properties": {"id":28,
"creator":"tester2",
"creationDate":"2023-11-23T15:18:09.799242+01:00",
"lastModificationDate":"2023-11-23T15:18:09.799242+01:00",
"beschreibung":"AOI #5"}},
{"id":24,
"type":"Feature",
"geometry":{"type":"Polygon","coordinates":[[[9.673886487281651,48.90751103851957],[10.163980586437354,48.40368289347154],[11.25307858456113,48.692201213390575],[10.70852958549924,49.2287440309735],[9.673886487281651,48.90751103851957]]]},
"properties": {"id":24,
"creator":"tester2",
"creationDate":"2023-11-23T15:03:38.08764+01:00",
"lastModificationDate":"2023-11-23T15:03:38.08764+01:00",
"beschreibung":"AOI #2"}}
]
}
```

JSONPath (validated on jsonpath.com)
`$.content..[?(@.beschreibung == 'AOI #5')].id`
or
`$.content.[?(@.beschreibung == 'AOI #5')].id`

### What is the current *bug* behavior?
Hurl returns an empty list.

### Steps to reproduce
- create a request that returns the attached response body
- create a [Captures] block with a variable and the attached jsonpath
- check the content of the variable

### What is the expected *correct* behavior?
according to jsonpath.com the result should look like this:
```
[
  28
]
```
### Execution context
Ubuntu with Hurl Version 4.1.0

 
I am not sure if this is a bug or if I am unaware of the correct way to capture the value. Either way, your help is greatly appreciated! 

Best regards,
Jan

**Comment by fabricereix** [comment]
Hi @janstrohschein,

Thanks for your issue.

For the first expression `$.content..[?(@.beschreibung == 'AOI #5')].id`,
There is indeed a bug, we should support filter with `..` operator (all elements).

But for the second one `$.content.[?(@.beschreibung == 'AOI #5')].id`, I don't really understand why it should return something.
The current element do not have a `beschreibung` field. We can deal with this one in another issue.
And focus on the new jsonpath spec https://www.ietf.org/archive/id/draft-goessner-dispatch-jsonpath-00.html

Relating to the other tools
```
$.content.[?(@.beschreibung == 'AOI #5')].id
http://jsonpath.com/                                    => match
https://jsonpath.curiousconcept.com/                    => match
https://www.site24x7.com/tools/json-path-evaluator.html => not match

$.content[?(@.beschreibung == 'AOI #5')].id
http://jsonpath.com/                                    => not match
https://jsonpath.curiousconcept.com/                    => match
https://www.site24x7.com/tools/json-path-evaluator.html => not match

```

**Comment by janstrohschein** [comment]
Dear @fabricereix,

I could fix the second Option by now, the correct way to retrieve the data is via:
`$.content[?(@.properties.beschreibung == 'AOI #5')].id`

It would still be nice to implement the Option1 with the `..`. Should i close this issue and create another one for this?

Thank you for your help!
Best regards,
Jan

**Comment by fabricereix** [comment]
I have created a specific issue #2195 to clarify the Option2 
and added it in our integration tests
https://github.com/Orange-OpenSource/hurl/blob/master/integration/tests_ok/assert_json.hurl#L112

We can keep this issue to add support for `..` (Option1)

**Comment by fabricereix** [comment]
Hi @janstrohschein,
I'm coming back to you relating to your jsonpath expressions.
I don't think `$.content..` and `$.content.` expressions are valid. They are not included in the spec https://www.ietf.org/archive/id/draft-goessner-dispatch-jsonpath-00.html (still a draft)

You should probably write `$.content[?(@.beschreibung == 'AOI #5')].id` instead.
Let me know if it works for you.

I have also added the following example in our integration test suite.
It illustrates what is currently supported

```
jsonpath "$..*[?(@.name)]" count == 5
jsonpath "$..*[?(@.name=='car')].id" nth 0 == 1
jsonpath "$..*[?(@.name=='wheel')].id" nth 0 == 4

jsonpath "$..items[?(@.name)]" count == 5
jsonpath "$..items[?(@.name=='car')].id" nth 0 == 1
jsonpath "$..items[?(@.name=='wheel')].id" nth 0 == 4

jsonpath "$.main.items[?(@.name)]" count == 3
jsonpath "$.main.items[?(@.name=='car')].id" nth 0 == 1
jsonpath "$.main.items[?(@.name=='wheel')].id" isEmpty

jsonpath "$.main..items[?(@.name)]" count == 4
jsonpath "$.main..items[?(@.name=='car')].id" nth 0 == 1
jsonpath "$.main..items[?(@.name=='wheel')].id" nth 0 == 4

{
  "main": {
    "items": [
      {
        "id": 1,
        "name": "car"
      },
      {
        "id": 2,
        "name": "bike",
        "items": [
          {
            "id": 4,
            "name": "wheel"
          }
        ]
      },
      {
        "id": 3,
        "name": "plane"
      }
    ]
  },
  "more": {
    "items": [
      {
        "id": 5,
        "name": "scooter"
      }
    ]
  }
}
```

**Comment by jcamiel** [comment]
Hi @janstrohschein we're closing this issue now, feel free to reopen it if needed.
