### ISSUE TITLE
starting zero is filtered out when passing variable with numeric value by string type

### ISSUE THREAD

**Issue by redsnapper2006** [Orange-OpenSource/hurl#2193]
### What is the current *bug* behavior?

when passing variable with numeric value by string type, starting zero is filtered out

### Steps to reproduce

hurl --variable parameter="0123456" sample.hurl

during execution, parameter gets 123456 value

for case `hurl --variable parameter=0123456 sample.hurl`, it is ok for value 123456

### What is the expected *correct* behavior?

parameter variable should have "0123456"

### Execution context

- Hurl Version (`hurl --version`):
4.1.0

**Comment by redsnapper2006** [comment]
it works well

`hurl --variable parameter=\"0123456\" sample.hurl`

if no further comment, please ignore this issue

**Comment by jcamiel** [comment]
Related to #1314 

Thanks for the issue, I don't remember what we have to do, it's worth checking again
