### ISSUE TITLE
Hurl don't like Authentication Challenge

### ISSUE THREAD

**Issue by gaojx** [Orange-OpenSource/hurl#2211]
<b> What is the current *bug* behavior? </b>

Hurl reports error:
  Failure when receiving data from the peer
for response:

 HTTP/1.1 401 Unauthorized
 WWW-Authenticate: Basic realm="myapp"

<b>Steps to reproduce</b>

<ol>
  <li>Send an request to server that requires authentication </li>
  <li>The server response with a auth challenge, like the one above</li>
</ol>

<b> What is the expected *correct* behavior? </b>
  Hurl should just show the response, and supports assert like:
 `HTTP 401`

 Hurl returns error: 
  `Failure when receiving data from the peer`

<b> Execution context </b>
- Hurl Version: hurl 4.1.0 (Windows) libcurl/8.0.1-DEV Schannel zlib/1.2.13

**Comment by fabricereix** [comment]
Hi @gaojx,
Could you send your output in verbose mode (`--verbose)?
Could you also send the output of curl (also in verbose mode)?
Thanks
