### ISSUE TITLE
Make dark mode for the HTML report

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#2254]
Current HTML report is light mode only, it would be cool to display a light/dark report based on current user's preferences.

**Comment by dorryspears** [comment]
I want to tackle this!

**Comment by jcamiel** [comment]
Hi @dorryspears no problem, you can work on it! The only thing that will maybe be difficult is the SVG requests timeline.

**Comment by dorryspears** [comment]
@jcamiel made a rough draft PR

**Comment by jcamiel** [comment]
@dorryspears yes thanks a lot, I'll look at it as soon as I come back from vacation
