### ISSUE TITLE
Support "-" as output to sdtout for --output option

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#2312]
Support "-" as output to sdtout for --output option

**Comment by asggWa** [comment]
integración.
rust más que curl o hurl.

**Comment by jcamiel** [comment]
See curl code =>

https://github.com/curl/curl/blob/72bd88adde0e8cf6e63644a7d6df1da01a399db4/src/tool_cb_wrt.c#L209
