### ISSUE TITLE
4.2.2 release did not get completed?

### ISSUE THREAD

**Issue by chenrui333** [Orange-OpenSource/hurl#2316]
👋 it looks like 4.2.2 release did not get completed? ie the release did not get marked as latest release. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/159538

**Comment by jcamiel** [comment]
Hi @chenrui333 we've made a mistake yesterday preparing the new release.
The new release (is draft now, will be official in a few minutes) is _4.2.0_ . The branch 4.2.2 as the tag 4.2.2 have been deleted
Thanks !!

**Comment by chenrui333** [comment]
I see, that actually makes total sense, I was wondering why it was 4.2.2 yesterday too LOL
