### ISSUE TITLE
A pre-built binary for linux/arm64 is missing at 4.2.0

### ISSUE THREAD

**Issue by suzuki-shunsuke** [Orange-OpenSource/hurl#2318]
A pre-built binary for linux/arm64 is missing at 4.2.0.

<img width="467" alt="image" src="https://github.com/Orange-OpenSource/hurl/assets/13323303/0be0cbee-401f-465b-ad54-9a7c07369eb6">

At 4.1.0, the pre-built binary for linux/arm64 exists.

<img width="461" alt="image" src="https://github.com/Orange-OpenSource/hurl/assets/13323303/dd6b23fe-afb4-4c76-9aef-5389da75bdc4">

**Comment by jcamiel** [comment]
Hi @suzuki-shunsuke yes we've to delivered this artifact for the 4.2.0. Normally, it should be done in a few hours

**Comment by suzuki-shunsuke** [comment]
Oh, I see. Thank you.
I'm sorry I forgot I asked the similar thing before. 🙇‍♂️

- https://github.com/Orange-OpenSource/hurl/issues/1590#issuecomment-1573140063

**Comment by lepapareil** [comment]
Hi @suzuki-shunsuke, here it is https://github.com/Orange-OpenSource/hurl/releases/download/4.2.0/hurl-4.2.0-aarch64-unknown-linux-gnu.tar.gz 😄.

**Comment by suzuki-shunsuke** [comment]
Thank you!
