### ISSUE TITLE
add --progress option to print progressive status and executed count

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#236]
`hurl version = 1.2.0`

### I write 4 test files, 3 will succeed, 1 will fail.

Currently I get:

```
$ hurl test*.hurl
error: Assert Status
  --> /dir1/dir2/dir3/file3.hurl:7:10
   |
 7 | HTTP/1.1 200
   |          ^^^ actual value is <500>
   |
```

What i expect using the new parameter `--progress`

```
$ hurl --progress test*.hurl
/dir1/dir2/dir3/file1.hurl: success         
/dir1/dir2/dir3/file2.hurl: success         
/dir1/dir2/dir3/file3.hurl: failure          
error: Assert Status
  --> /dir1/dir2/dir3/file3.hurl:7:10
   |
 7 | HTTP/1.1 200
   |          ^^^ actual value is <500>
   |
/dir1/dir2/dir3/file4.hurl: success
```

Which could give on screen:

![--progress](https://user-images.githubusercontent.com/15672496/124939904-cd61d380-e009-11eb-955b-2c45fbdb5a0f.gif)

**Comment by fabricereix** [comment]
For the next version, we can start by simply adding these 2 lines:
- <FILENAME>: running before running the test
- <FILENAME>: <STATUS> after runing the test

Replacing 'running' by the test status may not be possible if errors are printed.
We also need to clarify the behavior in verbose mode.

**Comment by fabricereix** [comment]
We can't really replace `running` by `success`|` failure`.
The cursor is rather moved with a terminal instruction such as tput.
In this case, the ouput would not be greppable anymore.
