### ISSUE TITLE
output individual responses

### ISSUE THREAD

**Issue by SubeeshNair** [Orange-OpenSource/hurl#2368]
Suppose I have 4 to 5 responses and I want to get output of each individual response in either .txt format or .json format. What can we do here. The -- output only outputs the last response

**Comment by jcamiel** [comment]
Hi @SubeeshNair , 

You can use an [[Options] section](https://hurl.dev/docs/request.html#options) to override options for each request. By instance, we can use it to save each response in a custom file:


```hurl
GET https://foo.com
[Options]
output: foo.bin
HTTP 200

GET https://bar.com
[Options]
output: bar.bin
HTTP 200

GET https://baz.com
[Options]
output: baz.bin
HTTP 200
```

**Comment by jcamiel** [comment]
Hi @SubeeshNair 
I'm closing this one, as I think the current version of Hurl is supporting your use case. Fill-free to reopen it if it's not the case or if you need more information!

**Comment by SubeeshNair** [comment]
Hi @jcamiel 
Im not able to use 
GET https://foo.com 
[Options] 
output: foo.bin 
HTTP 200
Because the terminal is giving an error, the http method output is not valid. 

Can you please provide a workaround
I tried generating a report using --report-html, but it doesnt provide all the reports I need

**Comment by jcamiel** [comment]
Hi @SubeeshNair can you provide-me the output if `hurl --version`? 
The `--output` version has been introduced in the last Hurl release (4.2.0).

**Comment by SubeeshNair** [comment]
Im using hurl release 4.1.0. That might be the reason for this issue. Thanks for the response @jcamiel
