### ISSUE TITLE
Support global header for setting?

### ISSUE THREAD

**Issue by baerwang** [Orange-OpenSource/hurl#2487]
### Problem to solve

test OpenAPI need token info , integration for login, need global header setup

### Tasks to complete

- [ ] ...

**Comment by jcamiel** [comment]
Hi @baerwang 

Is this issue the same as https://github.com/Orange-OpenSource/hurl/issues/2144 ?

In 2144, the proposal is to implement curl option `-H/--header` (on the command line and per request):


```shell
$ hurl --header "X-MyHeader: 123" test.hurl
```

will add the header `X-MyHeader` to all requests in `test.hurl`


And also header in `[Options]` section is supported (while redundant with Hurl headers):

```hurl
GET https://foo.com
[Options]
header: X-MyHeader: 123

GET https://bar.com
```

is identical to 

```hurl
GET https://foo.com
X-MyHeader: 123

GET https://bar.com
```


If it's the same issue, we can ark this one as duplicate of #2144

**Comment by baerwang** [comment]
thanks
