### ISSUE TITLE
Alternative file format (yaml)

### ISSUE THREAD

**Issue by terev** [Orange-OpenSource/hurl#2603]
### Problem to solve
The current flat file format can become hard to read when the number of entries grows much. It's can become hard to distinguish between entries, where they end, begin, etc.

### Proposal
I propose the tool accept entries encoded in an alternative file format such as yaml. A yaml version of the data model would be much more readable as it would be easy to distinguish between entries in an array.

### Additional context and resources
I considered creating a pre processor to generate the hurl file format from yaml. However I figured it'd be better to have support within the tool itself if possible. 

### Tasks to complete
Looking at the code briefly it seems like the data processing would need to be separated from the runner module. And make the runner module instead accept the pre loaded data as a model to execute. This way the loading can be separated from the actual execution.

A yaml based loader would need to be added.

The data loading code within the cli would need to be changed to use the correct loader based on file extension or some other mechanism.

**Comment by jcamiel** [comment]
Hi @terev 

Thanks for the issue. There is very few chance that we address it, as we've specially designed the format to be what it is today. We've (long ago) gone through a JSON then Yaml format, to then settle on our own. There are obvious downsides to it (IDE support, syntax coloring, adoption etc...), but, in our mind, the benefits are greater than the loss.

That said, you can of course make your own repo/tool that converts Yaml to Hurl, it could be great! There are also great alternatives in this space (https://github.com/stepci/stepci for instance) that're Yaml based and could be more suitable.

**Comment by terev** [comment]
@jcamiel That's true I think IDE support and syntax coloring, etc would help a lot. Understood, I appreciate the reply!
