### ISSUE TITLE
Assert against a response file

### ISSUE THREAD

**Issue by joesantos418** [Orange-OpenSource/hurl#2627]
### Problem to solve

Offering a flexible way to assert a response content regardless of format.

### Proposal

The idea is to use the same syntax that allows to load requests from files, to allow asserts against expected responses using files as well. 

### Additional context and resources

I have a few API tests using JSON input and output. I use the jsonpath assert, which works great, but I'd like my tests to break if someone adds a new field to the response and doesn't test it. This could also help people who use other output formats that don't have support and offers another layer of completeness for the tests.

### Tasks to complete

- [ ] Add support to assert against a file
- [ ] Update docs

**Comment by fabricereix** [comment]
Hi @joesantos418 ,
could you give us a few examples to make it more concrete?
thanks

**Comment by jcamiel** [comment]
Just for info @joesantos418 you can do this with Hurl current version:

- [implicit assert body](https://hurl.dev/docs/asserting-response.html#body):

```hurl
GET https://example.org/api/cats/123
HTTP 200
{
  "name" : "Purrsloud",
  "species" : "Cat",
  "favFoods" : ["wet food", "dry food", "<strong>any</strong> food"],
  "birthYear" : 2016,
  "photo" : "https://learnwebcode.github.io/json-example/images/cat-2.jpg"
}
```

- [explicit assert body with file](https://hurl.dev/docs/asserting-response.html#body-assert):

```hurl
GET https://example.org/index.html
HTTP 200
[Asserts]
body == file,cat.json;
```

**Comment by joesantos418** [comment]
That's exactly what I was looking for. Thank you!

**Comment by jcamiel** [comment]
@joesantos418 minor typo, should be `bytes`:

```hurl
GET https://example.org/index.html
HTTP 200
[Asserts]
bytes == file,cat.json;
```
