### ISSUE TITLE
Add units for duration value

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#2653]
Duration value is Hurl format are sometimes milliseconds, (`--delay`) or seconds (`--max-time`). It would increase the readibility of Hurl format if we could optionally specify a time unit:

Without time unit:

```hurl
GET https://foo.com
[Options]
delay: 2000
max-time: 60
HTTP 200

POST https://foo.com
[Options]
retry-interval: 100
HTTP 200
[Asserts]
duration < 1000
```

With time unit:

```
GET https://foo.com
[Options]
delay: 2s
max-time: 60s
HTTP 200

POST https://foo.com
[Options]
retry-interval: 100ms
HTTP 200
[Asserts]
duration < 1s
```

Question: do we want to support this with command line values ?

**Comment by Jiehong** [comment]
I would like to re-open this issue, because the PR #3129 only implemented is for `delay` and `retry-interval`, but not for `duration`.

I can reproduce this issue with the latest hurl version:

```
hurl --version
hurl 6.0.0 (x86_64-apple-darwin23.0) libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.61.0
Features (libcurl):  alt-svc AsynchDNS HSTS HTTP2 IPv6 Largefile libz NTLM SPNEGO SSL UnixSockets
Features (built-in): brotli
```

Running a test, I get an error:

```
error: Parsing literal
  --> performance_tests/perf.hurl:17:14
   |
17 | duration < 20s
   |              ^ expecting 'line_terminator'
   |
```

@jcamiel : would you mind re-opening this issue?

**Comment by fabricereix** [comment]
We can create another issue. This issue is linked to the current release.

**Comment by Jiehong** [comment]
@fabricereix well, this issue did show units on durations, but it was not implemented.

From the first comment on this ticket:

```
[Asserts]
duration < 1s
```

So, maybe it's more a bug than a feat, or both. Fair enough. Thanks for the new ticket.
