### ISSUE TITLE
[Feature] `--interactive` mode should tell the user what the next request would be if "Continue" were selected

### ISSUE THREAD

**Issue by jpluscplusm** [Orange-OpenSource/hurl#268]
Hey there👋 Loving hurl!

As I started to dig into the different use cases that the tool allows, I tried out the `--interactive` mode. It occurred to me that it would be really handy if, during a sequence of requests, it informed me what the next request /would/ be, if I were to hit `C`.

I don't believe this change in output could possibly break anyone's existing workflows, as the nature of the tool is that it's driven by machines and only /humans/ will drop into interactive mode. No-one should be mechanising the parsing of the output of `--interactive` mode!

**Comment by jcamiel** [comment]
Hi, good idea, indeed with this you could run an Hurl file and see what's coming. The interactive mode is very "raw" now but we keep the idea for the next version.
