### ISSUE TITLE
hurl: /lib64/libcurl.so.4: no version information available (required by hurl)

### ISSUE THREAD

**Issue by sardaukar** [Orange-OpenSource/hurl#279]
I get this running the binary in Fedora 34. Do I need an extra lib? Hurl still works, would just like to fix the warning

**Comment by jcamiel** [comment]
I've reproduced this warning with the Hurl Linux precompiled binary and a Fedora 34 image.
While we try to understand/solve the issue, you can install Hurl with Cargo and everything should be fine, without any warning:

```
$ yum install cargo libxml2-devel openssl-devel
$ cargo install hurl
$ export PATH=/root/.cargo/bin:$PATH
$ hurl --version
hurl 1.3.1
```

**Comment by azzamsa** [comment]
Is there a way to fix this with binary install?

**Comment by jcamiel** [comment]
We need to work on it in order to understand what's going on. Meanwhile, you can try to install Hurl with Cargo (https://hurl.dev/docs/installation.html#cargo), that should produce a correct binary on Fedora.

**Comment by vaidis** [comment]
```
[root@rocky_linux_v9 ~]# cargo install hurl
...
error: failed to compile `hurl v4.0.0`, intermediate artifacts can be found at `/tmp/cargo-installDxkBi8`

Caused by:
  package `hurl v4.0.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.66.1
```

any other ideas on how to install hurl to redhat/rocky?

**Comment by lepapareil** [comment]
> ```
> [root@rocky_linux_v9 ~]# cargo install hurl
> ...
> error: failed to compile `hurl v4.0.0`, intermediate artifacts can be found at `/tmp/cargo-installDxkBi8`
> 
> Caused by:
>   package `hurl v4.0.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.66.1
> ```
> 
> any other ideas on how to install hurl to redhat/rocky?

Hi @vaidis, You have to install rust 1.70 or newer to be able to build hurl 4.0.0+ on rockylinux v9. You have to follow these prerequisites:

```shell
yum install -y pkg-config gcc openssl-devel libxml2-devel git
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
git clone --depth 1 https://github.com/Orange-OpenSource/hurl.git
cd hurl
cargo install hurl
```
