### ISSUE TITLE
Install Hurl in Windows via chocolatey

### ISSUE THREAD

**Issue by tbolon** [Orange-OpenSource/hurl#282]
[chocolatey.org](https://chocolatey.org/) is a well-established software manager and repository for windows.

It could be useful to register hurl on this repo. I could help by creating a PR with necessary scripts and steps if interested.

**Comment by fabricereix** [comment]
@tbolon @lepapareil 
I'm closing this issue for scoop and create a new one #304  just for choco

**Comment by lepapareil** [comment]
Waiting for reviewer at https://community.chocolatey.org/packages/hurl/1.4.0

**Comment by lepapareil** [comment]
Since hurl choco package has successfully passed all automatic checks, we can already install hurl 1.4.0 with

```
choco install hurl --version=1.4.0
```

But the package is still waiting human moderation, so it is not publicly visible at the moment and therefore can not be found by `choco search hurl` or installed by `choco install hurl`

**Comment by lepapareil** [comment]
Hurl choco package is here !

```
choco install hurl
```
