### ISSUE TITLE
Allow bare --json parameter to write json to stdout

### ISSUE THREAD

**Issue by tbolon** [Orange-OpenSource/hurl#283]
I am planning to use hurl for integration testing and I want to parse the hurl output to generate CI/CD test results.

I have developed a custom program which is responsible for running hurl for multiple files and generate a test result compatible with our CI/CD infrastructure (azure devops).

As my custom program can read the standard output from hurl, and because the json format is perfect to read the results, I expected I could read the json directly from the program output.

But is seems the json result must be written in a file.

Perhaps if the `file` argument is omitted when adding the `--json` option, the result could be simply written to the output ?

PS: I know that the json option already append result to files (in case when you want to run hurl multiple times), but I find the standard output parsing easier (because it will not pollute the output directory with a result file).

PS2: Maybe this behavior could also be applied to the `--html` option ?

**Comment by tbolon** [comment]
No problem, take your time. For now I will use the json file on disk to generate the test result summary.

**Comment by fabricereix** [comment]
As described in #330 , `--json` will now change the default output to JSON.
It won't take a filename anymore.

**Comment by lepapareil** [comment]
As described in #330 , --json will:

outputs to stdout (instead of a file)
replace default body output
conflicts with --summary
