### ISSUE TITLE
Using hurl as a library

### ISSUE THREAD

**Issue by nikeee** [Orange-OpenSource/hurl#284]
I really love this tool. I loce it so much that I'd like to integrate it into some project. If I'm not mistaking, it's currently only a CLI tool (and a rust crate).

Sadly, most of my current projects that would benefit from this aren't written in rust. Would it be possible to somehow provide a version of this with FFI wrappers to the main part? Glancing at the source, this seems to be the function that would need to be wrapped:
https://github.com/Orange-OpenSource/hurl/blob/dab4006346b655b13ccdfbb1006c382e6c71168f/packages/hurl/src/main.rs#L61-L69

Also, are there non-statically linked parts?

**Comment by fabricereix** [comment]
From what language you would like to call the Hurl API? Python?
If you can manage something, we will be interested by your feedback.

**Comment by nikeee** [comment]
It's currently .NET, which can consume exported C functions.  I'm not that much into rust, but I assume that this would require some bindgen stuff.

Python would be interesting, too.

**Comment by nikeee** [comment]
I think the first step could be to just provide a create that exposes the above mentioned `execute` function.
From that on, we can create a create (possibly independent) that wraps this function + types to whatever someone needs.

**Comment by humphd** [comment]
This is something that would be cool to do with node.js and something like https://neon-bindings.com/.  I'd love to see Hurl become more accessible to JS devs, many of whom aren't used to adding tools from outside the npm-ecosystem.

**Comment by fabricereix** [comment]
Yes, It would be good to see Hurl in the Browser/JS space.
It would useful for example to create a Hurl playground.

I initially thought about generating standard Web Assembly from Hurl Rust source code. 
But HTTP requests have to be handled outside Web Assembly.

I don't know about https://neon-bindings.com. 
It can be interesting to see how it handles these HTTP calls.

**Comment by jcamiel** [comment]
@humphd @fabricereix thinking about this issue, I'm wondering if publishing Hurl binaries to npm registry will not be sufficient (instead of building through Neon or WASM). For instance, [dprint](https://dprint.dev) is a code formatter written in Rust and [you can install it](https://dprint.dev/install/) with cargo, brew, npm etc...:

```
$ brew install dprint
$ cargo install dprint
$ npm install dprint
```

On [npm package](https://www.npmjs.com/package/dprint), dprint is listed as "npm CLI distribution for dprint"

If we do the same with the existing Hurl binaries (publishing to npm), it should be sufficient to reach JS devs ?

**Comment by humphd** [comment]
This would be great, yes. Being able to install and run `hurl` via `npm` (e.g., having it get put in `node_modules/.bin` and being able to use it via `npm` scripts, like `"test": "hurl --test ..."`) would accomplish what I'm after.

Looking at https://github.com/dprint/dprint/tree/main/deployment/npm seems to provide a good path forward.  I tried installing it, and it does exactly what `hurl` should do: a binary is downloaded and `npm` can call it:

```
$ tree -a node_modules
node_modules
├── .bin
│   └── dprint -> ../dprint/bin.js
├── .package-lock.json
└── dprint
    ├── LICENSE
    ├── README.md
    ├── bin.js
    ├── dprint
    ├── info.json
    ├── install.js
    ├── install.ps1
    ├── install.sh
    ├── install_verify_checksum.js
    └── package.json
```

**Comment by humphd** [comment]
I filed #544 to deal with the `npm` install case, so I don't hijack this issue.

**Comment by jcamiel** [comment]
We've added a sample using Hurl as a library here [`/contrib/sample`](https://github.com/Orange-OpenSource/hurl/tree/master/contrib/sample). We're using it now in the CI (see #972 ) to detect major changes in Hurl's crates API and can be used as a base for samples. I'm closing this issue for the moment.
