### ISSUE TITLE
Installer is identified as containing virus by Microsoft Defender

### ISSUE THREAD

**Issue by kuwii** [Orange-OpenSource/hurl#2848]
### What is the current *bug* behavior?

The installer cannot be run because it is identified as containing virus.

![image](https://github.com/Orange-OpenSource/hurl/assets/10705175/d05455fd-e6f9-4c02-b2e2-4e58e4336a32)

### Steps to reproduce

Run this command in terminal:

```
winget install -e --id Orange-OpenSource.Hurl
```

Or manually download the installer.

### What is the expected *correct* behavior?

The installer should work.

### Execution context

- Hurl Version (`hurl --version`): N/A unable to install.
- Defender update: 2024/5/29
- System Version: Windows 11 22631.3593

### Possible fixes

N/A

**Comment by lepapareil** [comment]
Hi @kuwii, thks for this issue, I'm going to analyze this !

**Comment by lepapareil** [comment]
It seems that is one of possible false positive on windows installer made with NSIS.
I've broken the link between the installer and the winget formula for version 4.3.0 to avoid scaring users during installation.

The rebuild of the windows 4.3.0 installer is available on and no longer makes false positives (created with the latest version of NSIS).

You can also install it with chocolatey or scoop, whose formulas are based on the zip file and not on the exe installer.

**Comment by lepapareil** [comment]
We will also enforce security by adding daily control over sha256 on our release artifacts soon.
