### ISSUE TITLE
Install via Scoop

### ISSUE THREAD

**Issue by wenmin92** [Orange-OpenSource/hurl#289]
[Scoop](https://scoop.sh/) is a handy command-line installer for Windows.

~~If you already has extra bucket added,~~ just:
```cmd
scoop install hurl
```
~~Else, add extra bucket first:~~ (while it's in the main bucket, no need to add extra bucket)
```cmd
scoop bucket add extras
```

**Comment by lepapareil** [comment]
> Updated.
> 
> * If 1.4.0 has been installed, uninstall it and reinstall.
> * If the installation is 1.3.x, just update it.

![image](https://user-images.githubusercontent.com/15672496/137883338-f90d314e-dc23-44da-8a73-447845f47076.png)
