### ISSUE TITLE
Bug: tilde not allowed in URL

### ISSUE THREAD

**Issue by fourjay** [Orange-OpenSource/hurl#294]
URL spec like
``GET https://web.augsburg.edu/~auggie/``

Reports "^ Illegal character <~>"

**Comment by jcamiel** [comment]
Good catch, we should add more tests on url parsing (maybe take inspiration from various standard lib < https://cs.opensource.google/go/go/+/refs/tags/go1.17.2:src/net/url/url_test.go>)

Also related to #233

**Comment by fabricereix** [comment]
Thanks for reporting.
The fix will be included in the next release 1.4.0.

Note that for the time-being, the percent-encoding form can be used
```
GET https://web.augsburg.edu/%7Eauggie/
```
