### ISSUE TITLE
Can you output certain fields in JSON format to output?

### ISSUE THREAD

**Issue by baerwang** [Orange-OpenSource/hurl#2983]
### Problem to solve

Create tokens and deliver them to different hurl dependencies

## get token

```hurl
GET {{host}}/v1/integration/register
[Options]
output: integration_output
HTTP 200
[Captures]
token: jsonpath "$.result.token"
```

## api response

```
{"token":"secret"}
```

## integration_output file

token: secret

## use hurl command execute next.hurl

```shell
hurl --test --error-format long --variables-file integration_output next.hurl
```

## next.hurl

```hurl
GET {{host}}/v1/integration
Authorization: Bearer {{access_token}}
HTTP 200
```

### Tasks to complete

- [ ] ...

**Comment by jcamiel** [comment]
Hi @baerwang 

Would it be possible to use [`--json`option](https://hurl.dev/docs/manual.html#json) and piping the output with `jq` for instance to extract captured variables? I have the impression that it could address your needs.

**Comment by baerwang** [comment]
> Hi @baerwang
> 
> Would it be possible to use [`--json`option](https://hurl.dev/docs/manual.html#json) and piping the output with `jq` for instance to extract captured variables? I have the impression that it could address your needs.

I think hurl could consider adding `json,xml...` parse，`jq` reduces development efficiency

**Comment by jcamiel** [comment]
Hi @baerwang 

I'm closing this issue, I've the impression that we can do what we want with `--json`.

Regards,
