### ISSUE TITLE
Building hurl with newer rust versions (1.79) errors out due to "error: field `XXX` is never read"

### ISSUE THREAD

**Issue by johanneskastl** [Orange-OpenSource/hurl#3057]
### What is the current *bug* behavior?

I am maintaining a hurl package on openSUSE. The package built fine with the 1.77 version of rust and cargo, but with 1.79 it fails with the following errors:

```
[   45s]    Compiling hurlfmt v4.3.0 (/home/abuild/rpmbuild/BUILD/hurl-4.3.0/packages/hurlfmt)
[   48s] error: field `retry` is never read
[   48s]   --> packages/hurl/src/http/options.rs:49:9
[   48s]    |
[   48s] 26 | pub struct ClientOptions {
[   48s]    |            ------------- field in this struct
[   48s] ...
[   48s] 49 |     pub retry: Retry,
[   48s]    |         ^^^^^
[   48s]    |
[   48s]    = note: `ClientOptions` has derived impls for the traits `Clone` and `Debug`, but these are intentionally ignored during dead code analysis
[   48s]    = note: `-D dead-code` implied by `-D warnings`
[   48s]    = help: to override `-D warnings` add `#[allow(dead_code)]`
[   48s] 
[   48s] error: field `worker_id` is never read
[   48s]   --> packages/hurl/src/parallel/message.rs:41:9
[   48s]    |
[   48s] 39 | pub struct IOErrorMsg {
[   48s]    |            ---------- field in this struct
[   48s] 40 |     /// Identifier of the worker sending this message.
[   48s] 41 |     pub worker_id: WorkerId,
[   48s]    |         ^^^^^^^^^
[   48s] 
[   48s] error: fields `worker_id` and `job` are never read
[   48s]   --> packages/hurl/src/parallel/message.rs:62:9
[   48s]    |
[   48s] 60 | pub struct ParsingErrorMsg {
[   48s]    |            --------------- fields in this struct
[   48s] 61 |     /// Identifier of the worker sending this message.
[   48s] 62 |     pub worker_id: WorkerId,
[   48s]    |         ^^^^^^^^^
[   48s] 63 |     /// Job originator of this message.
[   48s] 64 |     pub job: Job,
[   48s]    |         ^^^
[   48s] 
[   48s] error: field `stdout` is never read
[   48s]    --> packages/hurl/src/parallel/message.rs:111:9
[   48s]     |
[   48s] 105 | pub struct CompletedMsg {
[   48s]     |            ------------ field in this struct
[   48s] ...
[   48s] 111 |     pub stdout: Stdout,
[   48s]     |         ^^^^^^
[   48s] 
[   48s] error: field `0` is never read
[   48s]   --> packages/hurl/src/report/junit/xml/writer.rs:33:8
[   48s]    |
[   48s] 33 |     Io(std::io::Error),
[   48s]    |     -- ^^^^^^^^^^^^^^
[   48s]    |     |
[   48s]    |     field in this variant
[   48s]    |
[   48s] help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
[   48s]    |
[   48s] 33 |     Io(()),
[   48s]    |        ~~
[   48s] 
[   48s] error: field `0` is never read
[   48s]   --> packages/hurl/src/report/junit/xml/writer.rs:34:19
[   48s]    |
[   48s] 34 |     FromUtf8Error(FromUtf8Error),
[   48s]    |     ------------- ^^^^^^^^^^^^^
[   48s]    |     |
[   48s]    |     field in this variant
[   48s]    |
[   48s] help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
[   48s]    |
[   48s] 34 |     FromUtf8Error(()),
[   48s]    |                   ~~
[   48s] 
[   48s] error: field `0` is never read
[   48s]   --> packages/hurl/src/report/junit/xml/writer.rs:35:18
[   48s]    |
[   48s] 35 |     GenericError(String),
[   48s]    |     ------------ ^^^^^^
[   48s]    |     |
[   48s]    |     field in this variant
[   48s]    |
[   48s] help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
[   48s]    |
[   48s] 35 |     GenericError(()),
[   48s]    |                  ~~
[   48s] 
[   48s] error: could not compile `hurl` (lib) due to 7 previous errors
```

I am not quite sure if this was already failing with 1.78.

### What is the expected *correct* behavior?

The build should succeed. :-)

**Comment by jcamiel** [comment]
Hi @johanneskastl  first of all, thanks for maintaining the Hurl package for openSUSE! We've fixed the compilation errors when 1.79 has been released. You can check that master is building without any warnings with 1.79.

**Comment by jcamiel** [comment]
By the way, I see that we don't have any information on how to install Hurl on openSUSE, neither how to build Hurl on openSUSE on our documentation => https://hurl.dev/docs/installation.html? Would you be kind to make a PR updated this file https://github.com/Orange-OpenSource/hurl/blob/master/docs/installation.md ? (Or just give me some instructions and I will update the docs)

**Comment by johanneskastl** [comment]
> Hi @johanneskastl first of all, thanks for maintaining the Hurl package for openSUSE! We've fixed the compilation errors when 1.79 has been released. You can check that master is building without any warnings with 1.79.

OK, then I'll try to backport the fixes to the latest release. Or are you planning a new 4.x minor release soon-ish (that contains those fixes)?

**Comment by johanneskastl** [comment]
> By the way, I see that we don't have any information on how to install Hurl on openSUSE, neither how to build Hurl on openSUSE on our documentation => https://hurl.dev/docs/installation.html? Would you be kind to make a PR updated this file https://github.com/Orange-OpenSource/hurl/blob/master/docs/installation.md ? (Or just give me some instructions and I will update the docs)

Once the package builds again, I will submit it to openSUSE Tumbleweed. Once that is done, it is an "official" package and I can create a PR to update the docs.

**Comment by johanneskastl** [comment]
> OK, then I'll try to backport the fixes to the latest release. Or are you planning a new 4.x minor release soon-ish (that contains those fixes)?

Duh, I missed the patch in the list of commits.

https://github.com/Orange-OpenSource/hurl/commit/d51c275fc63d1ee5bbdc6fc70279ec8dae86a9c1.patch does the trick.
