### ISSUE TITLE
Support date utilities in variables

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#312]
Currently, to inject a date in a variable, one should compute it beforehand, before running the Hurl File.

For instance (https://hurl.dev/docs/frequently-asked-questions.html#can-i-do-calculation-within-a-hurl-file):

```
TODAY=$(date '+%y%m%d')
TOMORROW=$(date '+%y%m%d' -d"+1days")
hurl --variable "today=$TODAY" --variable "tomorrow=$TOMORROW" test.hurl
```

It could be nice to have utilities to work with date inside the Hurl file, without any pre injections.

Some examples in other tools/templating:

## [Liquid template](https://shopify.github.io/liquid/filters/date/)

> date
>
> Converts a timestamp into another date format. The format for this syntax is the same as 
> strftime. The input uses the same format as Ruby’s Time.parse.

```
Input
{{ article.published_at | date: "%a, %b %d, %y" }}

Output
Fri, Jul 17, 15
```

```
Input
{{ article.published_at | date: "%Y" }}

Output
2015
```

> date works on strings if they contain well-formatted dates.

```
Input
{{ "March 14, 2016" | date: "%b %d, %y" }}

Output
Mar 14, 16
```

> To get the current time, pass the special word "now" (or "today") to date.

```
Input
This page was last updated at {{ "now" | date: "%Y-%m-%d %H:%M" }}.

Output
This page was last updated at 2021-04-28 17:52.
```

Offset are also possible:

```
{{ myDate | date_add: 7, "day" }} 
```

## [Wiremock](http://wiremock.org/docs/response-templating/)

> A helper is present to render the current date/time, with the ability to specify the 
> format (via Java’s SimpleDateFormat) and offset.

```
{{now}}
{{now offset='3 days'}}
{{now offset='-24 seconds'}}
{{now offset='1 years'}}
{{now offset='10 years' format='yyyy-MM-dd'}}
```

> Dates can be rendered in a specific timezone (the default is UTC):

```
{{now timezone='Australia/Sydney' format='yyyy-MM-dd HH:mm:ssZ'}}
```

> Pass epoch as the format to render the date as UNIX epoch time (in milliseconds), or unix 
> as the format to render the UNIX timestamp in seconds.

```
{{now offset='2 years' format='epoch'}}
{{now offset='2 years' format='unix'}}
```

> Dates can be parsed using the parseDate helper:

```
// Attempts parsing using ISO8601, RFC 1123, RFC 1036 and ASCTIME formats.
// We wrap in the date helper in order to print the result as a string.
{{date (parseDate request.headers.MyDate)}}

// Parse using a custom date format
{{date (parseDate request.headers.MyDate format='dd/MM/yyyy')}}

// Format can also be unix (epoch seconds) or epoch (epoch milliseconds)
{{date (parseDate request.headers.MyDate format='unix')}}
```

## [Jinja](https://jinja.palletsprojects.com/en/3.0.x/)

Jinja has [filters](https://jinja.palletsprojects.com/en/3.0.x/templates/#list-of-builtin-filters), but no facilities for date.

```
{{ name|striptags|title }
{{ "foo bar baz qux"|truncate(11) }} -> "foo bar baz qux"
```

## [Djando](https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#std:templatefilter-date)

```
{{ value|date:"D d M Y" }}
```

```
{{ value|date:"SHORT_DATE_FORMAT" }}
```

## [Twig](https://twig.symfony.com/doc/2.x/filters/date.html)

```
{{ post.published_at|date("m/d/Y") }}
```

With Timezone:

```
{{ post.published_at|date("m/d/Y", "Europe/Paris") }}
```

Offset and modification can be use with [`date_modify`](https://twig.symfony.com/doc/2.x/filters/date_modify.html) filter:

```
{{ post.published_at|date_modify("+1 day")|date("m/d/Y") }}
```

## [Tera](https://tera.netlify.app/docs/#date)

```
{{ "2019-09-19T13:18:48.731Z" | date(timezone="America/New_York") }}
{{ "2019-09-19T13:18:48.731Z" | date(format="%Y-%m-%d %H:%M", timezone="Asia/Shanghai") }}
```

**Comment by atcol** [comment]
The wiremock examples look **really** useful for a number of usecases I can imagine.

Is there a decision on what Hurl will support regarding dates & other templating behaviour?

**Comment by icepuma** [comment]
I really like `tera` which makes use of named parameters and the `function(...)` - syntax. The result of a function could be pipeable as well.

**Comment by jcamiel** [comment]
@icepuma I link here you issue https://github.com/Orange-OpenSource/hurl/issues/606 

For reference, as proposed, we could also support functions generating random data:

```hurl
# Create a new doggy thing with JSON body:
POST https://example.org/api/dogs
{
    "id": 0,
    "name": "{{random_alphanumeric(12)}}",
    "picture": "images/scottish-terrier.jpeg",
    "age": {{random_int()}},
    "breed": "Scottish Terrier",
    "location": "Lisco, Alabama"
}
```

**Comment by fabricereix** [comment]
We like that too
"filter" functions which can take input from a previous pipe
with possible parameters between brackets
 
We are in the process of generalizing templates everywhere in the Hurl file.
After that, we can start formalizing these functions in the [grammar](https://hurl.dev/docs/grammar.html)

**Comment by victoraugustolls** [comment]
Is there any way to get `now` timestamp in hurl? Not by environment variables, but I have a use case in that I need up to seconds precision, and `daysBeforeNow` does not cover that!

**Comment by jcamiel** [comment]
Hi @victoraugustolls 

Can you give us more details about your use case? We've things related to duration:[timings](https://hurl.dev/docs/response.html#timings) that you can access through [`--json`](https://hurl.dev/docs/manual.html#json), or [`duration` query](https://hurl.dev/docs/capturing-response.html#duration-capture) that you can assert and capture.
If you've an hypothetic Hurl file example that you want to exist, it's a + !

**Comment by jcamiel** [comment]
@victoraugustolls it's been a while but we've introduced [functions](https://hurl.dev/docs/templates.html#functions) in Hurl 6.0.0

`newDate` function can be used to create a RFC3339 string at the current time:

```hurl
GET https://example.org/api/foo
[Query]
date: {{newDate}}
HTTP 200
```

Run a GET request to https://example.org/api/foo?date=2024%2D12%2D02T10%3A35%3A44%2E461731Z where the date query parameter value is 2024-12-02T10:35:44.461731Z URL encoded.

**Comment by chris-kahn-woven** [comment]
It would be useful if this had more options beyond RFC3339 date strings, such as UNIX epoch timestamps or other formats. Not all APIs accept RFC3339 strings.

**Comment by jcamiel** [comment]
@chris-kahn-woven yes indeed, what we plan to to is to be able to add [filters](https://hurl.dev/docs/filters.rs) in templates.
With such a feature, you'll be able to [format a date](https://hurl.dev/docs/filters.html#dateformat) in any format:

```hurl
GET https://example.org/api/foo
[Query]
# Make a timestamp date
timestamp: {{newDate format "%s"}}
# Make a "2026-02-20" like date
date: {{newDate format "%y/%m/%d"}}
HTTP 200
