### ISSUE TITLE
Unable to pass an array of integers in a variable

### ISSUE THREAD

**Issue by meleu-cw** [Orange-OpenSource/hurl#3136]
### What is the current *bug* behavior?

Hurl doesn't accept passing an array of integers as a variable.

Example:

`array-var.hurl`
```hurl
POST http://localhost:8080
{
  "array": {{my_array}}
}
```

```
[prompt]$ hurl --variable my_array='[1,2,3]' array-var.hurl
error: Invalid JSON
  --> array-var.hurl:3:14
   |
   | POST http://localhost:8080
   | ...
 3 |   "array": {{my_array}}
   |              ^^^^^^^^ actual value is <[1,2,3]>
   |
```

It fails saying that the JSON is invalid, but if I hardcode `{"array": [1,2,3]}` it's obviously a valid JSON and it works fine.

### Steps to reproduce

Described above 👆 

### What is the expected *correct* behavior?

In the scenario described above I expect hurl to "inject" the variable in the right place and send a body with:
```json
{
  "array": [1,2,3]
}
```

### Execution context

- Hurl Version (`hurl --version`):
```
hurl 4.3.0 (x86_64-apple-darwin23.0) libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.61.0
Features (libcurl):  alt-svc AsynchDNS HSTS HTTP2 IPv6 Largefile libz NTLM SPNEGO SSL UnixSockets
Features (built-in): brotli
```

**Comment by jcamiel** [comment]
Hi @meleu-cw 

Passing array or object is not supported yet in JSON body request but there is a workaround. You can use multiline string body, with a `json` "language hint" (like in Markdown GitHub flavored):


~~~hurl
POST http://localhost:8080
```json
{
  "array": {{my_array}}
}
```
~~~

Normally it should work, while I've not tested it.

**Comment by meleu-cw** [comment]
Thanks! Using your solution solved my problem. :)

Feel free to close the issue if you deem necessary.
