### ISSUE TITLE
[Options] with POST body at the same time

### ISSUE THREAD

**Issue by Rexee** [Orange-OpenSource/hurl#3213]
Not sure if it's a issue/bug or I just don't know how to setup it correctly.

### What is the current *bug* behavior?
When I try to use [Options] block together with request body, HURL drops error:
```
 5 | [Options]
   | ^ the HTTP method <> is not valid. Valid values are GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH
```

### Steps to reproduce
Create hurl file with following content:
```
POST https://hurl.dev
Content-Type: {{content_type}}
{"sample":"value"}
[Options]
variable: content_type=application/json

HTTP 200
```
Run it with hurl.

### What is the expected *correct* behavior?
[Options] should works correctly with request body without dropping error.

### Execution context
hurl --version:
```
hurl 4.3.0 (x86_64-apple-darwin23.0) libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.61.0
Features (libcurl):  alt-svc AsynchDNS HSTS HTTP2 IPv6 Largefile libz NTLM SPNEGO SSL UnixSockets
Features (built-in): brotli```

**Comment by jcamiel** [comment]
Hi @Rexee 

In a request, the body must be after any section, you can see it here <https://hurl.dev/docs/request.html>

You Hurl file should be:

```
POST https://hurl.dev
Content-Type: {{content_type}}
[Options]
variable: content_type=application/json
{"sample":"value"}

HTTP 200
```

And that should be OK!
