### ISSUE TITLE
Allow Hurl file to be validated without execution

### ISSUE THREAD

**Issue by bbkfhq** [Orange-OpenSource/hurl#3222]
### Problem to solve

There is no way to validate a Hurl file without also executing it.

### Proposal

Add a command-line flag such as `--validate` which instructs Hurl to only validate the provided file without executing it.

Example: `hurl --validate test.hurl` (exit code 0 to indicate valid file, exit code 2 to indicate parsing error)

Example (stdin): `cat test.hurl | hurl --validate`

### Use case

I'm building some test execution tools using Hurl. It would be convenient to be able to validate a test file without attempting to execute it. This will be used when validating user-provided tests. So that invalid tests can be caught early and reported prior to execution.

**Comment by jcamiel** [comment]
Hi @bbkfhq 
you can use `hurlfmt` to test the syntax of an Hurl file without executing it: `hurlfmt foo.hurl` and that's all.

**Comment by bbkfhq** [comment]
@jcamiel oh didn't know about that. It's great, thank you! I will close this ticket now.
