### ISSUE TITLE
Orange Livebox development team bug report

### ISSUE THREAD

**Issue by josephernest** [Orange-OpenSource/hurl#3262]
Hello @fabricereix @jcamiel , I tried a few months ago to contact the Orange Livebox development team to submit a detailed bug report, but I couldn't find the right persons (of course the phone consumer support didn't help for that: the bug report will end nowhere...).
I tried on LinkedIn and discussed with a few persons but I couldn't find the right persons at Orange to submit a bug report.

Can you contact me via email (contact@samplerbox.org) or point me to the right team so that my bug report has a change to reach someone actually involved in the development?

Thanks in advance!

**Comment by jcamiel** [comment]
Hi @josephernest 

We're looking for the best contact inside Orange, we will mail you when we find the right person

**Comment by jcamiel** [comment]
Hi @josephernest 

Somebody from Orange should normally have contacted you. I'm closing this issue

Thanks!
