### ISSUE TITLE
Add ARM Testing with Circle CI

### ISSUE THREAD

**Issue by fabricereix** [Orange-OpenSource/hurl#335]
Currently, ARM Architecture can not be tested with Github actions.

**Comment by lepapareil** [comment]
We can easily emulate arm64 cpus over ubuntu, installing qemu, docker and run arm64v8 images:

```
sudo apt update -qq
sudo apt install -y -qq qemu qemu-user-static binfmt-support
sudo update-binfmts --enable qemu-arm
```
