### ISSUE TITLE
Upgrade CI/CD Python 3.11

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#3472]
@lepapareil it would cool if we can upgrade our CI from Python 3.10 to Python 3.11 (I need some new stuff available in 3.11).

**Comment by lepapareil** [comment]
| ci os | actual python version | status |
|-|-|-|
| archlinux x64 base-20241201.0.284684 | 3.12.7 |✅|
| fedora x64 41 | 3.11.10 |✅|
| alpine x64 3.20.3 | 3.12.7 |✅|
| macos x64 13.7.1 22H221 | 3.13.0 |✅|
| macos aarch64 14.7.1 23H222 | 3.13.0 |✅|
| windows x64 wsl ubuntu 22.04 | 3.10.12 |⛔|
| windows x64 Server 2022 10.0.203 | 3.9.13 |⛔|
| ubuntu 20.04 | 3.10.15 |⛔|
| ubuntu 22.04 | 3.10.15 |⛔|

**Comment by jcamiel** [comment]
😞 thanks, we'll update it when 3.11 is available everywhere

**Comment by lepapareil** [comment]
🤔... Don't worry @jcamiel, I'll give a try this week !

**Comment by lepapareil** [comment]
After https://github.com/Orange-OpenSource/hurl/pull/3497:

| ci os | actual python version | status |
|-|-|-|
| archlinux x64 base-20241201.0.284684 | 3.12.7 |✅|
| fedora x64 41 | 3.11.10 |✅|
| alpine x64 3.20.3 | 3.12.7 |✅|
| macos x64 13.7.1 22H221 | 3.13.0 |✅|
| macos aarch64 14.7.1 23H222 | 3.13.0 |✅|
| windows x64 wsl ubuntu 22.04 | 3.10.12 |⛔|
| windows x64 Server 2022 10.0.203 | 3.11.9 |✅|
| ubuntu 20.04 | 3.10.15 |⛔|
| ubuntu 22.04 | 3.10.15 |⛔|

**Comment by lepapareil** [comment]
After https://github.com/Orange-OpenSource/hurl/pull/3501 :

| ci os | actual python version | status |
|-|-|-|
| Docker ubuntu x64 22.04 | 3.11.11 |✅|
| Docker archlinux x64 base-20241201.0.284684 | 3.12.7 |✅|
| Docker debian x64 12 | 3.11.2 |✅|
| Docker fedora x64 41 | 3.11.10 |✅|
| Docker alpine x64 3.20.3 | 3.12.7 |✅|
| MacOs x64 13.7.1 22H221 | 3.13.0 |✅|
| MacOs aarch64 14.7.1 23H222 | 3.13.0 |✅|
| Windows x64 wsl ubuntu 22.04 | 3.11.11 |✅|
| Windows x64 Server 2022 10.0.203 | 3.11.9 |✅|
| Ubuntu 20.04 | 3.11.10 |✅|
| Ubuntu 22.04 | 3.11.10 |✅|
| Dockerfile alpine 3.17 | 3.10.15 |⛔|

**Comment by lepapareil** [comment]
Now, after https://github.com/Orange-OpenSource/hurl/pull/3503 :

| ci os | actual python version | status |
|-|-|-|
| Docker ubuntu x64 22.04 | 3.11.11 |✅|
| Docker archlinux x64 base-20241201.0.284684 | 3.12.7 |✅|
| Docker debian x64 12 | 3.11.2 |✅|
| Docker fedora x64 41 | 3.11.10 |✅|
| Docker alpine x64 3.20.3 | 3.12.7 |✅|
| MacOs x64 13.7.1 22H221 | 3.13.0 |✅|
| MacOs aarch64 14.7.1 23H222 | 3.13.0 |✅|
| Windows x64 wsl ubuntu 22.04 | 3.11.11 |✅|
| Windows x64 Server 2022 10.0.203 | 3.11.9 |✅|
| Ubuntu 20.04 | 3.11.10 |✅|
| Ubuntu 22.04 | 3.11.10 |✅|
| Dockerfile alpine 3.17 | 3.12.8 |✅|

Enjoy @jcamiel !
