### ISSUE TITLE
 application does not appear in windows uninstall control panel after installing by windows nsis installer

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#348]
https://github.com/microsoft/winget-pkgs/pull/34558#issuecomment-965293184

**Comment by lepapareil** [comment]
#349 

![image](https://user-images.githubusercontent.com/15672496/141171090-aea80c5b-772d-48aa-a41f-942e72b45ef7.png)

**Comment by jcamiel** [comment]
👍
