### ISSUE TITLE
Wait till some conditions are matched

### ISSUE THREAD

**Issue by allevo** [Orange-OpenSource/hurl#3513]
### Problem to solve

I have two endpoints:
- the first one processes the input data in background. The time used to process that data is unknown, but typically in a few seconds
- the second endpoint fetches the processed data.

I have the Hurl script that invokes the first and second endpoints.
The first invocation was correctly processed, and the response was okay.
The second invocation failed because the data was not yet available.

I didn't find any mention in the docs of how to resolve this issue.

### Proposal

- The fast implementation could be put a "sleep 5" command to stop the execution for 5 seconds
- Another implementation could be a "while" loop that executes the invocation till some conditions are matched (HTTP status code, body checks)

### Tasks to complete

- [ ] ???

**Comment by lepapareil** [comment]
Hi @allevo !

You can use the `retry` options like described in https://hurl.dev/docs/samples.html#polling-and-retry 😄.

**Comment by allevo** [comment]
Hi! Thank you for the quick answer.
Can I suggest making that configuration searchable with "sleep" "wait" keywords?

**Comment by lepapareil** [comment]
Hi @allevo !

Thanks to @jcamiel, searching `sleep` now leads to `delay` pages => https://hurl.dev/search.html?query=sleep# 😊.

**Comment by lepapareil** [comment]
Hi @allevo, can we close this issue ?
