### ISSUE TITLE
add generic linux binary test over linux distributions when releasing

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#355]

**Comment by jcamiel** [comment]
@lepapareil we can maybe close this one ?

**Comment by lepapareil** [comment]
> @lepapareil we can maybe close this one ?

We still need this ci feature, but we need to discuss it further ;)

**Comment by lepapareil** [comment]
@jcamiel we will add this feature on the releasing workflow as a prerequisite to the creation of the final versioned GitHub package.

**Comment by lepapareil** [comment]
0a763ab92ff62ff01d5288ba2a3b1b4e056b269e
af62ed41b36683385219b634b9b743e8c9f1b396
e927ec9593eb12423a469f932f0f6005834d474a
c01cde1fb1f647f8c893256559239a4539ec28d9
1d1600a446162351c124bd6905b720e3a4ec3362
ecbab75b5d6f933d4d8581bc31633ff98c22b796
