### ISSUE TITLE
Support inclusion of user/password in request without using --user

### ISSUE THREAD

**Issue by humphd** [Orange-OpenSource/hurl#360]
It's possible this can already be done, and I'm missing it; but I want to be able to specify basic HTTP auth with user and password in a test, but not set it globally for all tests.  That is, in some tests I want to use userA and in others, userB.

**Comment by fabricereix** [comment]
There isn't something specific for the basic auth for one test.
It has to be encoded explictly in a header.

For example, for the user bob with password 'secret'
```
$ echo 'bob:secret' | base64
Ym9iOnNlY3JldAo=
```

```
GET http://example.com/protected
Authorization: Ym9iOnNlY3JldAo=
```

**Comment by fabricereix** [comment]
For sure, BasicAuth makes a good sample for the doc.

The section could also be specific for BasicAuth
```
GET https://example.org/account
[BasicAuth]
bob:secret
HTTP/1.1 200
```

or maybe, within the templating
```
GET https://example.org/account
Authorization: Basic {{'bob:secret' | base64}}
HTTP/1.1 200
```

**Comment by lepapareil** [comment]
```
[BasicAuth]
bob:secret
```
👍

**Comment by humphd** [comment]
Adding a `[BasicAuth]` section with `bob:secret`, where you can easily include the username and password without encoding (i.e., greater clarity in test cases), would be perfect. +1

**Comment by jcamiel** [comment]
Updated [README.md](https://github.com/Orange-OpenSource/hurl#http-headers) and [hurl.dev documentation](https://hurl.dev/docs/samples.html#http-headers) with basic authentification sample.

**Comment by humphd** [comment]
Thanks for the details and doc update with example.  It allowed me to do what I needed.

**Comment by fabricereix** [comment]
We forgot that we can also use the user:password in the url.

There willl be therefore 3 possible ways to add basicAuth at the request level
```
GET http://bob:secret@example.com/protected
HTTP/1.0 200

GET http://example.com/protected
Authorization: Basic Ym9iOnNlY3JldA==
HTTP/1.0 200

GET http://example.com/protected
[BasicAuth]
bob:secret
HTTP/1.0 200
```
