### ISSUE TITLE
Clarify output option for 1.5.0 (stderr/stdout)

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#369]
Three output streamable:

default: stream of body response, stdout
`--json`: stream of json, each Hurl file outputs a valid son, stdout
`--text`: stream of text lines, each Hurl file outputs a line

An option on stderr to summarise a test suite: `--summary`

An option on stderr to display progress: `--progress`

Option to produce different report:
- `--report-html`
- `--report-junit`

A shortcut option: `--summary`. Alias for `--pro

Sample:

```shell
            $ hurl --json tests/*.hurl
stdout      {"test":"a.hurl", "succeed": true...}
stdout      {"test":"b.hurl", "succeed": true...}
stdout      {"test":"c.hurl", "succeed": false...}
```

```shell
            $ hurl --json --summary tests/*.hurl 
stdout      {"test":"a.hurl", "succeed": true...}
stdout      {"test":"b.hurl", "succeed": true...}
stdout      {"test":"c.hurl", "succeed": false...}
stderr      --------------------------------------------------------------------------------
stderr      Executed:  3
stderr      Succeeded: 2 (100.0%)
stderr      Failed:    0 (0.0%)
stderr      Duration:  40ms
```

```shell
            $ hurl --json --progress tests/*.hurl
stderr      a.hurl: RUNNING [1/3]
stderr      a.hurl: SUCCESS
stdout      {"test":"a.hurl", "succeed": true...}
stderr      b.hurl: RUNNING [2/3]
stderr      b.hurl: SUCCESS
stdout      {"test":"b.hurl", "succeed": true...}
stderr      c.hurl: RUNNING [3/3]
stderr      c.hurl: SUCCESS
stdout      {"test":"c.hurl", "succeed": false...}
```

```shell
            $ hurl --json --progress --summary tests/*.hurl
stderr      a.hurl: RUNNING [1/3]
stderr      a.hurl: SUCCESS
stdout      {"test":"a.hurl", "succeed": true...}
stderr      b.hurl: RUNNING [2/3]
stderr      b.hurl: SUCCESS
stdout      {"test":"b.hurl", "succeed": true...}
stderr      c.hurl: RUNNING [3/3]
stderr      c.hurl: SUCCESS
stdout      {"test":"c.hurl", "succeed": false...}
stderr      --------------------------------------------------------------------------------
stderr      Executed:  3
stderr      Succeeded: 2 (100.0%)
stderr      Failed:    0 (0.0%)
stderr      Duration:  40ms
```

```shell
            $ hurl --test tests/*.hurl
stderr      a.hurl: RUNNING [1/3]
stderr      a.hurl: SUCCESS
stderr      b.hurl: RUNNING [2/3]
stderr      b.hurl: SUCCESS
stderr      c.hurl: RUNNING [3/3]
stderr      c.hurl: SUCCESS
stderr      --------------------------------------------------------------------------------
stderr      Executed:  3
stderr      Succeeded: 2 (100.0%)
stderr      Failed:    0 (0.0%)
stderr      Duration:  40ms
```

**Comment by fabricereix** [comment]
In the examples, we could distinguish between stdout and stderr

              $ hurl --json --progress tests/*.hurl
    stderr    a.hurl: RUNNING [1/3]
    stderr    a.hurl: SUCCESS
    stdout    {"test":"a.hurl", "succeed": true...}
    stderr    b.hurl: RUNNING [2/3]
    stderr    b.hurl: SUCCESS
    stdout    {"test":"b.hurl", "succeed": true...}
    stderr    c.hurl: RUNNING [3/3]
    stderr    c.hurl: SUCCESS
    stdout    {"test":"c.hurl", "succeed": false...}

**Comment by jcamiel** [comment]
Updated with stdout and stderr

**Comment by fabricereix** [comment]
To be explicit than `--text`,  the option `--csv` can be defined with the following columns: 
- filename
- status
- duration
- ...

**Comment by fabricereix** [comment]
`--test` combines several options. It disables output (response body/JSON) but it also add progress and a summary.
 The option `--noout` could be also be used just to disable output.

This option name  is used by xmllint (http://xmlsoft.org/xmllint.html)

Note that disabling output is not exactly the same than redirecting to /dev/null.
For example, with the option `--compressed` (https://hurl.dev/docs/man-page.html#compressed), the output is automatically is automatically decompressed before being written, that can take time and that can produce errors.

For example,  ` echo POST http://localhost | hurl --noout` will send a POST request, but won't output anything (except possible connection errors) in the terminal.
