### ISSUE TITLE
Add option `--resolve`

### ISSUE THREAD

**Issue by fabricereix** [Orange-OpenSource/hurl#379]
Add curl option `--resolve`
(https://curl.se/docs/manpage.html#--resolve)

**Comment by JanKoppe** [comment]
This would be a pretty great feature! We're currently trying to use Hurl to test an elaborate Caddy configuration locally before rolling it out, and it would be awesome if we could just resolve all the hundreds of hostnames in that case to localhost instead to point it to the test-instance of Caddy.

Currently I'm struggling to find an alternative way to do this.
