### ISSUE TITLE
Improving pattern for regex capture and matches predicates

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#4]
Currently, regex patterns are used in :
- regex query
- matches predicate

```
GET http://localhost:8000/assert-regex

HTTP/1.0 200
[Asserts]
regex "Hello ([0-9]+)!" not exists
regex "Hello ([a-zA-Z]+)!" equals "World"
body matches "Hello [a-zA-Z]+!"
```

Pattern in Hurl grammar use `quoted-string`: the problem is that backslash in `quoted-string` should be escaped. So to use special character in pattern (like `\d`, `\s`), backslash should be escaped, degrading the readability of the pattern:

```
regex "Hello (\\d)!" not exists
```

In Rust, Python, Kotlin, raw strings are used to improve the regex readability. In Rust, for instance:

```rust
use regex::Regex;
let re = Regex::new(r"^\d{4}-\d{2}-\d{2}$").unwrap();
assert!(re.is_match("2014-01-01"));
```
In the Hurl grammar, we already have raw string (&#96;&#96;&#96;something\ntutu&#96;&#96;&#96; is literally the string "something\ntutu" without a newline between something and tutu). We could reuse this syntax when using regex query or matches predicates:

Before:

```
GET http://localhost:8000/assert-regex

HTTP/1.0 200
[Asserts]
regex "abc(\\d+)!" exists
jsonpath "$.date1" matches "\\d{4}-\\d{2}-\\d{2}"
```

After:

~~~
GET http://localhost:8000/assert-regex

HTTP/1.0 200
[Asserts]
regex ```abc(\d+)!``` exists
jsonpath "$.date1" matches ```\d{4}-\d{2}-\d{2}```
~~~

We could also introduce another syntax, like Python raw string and Rust raw string and keep ``` for body raw string:

```
GET http://localhost:8000/assert-regex

HTTP/1.0 200
[Asserts]
regex r"abc(\d+)!" exists
jsonpath "$.date1" matches r"\d{4}-\d{2}-\d{2}"
```

raw-string like r"abcd" could be used anywhere a quoted-string is used (not limited to regex capture and matches predicate)

**Comment by humphd** [comment]
I ran into this today, and was just coming to file a docs issue before seeing this already open.  Here is what I hit:

```
10 | jsonpath "$.version" matches "\d+\.\d+\.\d+"
   |                                ^ The escaping sequence is not valid
```

It wasn't intuitive to me that I needed to escape my backslashes, especially since there aren't any examples of this in the docs (I looked at your tests to figure out what the problem was).

Could you support `matches /\d+\.\d+\.\d+/` vs `"\\d+\\.\\d+\\.\\d+"` so that you can avoid this?

At the very least, more significant examples in the docs would help a lot.

**Comment by fabricereix** [comment]
Thanks for your suggestion.
I like the regex-specific type `/.../` a lot.
It is quite standard and even used in javascript (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions).

It really improves the readability of the Hurl file.

**Comment by jcamiel** [comment]
Yes, big fan of @humphd suggestion for regex syntax, feels natural.
I've updated the docs about regex escaping also here:

- <https://hurl.dev/docs/asserting-response.html#regex-assert>
- <https://hurl.dev/docs/capturing-response.html#regex-capture>
- <https://hurl.dev/docs/capturing-response.html#regex-subquery>
- <https://hurl.dev/docs/samples.html#testing-rest-apis>

**Comment by fabricereix** [comment]
Regex Literals /.../ should probably not include any Hurl template.
Keeping the special characters '{' and '}' only for regex quantifiers.

We could maybe still use a string value for the match only if we need a template.

```
jsonpath "$.date" matches /\d{4}-\d{2}-\d{2}/                   # using regex literal
jsonpath "$.date" matches "{{year}}/\\d{4}-\\d{2}-\\d{2}"       # using string template

```
