### ISSUE TITLE
Should error on missing closing quote

### ISSUE THREAD

**Issue by humphd** [Orange-OpenSource/hurl#403]
Using hurl v1.4.0, when I run this test, it passes.  I think it should error, since I haven't closed the quote after `"not found`:

```
GET http://localhost:8080/not-found

HTTP/1.1 404
[Asserts]
# NOTE: missing closing quote here doesn't cause an error
jsonpath "$.error.message" == "not found
```

**Comment by jcamiel** [comment]
Yes exactly, it it not syntactically correct and should have been in error!
Shameful bug, thanks for spotting it @humphd (still present on master)

**Comment by fabricereix** [comment]
Thanks for reporting. I can't believe we had not caught this one before. 

With the fix, it will produce the following error
```
error: Parsing literal
  --> test.hurl:6:41
   |
 6 | jsonpath "$.error.message" == "not found
   |                                         ^ expecting '"'
   |
```
