### ISSUE TITLE
variable hostname/authority in the request url

### ISSUE THREAD

**Issue by a5huh** [Orange-OpenSource/hurl#408]
I'm evaluating hurl for use at my work. One that that would be useful is if the request url can support variables for the hostname/authority portion of the url. According the grammar (https://hurl.dev/docs/grammar.html#url) it does not.

This would be useful so that a hurl file can be run against different environments (local development, staging, production).

**Comment by jcamiel** [comment]
Hi, 

It's quite not clear in the documentation but you can write templates in a lot of "values" like url, status code, assert values etc... If you've not found it in our doc, we need to be clearer.

In the [templates section](https://hurl.dev/docs/templates.html), we have a basic description of how templates work. In <https://hurl.dev/docs/templates.html#injecting-variables>, for instance, you can have this Hurl file:

```hurl
GET {{my_url}}/status
HTTP/1.1 304
```

and runs it with `$ hurl --variable my_url=https://example.net test.hurl`.

This will result to :

```hurl
GET https://example.net/status
HTTP/1.1 304
```

If you have a lot of variable, you can set them in a file with [`--variables-file`](https://hurl.dev/docs/man-page.html#variables-file). And starting with hurl 1.5.0, variables can also be set using environment variables (the doc is not yet updated for this option): 

```
export HURL_my_url=https://example.net
```

will produce variable my_url with value https://example.net

I hope that's what your question is about! If not, could you give us a sample of what you need ?

**Comment by a5huh** [comment]
That's exactly what I was looking for. Thanks.
