### ISSUE TITLE
How to assert if a json object is included in a collection

### ISSUE THREAD

**Issue by fjchen7** [Orange-OpenSource/hurl#420]
Assume that we have the json
```json
{
    "fruit": [
        {
            "name": "apple",
            "price": 100
        },
        {
            "name": "grape",
            "price": 200
        }
    ]
}
```

How to assert that `{"name": "apple", "price": 100}` is in collection? For now what I can do is that

```
jsonpath "$.fruit[*].name" includes "apple"
jsonpath "$.fruit[*].price" includes 100
```

But this is not the exact assertion I want. It checks these two values separately.

Seems that the keyword `includes` only supports literal value? Can we extend it to json object? Just like

```
jsonpath "$.fruit[*]" includes '{"name": "apple", "price": 100}'
```

**Comment by fabricereix** [comment]
Hi @fjchen7,

You're right, currently `includes` (all other predicates) only support scalar literal values. List and Object are not supported.
If these one are parseable without ambiguities, it might indeed be a good idea to support it. We are going to look into it.


Note that you can for the time-being use the following xpath asserts in order to be more specific:
```
jsonpath "$.fruit[?(@.name=='apple')].price" == 100
jsonpath "$.fruit[?(@.name=='grape')].price" == 200
```

But I agree that yours would be more readable
```
jsonpath "$.fruit[*]" includes {"name": "apple", "price": 100}
jsonpath "$.fruit[*]" includes {"name": "grape", "price": 200}
```

**Comment by fjchen7** [comment]
Great. Thanks @fabricereix, your answer could meet most of my requirement.

BTW, can I filter nested element?

```json
{
    "fruit": [
        {
            "name": "apple",
            "price": {
                "US": 100,
                "UN": 110
            }
        },
        {
            "name": "grape",
            "price": {
                "US": 200,
                "UN": 150
            }
        }
    ]
}
```

I tried with this
```
jsonpath "$.fruit[?(@.name.US==200)].name == "grape"
```
But it returns `is not valid`.

**Comment by fabricereix** [comment]
I don't think this is a valid jsonpath expression.

You can always quickly check with http://jsonpath.com/.
It also does not return anything.

**Comment by fjchen7** [comment]
Great project and we are ready to use it for production test. Thanks for help!

**Comment by fjchen7** [comment]
Sorry my mistake. I gave a wrong jsonpath expression in [my last reply](https://github.com/Orange-OpenSource/hurl/issues/420#issuecomment-996577740).

Actually the expression `$.fruit[?(@.price.US==200)].name` can filter out value in http://jsonpath.com.

![image](https://user-images.githubusercontent.com/10106636/146631117-e38dd246-f411-4e7a-a41d-c5559b42ff8b.png)

However in `hurl` the same expression can not work.

![image](https://user-images.githubusercontent.com/10106636/146631152-c589efb9-6f48-448e-8d54-d60ee83809c6.png)

`hurl` can not support full jsonpath?

**Comment by fabricereix** [comment]
The original "spec" https://goessner.net/articles/JsonPath/ is still the one we refer to to, but it is not very detailed.
Every implementation adds its own features, which are not described in this spec. For example, your filter with a nested object is one of them.

We also add these extra features when they make sense and often they are also implemented in http://jsonpath.com.
This one is indeed a good candidate. We can try to support it for the next release (#423)

**Comment by fabricereix** [comment]
@fjchen7, the support for nested object has now been merged into master.
you can get the hurl binary from https://github.com/Orange-OpenSource/hurl/actions/runs/1603719015#artifacts if you need this feature before the next release (probably end of january).
Thanks for your feedback.

**Comment by fjchen7** [comment]
Amazing. You guys are very productive. Very appreciate it!
