### ISSUE TITLE
MultipartFormData section doesn't accept some key-value pair

### ISSUE THREAD

**Issue by linjan** [Orange-OpenSource/hurl#457]
Hello,

Params in [Multipart Form Data](https://hurl.dev/docs/request.html#multipart-form-data) according to grammar of Hurl accepts key-value, with key-string in it, accepting `= <(alphanum | "_" | "-" | "." | escape-char)+ >`
By the way, there are cases, where key-string must contain brackets, like on the image:

![image](https://user-images.githubusercontent.com/5128657/150809463-1e5e1414-60dd-41bf-a6ee-c199a57cdd04.png)

I tried several ways to encode (\u005b\u005d), escape (\\) characters, but no result.
So for instance, '[]' (ascii square brackets or box brackets) should be accepted by Hurl.

The following Hurl file should be valid:
```
POST http://test.stand/upload
# Content-Type: multipart/form-data; charset=utf-8
[MultipartFormData]
authenticity_token: abcdef0123456789
package[sender_type]: Other;
package[package]: file,request.zip; application/zip

```
Actually, Hurl raises an error:
```
❯ hurl -x http://test.stand/upload request.hurl
error: Parsing Method
  --> request.hurl:69:1
   |
69 | package[sender_type]: Other;
   | ^ The HTTP method is not valid. Available HTTP Methods are GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE or PATCH
   |
```

**Comment by fabricereix** [comment]
Hi @linjan,
Thanks for your detailed explanations.
You're right, Hurl should accept square bracket in key string.
We will add it for the next release.

**Comment by fabricereix** [comment]
Escaping can work as follows:
`package[sender_type]: Other`  
written in the Hurl file as:
`package\u{5b}sender_type\u{5d}: Other`

**Comment by fabricereix** [comment]
We might add the reasonable restriction that the key-string does not start with a '['.
So that there is no ambiguities in the parsing with the section name.

For example
```
[FormParams]
x[Cookies] # parsed as a form param
[Cookies]  # parsed as Cookie section
[xxx]      # parsing error - invalid section name
```
