### ISSUE TITLE
Templates in File Uploads

### ISSUE THREAD

**Issue by nikeee** [Orange-OpenSource/hurl#464]
I'm trying to create a file upload script that uses hurl. I've got this script (made executable with `chmod +x`):
```hurl
#!/usr/bin/hurl
# pass:
# --variable file=/path/to/file

POST https://example.net/api/upload
Cookie: <....>

[MultipartFormData]
file: file,{{file}}; image/png
```

Invoking it yields the following error:
```sh
./upload.hurl --variable file=./test.txt
error: Parsing Filename
  --> ./upload.hurl:9:12
   |
 9 | file: file,{{file}}; image/png
   |            ^ expecting a filename
   |
```
The same error also happens when invoked with `hurl --variable file=./test.txt upload.hurl`. It seems that the template variable is not resolved in this place.

**Comment by fabricereix** [comment]
Hi @nikeee 
You're right. Template are not supported in filename.
This is indeed a good feature to have.
We  will add in the next release.

**Comment by nikeee** [comment]
Great!

Is it somehow possible to derive the mime type from that provided file name?

**Comment by jcamiel** [comment]
Yes, from the docs on [Multipart Form Data](https://hurl.dev/docs/request.html#multipart-form-data), you can omit mime type for the most common extensions:

> Content type can be specified or inferred based on the filename extension:
>
> - .gif: image/gif,
> - .jpg: image/jpeg,
> - .jpeg: image/jpeg,
> - .png: image/png,
> - .svg: image/svg+xml,
> - .txt: text/plain,
> - .htm: text/html,
> - .html: text/html,
> - .pdf: application/pdf,
> - .xml: application/xml
>
> By default, content type is application/octet-stream.

This is the same behaviour as curl!
