### ISSUE TITLE
Feature Request: Inject variables from file

### ISSUE THREAD

**Issue by s4ik4t** [Orange-OpenSource/hurl#465]
Great project, thanks `Hurl`ers!

Right now there is an option to inject multiple variables from the command line. Could we also support reading multiple variables from another file?

For e.g. `hurl --variable a_string=apple --variable a_bool=true --variable test.hurl` → `hurl --variables dev.txt test.hurl` or `hurl --environment dev.txt test.hurl`.

**Comment by fabricereix** [comment]
Hello, yes we have that https://hurl.dev/docs/man-page.html#variables-file
```
hurl --variable-file dev.txt test.hurl
```

**Comment by s4ik4t** [comment]
Sorry didn't notice that. Many thanks @fabricereix 👍🏼
