### ISSUE TITLE
Support pipe character ('|') in Cookies section

### ISSUE THREAD

**Issue by adworacz** [Orange-OpenSource/hurl#466]
The following file fails to run with hurl:

```
GET https://example.com
[Cookies]
foobar: asdf|1234
```

Output:
```sh
hurl test.hurl
error: Parsing literal
  --> test.hurl:4:13
   |
 4 | foobar: asdf|1234
   |             ^ expecting 'line_terminator'
```

This might effect other sections as well, but I just ran into it with the Cookies section.

**Comment by fabricereix** [comment]
Thanks for reporting it.
We will fix it for the next release.
