### ISSUE TITLE
Assert fails only if last request int the single hurl file doesn't match

### ISSUE THREAD

**Issue by ivansumak** [Orange-OpenSource/hurl#489]
Trying to test multiple paths in the same hurl file, but it fails only if last request doesn't match the assertion.

Example:  

SUCCEEDS:
```
GET http://{{host}}:8080/tests
GET http://{{host}}:8080/nema
GET http://{{host}}:8080/api/v4/dr/pull
GET http://{{host}}:8080/nema

HTTP/1.1 200
[Asserts]
jsonpath "$.headers.TestBackendName" == "test-1"
```

FAILS: 
```
GET http://{{host}}:8080/tests
GET http://{{host}}:8080/nema
GET http://{{host}}:8080/api/v4/dr/pull

HTTP/1.1 200
[Asserts]
jsonpath "$.headers.TestBackendName" == "test-1"
```

`GET http://{{host}}:8080/api/v4/dr/pull` doesn't match assertion but if it's not on the last line in the hurl file - test is successful.
`GET http://{{host}}:8080/nema` matches the assertion and test is successful regardless of the the fact that previous request doesn't . 

I think test should fail if assertion is not met for any of the requests in the hurl file. 

hurl version: `hurl 1.5.0 libcurl/7.80.0-DEV OpenSSL/1.1.1l zlib/1.2.11`

Is this behavior expected?

**Comment by jcamiel** [comment]
Hi @ivansumak, the assertions sections is optional and test the _associated_ request.

With your first example:

```hurl
GET http://{{host}}:8080/tests
GET http://{{host}}:8080/nema
GET http://{{host}}:8080/api/v4/dr/pull
GET http://{{host}}:8080/nema

HTTP/1.1 200
[Asserts]
jsonpath "$.headers.TestBackendName" == "test-1"
```

Can be summarised:
```
REQUEST-1
REQUEST-2
REQUEST-3
REQUEST-4
RESPONSE-4
```

The second example is
```
REQUEST-1
REQUEST-2
REQUEST-3
RESPONSE-3
```

The Hurl file format describe a list of[ _entry_](https://hurl.dev/docs/entry.html): each entry being a mandatory request and an optional response that can have multiple asserts.

I hope that it is ok with your workflow!

Regards,

**Comment by ivansumak** [comment]
It's not ideal but I can work around it. Thanks for your response!
