### ISSUE TITLE
Unable to use JSON RPC

### ISSUE THREAD

**Issue by Karrq** [Orange-OpenSource/hurl#495]
Hi, I was interested in trying this tool to make a series of requests easily reproducible or parametrized but I was stuck immediately when attempting to make a json rpc request.

Here's the sample:
```
POST https://rpc.flashbots.net/
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": ["0x5E3A3F", true]
}
```

When running with `hurl file.hurl` I get the following error:
```
error: Parsing json
  --> file.hurl:6:14
   |
 6 |     "params": ["0x5E3A3F", true]
   |              ^ json error
   |
   ``` 
   
   But I tried to verify this payload and had no issue with it, even using it in postman without any trouble... Am I missing something here?

**Comment by fabricereix** [comment]
Hello @Karrq,
For JSON parsing, we have added the check that all items in an array should have the same type.
Can you use this payload instead?
```
POST https://rpc.flashbots.net/
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": ["0x5E3A3F", "true"]
}
```

We need to check if this extra restriction is common and really makes sense. If not we will remove it.

**Comment by fabricereix** [comment]
It seems indeed that each element in an array may be of a different type.
A unique type can be enforced with a JSON schema validation.
Thanks for reporting it, we will remove this restriction in the next release.

**Comment by Karrq** [comment]
Hi, thanks for the quick response.

I tried running the payload as you suggested (btw the rpc endpoint I
provided is public), and I got an error _as a response_.

`{"id":1,"error":{"code":-32602,"message":"invalid argument 1: json: cannot
unmarshal string into Go value of type bool"},"jsonrpc":"2.0"}`

EDIT:
While writing this response I saw you verified that elements in JSON arrays
can be of different types.
I'm surprised no other users found this before!

May I sneak in a feature request? Some kind of interface in hurl for
JSON-RPC?

Il giorno sab 5 mar 2022 alle ore 15:44 Fabrice Reix <
***@***.***> ha scritto:

**Comment by fabricereix** [comment]
Until the next release, you can send your exact payload with a mutiline string

    POST https://rpc.flashbots.net/
    ```
    {
        "id": 1,
        "jsonrpc": "2.0",
        "method": "eth_getBlockByNumber",
        "params": ["0x5E3A3F", true]
    }
    ```

The JSON won't be decoded by Hurl.

I'm not familiar with JSON-RPC. What kind of feature would you like?

**Comment by fabricereix** [comment]
Hi @Karrq,
I'm closing the issue, The fix has been merged in #496

**Comment by huangjj27** [comment]
If I need to check the types of the elements in an array are the same, how do I do this?

**Comment by jcamiel** [comment]
Hi, you can use `isInteger` `isFloat` `isString` `isCollection` predicates and explicitely asserts all items:

```hurl
GET http://api.foo.com

HTTP/* 200
[Asserts]
jsonpath "$.books[0]" isString
jsonpath "$.books[1]" isString
jsonpath "$.books[2]" isString
```

We'll improve this with in a future version an `any`, `all` `none` keywords, 

https://hurl.dev/docs/asserting-response.html#predicates

**Comment by huangjj27** [comment]
> Hi, you can use isInteger isFloat isString isCollection predicates and explicitely asserts all items:

But in the practical sence, the elements in an array usually are complex structures of the same type. It's hard to predict in such sence.

**Comment by fabricereix** [comment]
you might probably be happy a schema validation (https://github.com/Orange-OpenSource/hurl/issues/543)
