### ISSUE TITLE
[BasicAuth] with @ in username gives "error: Parsing json"

### ISSUE THREAD

**Issue by humphd** [Orange-OpenSource/hurl#513]
Given the following `.hurl` file:

```
POST http://localhost:8080/
[BasicAuth]
user1@email.com: password1
```

Running this produces the following error:

```sh
$ hurl --test tests/integration/auth.hurl
expr=tests/integration/auth.hurl
tests/integration/post-fragments.hurl: RUNNING [1/1]
error: Parsing json
  --> tests/integration/auth.hurl:7:2
   |
 7 | [BasicAuth]
   |  ^ json error
   |
```

Removing the `@` works.  This is surprising (to me).  Is there someway to handle this case without having to produce the `Authorization` header manually?  I really like the expressiveness of having the username/password **in** the test case, since it's part of the test.

**Comment by fabricereix** [comment]
Thanks @humphd for reporting this bug.
We will fix it in the 1.6.1 patch version by the end of the week.
