### ISSUE TITLE
Incomplete escaping of shell arguments

### ISSUE THREAD

**Issue by kautsig** [Orange-OpenSource/hurl#530]
The method responsible for escaping shell arguments does not consider backslashes as part of the string to encode.

This is the method:
```
fn encode_value(s: String) -> String {
    if s.contains('\'') {
        let s = escape_single_quote(s);
        format!("$'{}'", s)
    } else {
        format!("'{}'", s)
    }
}
```
https://github.com/Orange-OpenSource/hurl/blob/4371484fe408bc0dcd1af9c101decde749c3e2a0/packages/hurl/src/http/request_spec.rs#L313

Now assume the input is `foo\`.

Then the output will be `'foo\'` which escapes the closing `'` causing breakage.

**Comment by fabricereix** [comment]
Thanks @kautsig for reporting, we will try to add a test for that input and fix it in the next release.

**Comment by kautsig** [comment]
I managed to put together a simple testcase, so I can provide some more details. My initial finding might not be the root cause.

My problem was that my json field payload contained `'` and '\' which seemed to cause 2 problems.

Assume following files, `test.hurl`:
```
POST http://localhost:8000/
{
    "key": "{{ variable }}"
}
```
Run hurl:
```
hurl -k -v test.hurl --variable "variable=val'ue\\"
```

The variable value reported is what I'd expect:
```
* variables:
*     variable=val'ue\
```

**Problem 1:** The curl command written out is clearly off, `'` is not escaped.
```
* request can be run with the following curl command:
* curl 'http://localhost:8000/' -H 'Content-Type: application/json' --data $'{\n    "key": "val'ue\\"\n}' --insecure
```

**Problem 2:** The json payload sent to the server breaks as well:
```
{
    "key": "val'ue\"
}
```

**Comment by fabricereix** [comment]
Thanks for this clear testcase.
I agree for the problem1 but maybe not for the problem2.

It might be "normal" to fail in this case.

The JSON defined in a Hurl file must be valid and sent as such.
Hurl should not apply any encoding.

Posting the following Hurl with variable set to `val'ue\`
```
POST http://localhost:8000/
{
    "key": "{{ variable }}"
}
```

is really equivalent to Posting
```
POST http://localhost:8000/
{
    "key": "val'ue\"
}
```

The variable needs to be set with the encoded value `val\'ue\\` 
which will be evaluated at runtime as
```
POST http://localhost:8000/
{
    "key": "val\'ue\\"
}
```

**Comment by kautsig** [comment]
Thanks for your quick response!

My opinion on problem 2 would be that the user should not need any knowledge about the context a variable is used in when defining its value to take care of escaping.

It would be preferable if escaping could be done where the variable is used, e.g.:
 
```
POST http://localhost:8000/
{
    "key": "{{ variable | escapeJsonString }}"
}
```
This would be a feature though, not a bugfix, since the current behavior is expected.

**Comment by fabricereix** [comment]
We'd like to add small transformation functions like this one,
for example
```
GET https://example.org/account
Authorization: Basic {{'bob:secret' | base64}}
HTTP/1.1 200
```

I don't know if this one is too specific but it fits well with the philosophy of Hurl.

To post a JSON, we can also use
```
POST http://localhost:8000/
{
    "key": {{ variable }}
}
```
The variable can be a boolean, a number or a string.
In this case, for a String variable it would probably makes sense to encode it automatically.

**Comment by fabricereix** [comment]
After discussion, we'd like to follow your initial suggestion.
Every string variable evaluated in a JSON body should be encoded by Hurl.
Is is indeed more intuitive/natural for a user.

If a user does not want to have it encoded, he can use the multiline string instead.
Thanks a lot for your remarks!
