### ISSUE TITLE
Make hurl installable via npm

### ISSUE THREAD

**Issue by humphd** [Orange-OpenSource/hurl#544]
Spin-off from https://github.com/Orange-OpenSource/hurl/issues/284#issuecomment-1109820307, it would be great if hurl could be installed via `npm` similar to what [`dprint` does](https://www.npmjs.com/package/dprint), see https://github.com/dprint/dprint/tree/main/deployment/npm.  This way, node/JS devs can use hurl as part of their normal workflows.

**Comment by humphd** [comment]
Prior art:

- Issue: https://github.com/dprint/dprint/issues/352
- PR: https://github.com/dprint/dprint/pull/358

**Comment by jcamiel** [comment]
@humphd I've a first draft ready to test, would it be possible to test it on your side ? I'm not very confident with my current npm knowledge. I've test this Pr on my Mac, and I need to test it on Windows.
For the moment you can :

```
$ git clone --branch feature/add-npm-install https://github.com/Orange-OpenSource/hurl.git
$ cd hurl/contrib/npm
