### ISSUE TITLE
Setting Scheme and Host in headers?

### ISSUE THREAD

**Issue by huangjj27** [Orange-OpenSource/hurl#547]
I'm using hurl as RESTful API specification, so I prefer a format that only the API path after the HTTP action, while the scheme and the host are defined in a `Scheme` and a `Host` header:

```hurl
# token.hurl
POST /tokens
Scheme: {{SCHEME}}
Host: {{HOST}}
```

But when I run this example with the command `hurl tokens.hurl --variables-file=test.env`, I get this error:

```sh
> hurl tokens.hurl --variables-file=test.env
error: Http Connection
  --> tokens.hurl:8:6
   |
 8 | POST /tokens
   |      ^^^^^^^ (3) URL using bad/illegal format or missing URL
   |
```

And I expect the example should work, but it seems this doesn't work now. Therefore, I'm here to request new feature support. Any advice?

**Comment by jcamiel** [comment]
Hi,

Using url without scheme (http/https) and host looks really like HTTP so it' interesting. But how would you tell if the protocol is HTTP or HTTPS? Choosing one by default seems arbitrary...

For the moment, you can, of course, templatize the url:

ˋˋˋ
POST https://{{host}}/tokens
ˋˋˋ

**Comment by huangjj27** [comment]
> Using url without scheme (http/https) and host looks really like HTTP so it' interesting

Oh，Indeed that variable "{{host}}" means "{{scheme_and_host}}", so that I could use HTTP for test environment and HTTPS for production.

**Comment by huangjj27** [comment]
I find some interesting request from firefox, that some request is using a `Scheme` header to identify the request scheme, It this part of the HTTP protocol standard?

**Comment by huangjj27** [comment]
The original post is edited.

**Comment by jcamiel** [comment]
I'm not at all a HTTP spec expert but I don't see the Scheme header often. It's not referenced in RFC2616 nor in  <https://en.wikipedia.org/wiki/List_of_HTTP_header_fields>. As it is not "well known", I'm a bit reluctant to add this kind of syntax:

```
POST /path
Host: example.com
Scheme: https
```

**Comment by huangjj27** [comment]
> It's not referenced in RFC2616 nor in https://en.wikipedia.org/wiki/List_of_HTTP_header_fields.

ok, since `Scheme` is not a standard header, we should not parse it as a header.

**Comment by louy2** [comment]
I really like this idea of making the request line more like actual HTTP request.

> how would you tell if the protocol is HTTP or HTTPS?

When a URL has no protocol, curl follows the option `--proto-default`, or in its absence guesses the protocol based on the hostname. You can also specify `--ssl-reqd` to force TLS upgrade.
