### ISSUE TITLE
Support wildcard value in implicit status code reponse

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#55]
Wildcard `*` can be used in HTTP version to disable any check on the HTTP version:

```
GET http://localhost:8000/timeout
HTTP/* 200
```

It could be useful to also support wildcard for status code.
For instance:

```
GET http://localhost:8000/timeout
HTTP/* *
[Asserts]
status not equals 200
```

Status code is explicitly tested not to be equals to 200

**Comment by fabricereix** [comment]
implemented in #68
