### ISSUE TITLE
Ordering of headers vs [BasicAuth] causes confusing error

### ISSUE THREAD

**Issue by humphd** [Orange-OpenSource/hurl#572]
Running hurl 1.6.1, I think the parser is getting confused, or at least I'm confused.  The order of headers vs the `[BasicAuth]` block leads to a parsing error.  To me, this is not intuitive, since I think of `[BasicAuth] ...` and `Authorization ...` as doing something similar.

Consider:

## Working

```
POST https://www.toptal.com/developers/postbin/1652367019243-4803056719247
Content-Type: application/json; charset=utf-8
[BasicAuth]
bob:secret
```{"hello": "world"}```

$ hurl --test test.hurl
test.hurl: RUNNING [1/1]
test.hurl: SUCCESS
--------------------------------------------------------------------------------
Executed:  1
Succeeded: 1 (100.0%)
Failed:    0 (0.0%)
Duration:  116ms
```

## Failing

NOTE: the change in order of `Content-Type` and `[BasicAuth]`:

```
POST https://www.toptal.com/developers/postbin/1652367019243-4803056719247
[BasicAuth]
bob:secret
Content-Type: application/json; charset=utf-8
```{"hello": "world"}```

❯ hurl --test test.hurl
test.hurl: RUNNING [1/1]
error: Parsing Method
  --> test.hurl:4:1
   |
 4 | Content-Type: application/json; charset=utf-8
   | ^ The HTTP method is not valid. Available HTTP Methods are GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE or PATCH
   |
```

Compare to this, which also works:

```
POST https://www.toptal.com/developers/postbin/1652367019243-4803056719247
Authorization: Basic Ym9iOnNlY3JldA==
Content-Type: application/json; charset=utf-8
```{"hello": "world"}```

$ hurl --test test.hurl
test.hurl: RUNNING [1/1]
test.hurl: SUCCESS
--------------------------------------------------------------------------------
Executed:  1
Succeeded: 1 (100.0%)
Failed:    0 (0.0%)
Duration:  116ms
```

Maybe there's a bug here, or maybe an opportunity to [add a bit more to the docs](https://hurl.dev/docs/request.html#basic-authentification)?

**Comment by fabricereix** [comment]
This might indeed be confusing with the implicit nature of Hurl.

An Hurl request is first made from
```
<Method> <Url>
<Headers>
<Sections>
<Body>
```

The sections are located between the headers and the body.
They are not really part of the request as such, they are used to generate content:
- url (`[QueryParams]`)
- header (`[Cookies]`, `[BasicAuth]`)
- body (`[FormParams]`) 

For sure, we can add more info to the doc.

**Comment by jcamiel** [comment]
@humphd I've created a PR on the docs, would you be kind to review it?
We can be add more explanation on this, I agree this can be confusing: https://github.com/Orange-OpenSource/hurl-dev/pull/54 

(note; I was not able to add you as a reviewer, I will try to do it)

**Comment by humphd** [comment]
> I've sent you an invitation so I can request a review to you, feel free to accept it or not accept it !!

Happy to be part of the action!  I'll review.

**Comment by jcamiel** [comment]
Closing this one, I've updated [the doc](https://hurl.dev/docs/request.html) with explanations and a schema (see <https://hurl.dev/docs/request.html#structure>) to explicit the file format structure.
