### ISSUE TITLE
Generate curl command(s) from Hurl file

### ISSUE THREAD

**Issue by lithammer** [Orange-OpenSource/hurl#581]
Basically the opposite of https://github.com/Orange-OpenSource/hurl/issues/316. Given a Hurl file, I would like to be able to generate curl command(s).

I realise it might be a bit tricky because of templating. But maybe those can just be left as-is or translated into shell variables (e.g. `{{foo}}` → `$foo`).

**Comment by fabricereix** [comment]
Hello @lithammer,
Generating curl commands simply from a Hurl file might not be easy/possible.
`curl` is request-based whereas `Hurl` is session-based, with possible captures between requests.

But from a given run, it is possible to output the equivalent curl command for each request.
That 's what Hurl is doing in verbose mode.

**Comment by lithammer** [comment]
> Hello @lithammer, Generating curl commands simply from a Hurl file might not be easy/possible. `curl` is request-based whereas `Hurl` is session-based, with possible captures between requests.

Suspected as much.

> But from a given run, it is possible to output the equivalent curl command for each request. That 's what Hurl is doing in verbose mode.

I hadn't noticed that. I think that actually satisfies my needs of "give a curl command to a colleague that's not using hurl" or "paste example request into documentation".

Thanks!
