### ISSUE TITLE
Create PR dependency-update (toml+lock)

### ISSUE THREAD

**Issue by fabricereix** [Orange-OpenSource/hurl#583]
Run automatically:
```
- dependency_age --upgrade
- cargo update
```

If `Cargo.toml/Cargo.look` have been modified, a PR will be created.

The job will be run on a daily basis,
if a dependencies PR is already open, this one will be updated.

**Comment by lepapareil** [comment]
Rewrite dependency_age.sh to crates_update.sh done by 0a552d7275999a41bef3e74d150516fe049678bf
