### ISSUE TITLE
--include options print only last entry headers or all ?

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#59]
`--include` options seems to print only the last entry headers.

Should it print all the entry headers or only the last entry ones ? In any case, man/documentation should explicit what it does.

**Comment by fabricereix** [comment]
-i, --include       Include protocol headers in the output 

It should have the same behaviour that the output, namely:
1. for the last entry
2. use standard output (currently it use standard error, it should be fixed)

The man can be updated as follow
-i, --include       Include protocol headers in the output (last entry only)

**Comment by fabricereix** [comment]
Fix include headers to standard output #72
