### ISSUE TITLE
variable as cookie

### ISSUE THREAD

**Issue by bschwehn** [Orange-OpenSource/hurl#597]
I'm trying to set a cookie value from a variable like:
```
GET {{base}}/api
[Cookies]
auth: {{cookie}}
```
but get the error

```
 3 | auth: {{cookie}}
   |       ^ expecting 'line_terminator'
   |
```

Am I doing it wrong or is using variables not supported for cookies?

**Comment by fabricereix** [comment]
Hello, 
Variables are not yet supported in the cookie value. This seems indeed like a missing feature.
We will try to support it in the next release.

For the time-being, you can use the `Cookie` header.
```
GET {{base}}/api
Cookie: auth={{cookie}}
```

**Comment by bschwehn** [comment]
Oh, I didn't think of this to be honest, that works well, thank you!
