### ISSUE TITLE
Hurl "Host" request header with port 8000

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#6]
When performing a GET on localhost:8000, Hurl set the `Host`request header to `localhost` whereas curl set this header to `localhost:8000`.
Hurl should be aligned with curl and set the `Host` header to `localhost:8000`.

There is an integration test on the subject:

https://github.com/Orange-OpenSource/hurl/blob/3d2d9e3215674909edd6ba7d03c87fd44ae0fd18/integration/tests/headers.py#L9

**Comment by fabricereix** [comment]
this is fixed by https://github.com/Orange-OpenSource/hurl/pull/21
