### ISSUE TITLE
how can veiw log for all reposone on output

### ISSUE THREAD

**Issue by hemedani** [Orange-OpenSource/hurl#600]
you say that in documentation 
```
By default, Hurl executes all HTTP requests and outputs the response body of the last HTTP call.
````

but I want to output all req responses in the terminal.

and it's great if we can add some extra custom log for every req output.

something like this 
```
[LogStart] getting all questions... [LogEnd]
GET http://localhost:8080/api/questions

[LogStart] requesting 404 page [LogEnd]
GET http://localhost:8080/not-found
```

and get this output on the shell :
```shell
$ hurl basic.hurl
getting all questions...
[{"id":"c0d80047-4fbe-4d45-a005-91b5c7018b34","created":"1995-12-17T03:24:00Z"....
-----------------------------

requesting 404 page
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/style.css">
    <!--<script src="script.js"></script>-->
</head>
<body>
<div>
    <img class="logo" src="/quiz.svg" alt="Quiz logo">
</div>
<h1>Error 404, Page not Found!</h1>

<a href="/">Quiz Home</a>


</body>
</html>
```

**Comment by jcamiel** [comment]
Yes, actually you can use:

-  [`--verbose` option](https://hurl.dev/docs/man-page.html#verbose) option to add additional log (HTTP request and response headers, captures etc). The log looks like hurl with lines starting with `>` for request headers, `<`for response headers and `*` in other cases,
- [`--json` option](https://hurl.dev/docs/man-page.html#json) to output a Hurl run to stdout in JSON  format (response body is not included)
- wait for the [`--very-verbose` PR](https://github.com/Orange-OpenSource/hurl/issues/499): in this PR we will log additional info for __each request / response__ of a Hurl file. This PR should land in the next Hurl version (1.7.0),
