### ISSUE TITLE
Create [Options] section to use command line option per request

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#612]
In 1.6.1, Hurl has command line options that affect a whole file (i.e each entry of a test).

For instance, [`--insecure`](https://hurl.dev/docs/man-page.html#insecure) allows to by-pass certificate verification on all entries of a file.

We could add an `[Options]` section that will allow to set option per request. 

For instance:

```hurl
GET https://trusty.net
[Options]
insecure: true

HTTP/* 200


GET https://not-trusty.net

HTTP/* 200
```

Will by-pass certificate verification on <https://trusty.net> and will verify certificate on <https://not-trusty.net>.

We could expose all the relevant options (excluding those which are not, like [`--color`](https://hurl.dev/docs/man-page.html#color)).

The supported options could be:

```hurl
GET https://example.org
[Options]
cacert: tmp/certificates/my-cert.cer
compressed: true
connect-timeout: 60
cookie: tmp/cookie-in.txt
cookie-jar: tmp/cookie-out.txt
file-root: /users/bob/tmp
location: true
include: true
insecure: true
ignore-asserts: true
max-redirs: 20
max-time: 30
proxy: localhost:8888
verbose: true

HTTP/* 200
```

Options that can already be defined per-request should not be included. For instance [--user](https://hurl.dev/docs/man-page.html#user) add basic authentifciation to each request.
As there is a `[BasicAuth]` section wich allows set basic authentification on a request, we don't need to support `user` in `[Options]`.

Options excluded because there are not relevant per-request:

- [`--color`](https://hurl.dev/docs/man-page.html#color)
- [`--fail-at-end`](https://hurl.dev/docs/man-page.html#fail-at-end)
- [`--glob`](https://hurl.dev/docs/man-page.html#glob)
- [`--interactive`](https://hurl.dev/docs/man-page.html#interactive)
- [`--json`](https://hurl.dev/docs/man-page.html#json)
- [`--no-color`](https://hurl.dev/docs/man-page.html#no-color)
- [`--no-output`](https://hurl.dev/docs/man-page.html#no-output)
- [`--noproxy`](https://hurl.dev/docs/man-page.html#noproxy)
- [`--output`](https://hurl.dev/docs/man-page.html#output)
- [`--progress`](https://hurl.dev/docs/man-page.html#progress)
- [`--report-junit`](https://hurl.dev/docs/man-page.html#report-junit)
- [`--report-html`](https://hurl.dev/docs/man-page.html#report-html)
- [`--test`](https://hurl.dev/docs/man-page.html#test)
- [`--to-entry`](https://hurl.dev/docs/man-page.html#to-entry)
- [`--to-entry`](https://hurl.dev/docs/man-page.html#to-entry)
- [`--variable`](https://hurl.dev/docs/man-page.html#variable)
- [`--variables-file`](https://hurl.dev/docs/man-page.html#variables-file)
- [`--help`](https://hurl.dev/docs/man-page.html#help)
- [`--version`](https://hurl.dev/docs/man-page.html#version)

**Comment by fabricereix** [comment]
This feature is very useful.
It could also set explicitly variables in a Hurl file (https://github.com/Orange-OpenSource/hurl/issues/533)
```
[Options]
variable: name=toto
```

**Comment by fourjay** [comment]
This is listed as added to the 1.7 release (yay)
But when trying it out I get
``` | [Options]                                                                                                                                                                                         
 |  ^ the section is not valid. Valid values are Captures or Asserts ```
 
 I'm using the release file for x86-64-linux
 hurl-1.7.0-x86_64-linux.tar.gz

**Comment by fourjay** [comment]
Placement was the issue :-) 
I'd placed the ```[Options]`` section after the ```HTTP/1.1```

**Comment by jcamiel** [comment]
Thanks for the feedback, always happy to hear how Hurl is used in the wild!

**Comment by alturkovic** [comment]
> Hi @fourjay can you provide your Hurl file ? We're updating the docs on https://hurl.dev for the 1.7.0. But, just for your information, the `[Options]` sections are relative to a request, for instance:
> 
> ```
> GET https://foo.com
> [Options]
> insecure: true
> variable: host=toot.com
> HTTP/*
> 
> # Another request without options
> GET http//bar.com
> ```
> 
> For the moment, you can not use the `[Options]` sections at the file level without any request. We're going to add it soon. So this Hurl file is not valid:
> 
> ```
> # Options for the whole file
> [Options]
> variable: host:sample.com
> 
> GET https://{{host}}
> HTTP/*
> ```
> 
> But it'll be soon !

Sorry to comment on an old issue, but this is the only place I found the mention of global `[Options]` which sounds super useful to set input variables and it was mentioned here that it will be supported. Is this still planned? Should I open a feature request for this?

**Comment by jcamiel** [comment]
Hi @alturkovic this feature is still planned, sure you can open a specific issue on it so we don't forget it!
