### ISSUE TITLE
make http header content-type charset processing case-insensitive in hurl

### ISSUE THREAD

**Issue by coopertinoUK** [Orange-OpenSource/hurl#639]
According to information found here 
https://stackoverflow.com/questions/19391221/are-character-set-names-case-sensitive-in-http
HTTP character sets are identified by case-insensitive tokens.

hurl expects lowercase charset and currently complains when it receives server response with http header
`Content-Type: text/plain; charset=UTF-8;`
displaying
`error: Invalid Charset` 

would it make sense to apply the following patch? (or sth similar, I don't know Rust language yet)
<div><code><pre>
diff --git a/packages/hurl/src/http/response_decoding.rs b/packages/hurl/src/http/response_decoding.rs
index 25dd166..498c4bc 100644
--- a/packages/hurl/src/http/response_decoding.rs
+++ b/packages/hurl/src/http/response_decoding.rs
@@ -73,7 +73,8 @@ impl Response {
         match self.content_type() {
             Some(content_type) => match mime_charset(content_type) {
                 Some(charset) => {
-                    match encoding::label::encoding_from_whatwg_label(charset.as_str()) {
+                    let c = charset.as_str().to_ascii_lowercase();
+                    match encoding::label::encoding_from_whatwg_label(&c) {
                         None => Err(HttpError::InvalidCharset { charset }),
                         Some(enc) => Ok(enc),
                     }
                     </pre>
                     </code>
                     </div>

**Comment by fabricereix** [comment]
Thanks for your detailed explanation.
We will add a test and apply your patch for the next release.

**Comment by coopertinoUK** [comment]
Great, thanks!

**Comment by fabricereix** [comment]
Hi @coopertinoUK 
it seems that Hurl already supports the charset in upper case (https://github.com/Orange-OpenSource/hurl/pull/658).
What is your full error message? the error might comes from the trailing `;`.

with a response header like yours `Content-Type: text/html; charset=UTF-8;`, I get the following error message:
```
error: Invalid Charset
  --> tests_failed/invalid_charset.hurl:5:1
   |
 5 | ```<p>Hello World!</p>```
   | ^ The charset 'UTF-8;' is not valid
   |
```
