### ISSUE TITLE
Explain --json, --append --html interaction

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#64]
Let's say we have file1.hurl, file2.hurl file3.hurl.

To get a json view of all files:

```
hurl --json /tmp/files.json file1.hurl file2.hurl file3.hurl
```
=> /tmp/files.json does represent the 3 files

```
hurl --json /tmp/files.json --append file1.hurl
hurl --json /tmp/files.json --append file2.hurl
hurl --json /tmp/files.json --append file3.hurl
```
=> /tmp/files.json does represent the 3 files

To get a html view of all files:

```
hurl --html /tmp/ file1.hurl file2.hurl file3.hurl
```
=> /tmp/*.html does represent the 3 files

```
hurl --json /tmp/files.json --append --html /tmp/ file1.hurl
hurl --json /tmp/files.json --append --html /tmp/ file2.hurl
hurl --json /tmp/files.json --append --html /tmp/ file3.hurl
```
=> /tmp/*.html does represent the 3 files

**Comment by fabricereix** [comment]
Simplify usage in #77 
(overwrite html files if they exist)
