### ISSUE TITLE
arbitary file uploads

### ISSUE THREAD

**Issue by datamuc** [Orange-OpenSource/hurl#674]
Hi,

the hurl version I'm running is:
```
 hurl 1.6.1 libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.3840 libidn2/2.3.0 libssh2/1.9.0 1.43.0
```
If I run the following hurl file:

```
PUT http://127.0.0.1:8000
file,../../../etc/shells;

HTTP/* 200
```

This is what the webserver receives:

```
PUT / HTTP/1.1
Host: 127.0.0.1:8000
Accept: */*
User-Agent: hurl/1.6.1
Content-Length: 130

# /etc/shells: valid login shells
/bin/sh
/bin/bash
/usr/bin/bash
/bin/rbash
/usr/bin/rbash
/bin/dash
/usr/bin/dash
/usr/bin/tmux
```

According to the documentatiohttps://github.com/Orange-OpenSource/hurl/issues/405n this should not happen I would say:

> Files are relative to the input Hurl file, and cannot contain implicit parent directory (..). You can use
[--file-root option](https://hurl.dev/docs/man-page.html#file-root) to specify the root directory of all file nodes.

I found #405 which was solved last december, so either the fix doesn't work or didn't made it into the current release. Well or something broke it again since then.

For Unix I think forbidding the path to start with `/`, `..` or containing `/..` should be enough. On Windows this is probably more complicated. If it's to much hassle, an option to disallow file access completely would also suit my needs, since people can just embed the body base64 encoded in the hurl file.

**Comment by jcamiel** [comment]
Yes, thanks for your report and you are totally right, we should have blocked this kind of file inclusion. The fix on https://github.com/Orange-OpenSource/hurl/blob/e278cf64d862dc22fafab5a120197c1d48531441/packages/hurl/src/runner/body.rs#L64 is visibly broken,  I will try to see what’s not working here.
