### ISSUE TITLE
Add --head option, similar to curl

### ISSUE THREAD

**Issue by kgrz** [Orange-OpenSource/hurl#700]
When making a curl request using the HEAD method, with the intent to only download headers and discard the body in responses, the `-X HEAD` does not work as intuited. If the server sends a body in the response for this method, curl *will* download the body.

Instead curl provides a `--head/-I` flag to put curl into a headers-only mode. This is useful when we only need to check headers, and has a side effect of speeding up the tests since it's less network data to download.

#698 was opened to add similar handling to hurl.

@jcamiel had this to say about that change (my responses included inline):

```

That said, could you give us your use case for a potential --head option?

Currently, you can have a Hurl file that do HEAD requests :

HEAD https://foo.org
HEAD https://bar.org
HEAD https://baz.com

Maybe you want to turn every method of an Hurl file to make HEAD request?

So this file:

GET https://foo.org
PUT https://bar.org
POST https://baz.com
when calling

$ hurl sample.hurl
will do a GET, then a PUT then a POST

and when calling with --head:

$ hurl --head sample.hurl
will do 3 HEAD requests.

```

In my mind only GETs would become HEAD, and rest of the methods will remain the same. Now I realise that I didn't actually handle this case.

I'll report back what curl does in each case.

```

In this case, we must also defines what happens to asserts and captures. Obviously, as there is no body response with a HEAD request, some asserts and captures will fail. For instance:

GET https://foo.com
HTTP/1.1 200
[Asserts]
jsonpath "$.id" == "baz"
will certainly fail.
```

I missed this bit too, and I'm now thinking the `jsonpath` asserts may be ignored for GET with an optional warning while running the file, and any header specific asserts be left as is.

**Comment by jcamiel** [comment]
Hi @kgrz, 

We have discussed a lot among the maintainers about this issue/PR and, for the moment, we don't think it goes went with the file format. It's rather convolulated to have explicit 'GET/POST etc.../' + asserts, and the `--head` option will bypass these. We don't feel at ease with disabling asserts when the options is used also. For the moment, we're not going to merge it. I understand that you have certainly a good use case for it, and all that you have spent time on the code, so I would like to apologise for not take it into account.
I hope you're ok with it and anyway don't hesitate to ask features you would like, 
Regards, 
Jc

**Comment by kgrz** [comment]
Thanks for considering this, and going through the effort to explain the decision, @jcamiel
