### ISSUE TITLE
Add coverage report to the pipeline

### ISSUE THREAD

**Issue by jcamiel** [Orange-OpenSource/hurl#746]
I think it would be a good idea to add coverage report and indicators to our pipeline.

I've followed this sources:
- <https://marco-c.github.io/2020/11/24/rust-source-based-code-coverage.html>  (courtesy to @marco-c)
- <https://doc.rust-lang.org/rustc/instrument-coverage.html>

An example of CI integration is here: <https://github.com/mozilla/grcov>

Basically:

1. `$ cargo install grcov`
2. `$ rustup component add llvm-tools-preview`
3. `$ cargo clean`
4. `export LLVM_PROFILE_FILE="your_name-%p-%m.profraw"`
5. instrument a debug build of hurl: `$ RUSTFLAGS="-C instrument-coverage" cargo build`
6. Run some test `$ target/debug/hurl integration/tests_ok/hello.hurl`
7. `grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o ./target/debug/coverage/`
8. open `./target/debug/coverage/`

Et voilà (run on hello.hurl)
<img width="1026" alt="coverage" src="https://user-images.githubusercontent.com/16323814/184006793-35cfe43d-c2c8-4e93-80ba-c6218ec6979b.png">

**Comment by lepapareil** [comment]
Done:

![coverage](https://user-images.githubusercontent.com/15672496/184247365-690b829c-99bc-4765-b3fc-3fbd0aa24fec.gif)

**Comment by jcamiel** [comment]
Super nice work !!!
Just wondering if we should run it only for integration tests (and not unit tests + integration tests) but it’s just a detail! Good job!

**Comment by lepapareil** [comment]
> Super nice work !!! Just wondering if we should run it only for integration tests (and not unit tests + integration tests) but it’s just a detail! Good job!

Feel free to update .github/workflows/coverage.yml as you need :)

**Comment by fabricereix** [comment]
We also need to exclude the test/ directories
