### ISSUE TITLE
Feature: --test report should show number of tests run in file

### ISSUE THREAD

**Issue by fourjay** [Orange-OpenSource/hurl#779]
Right now, running with the ``--test`` flag shows something like

```
hurl/facilities.hurl: RUNNING [1/1]
hurl/facilities.hurl: SUCCESS
--------------------------------------------------------------------------------
Executed:  1
Succeeded: 1 (100.0%)
Failed:    0 (0.0%)
Duration:  29ms
```
regardless of how many individual GET ... [Asserts] stanzas there are in the file.
This seems counter-intuitive.

**Comment by jcamiel** [comment]
Hi,
Thanks for the feedback. This is the same issue as #593, currently we’re associating « 1 test = 1 Hurl file » but maybe we can revise it. At least, be more descriptive in the summary like « number of files », « number of request »
