### ISSUE TITLE
hurl v1.7.0 is not published to crates.io

### ISSUE THREAD

**Issue by huangjj27** [Orange-OpenSource/hurl#832]
The latest version [here](https://crates.io/crates/hurl) is still v1.6.1

**Comment by fabricereix** [comment]
Indeed
I have tried to publish it but I get this javascript error when generating a new token in https://crates.io
```
Uncaught TypeError: l.randomUUID is not a function
    y chunk.ae3dbd3b1d7026c64c2c.js:2
    createIdentifierForNewRecord chunk.ae3dbd3b1d7026c64c2c.js:2
    _build chunk.ae3dbd3b1d7026c64c2c.js:2
    build chunk.ae3dbd3b1d7026c64c2c.js:2
    createRecord chunk.ae3dbd3b1d7026c64c2c.js:2
    _run loader.js:2
    _join loader.js:2
    join loader.js:2
    createRecord chunk.ae3dbd3b1d7026c64c2c.js:2
    _run loader.js:2
    _join loader.js:2
    join loader.js:2
    createRecord chunk.ae3dbd3b1d7026c64c2c.js:2
    startNewToken chunk.3dd9e7a061ae51fb5dc3.js:2
    s chunk.ae3dbd3b1d7026c64c2c.js:2
```

I've tried to 2 different browsers but I get the same error

**Comment by jcamiel** [comment]
@fabricereix maybe related https://github.com/rust-lang/crates.io/issues/5062 you can try to update your browser to see if is related...

**Comment by fabricereix** [comment]
ok, it now works with a fresh Chrome installation.
We had to add a small fix in the `Cargo.toml` file after the `1.7.0` tag.
We will therefore push to crates.io with the new tag `1.7.1` (in the next few days)

**Comment by fabricereix** [comment]
done
https://crates.io/crates/hurl

**Comment by huangjj27** [comment]
> We will therefore push to crates.io with the new tag 1.7.1 (in the next few days)
Will there be a  `1.7.1` ？

**Comment by jcamiel** [comment]
Hi,
You can get the 1.7.0 version on crates.io (see the change logs [here](https://github.com/Orange-OpenSource/hurl/releases/tag/1.7.0) and a quick tour at https://hurl.dev/blog/2022/09/15/announcing-hurl-1.7.0.html). The plan is to have a new version 1.8.0 with some features before the end of this year.
