### ISSUE TITLE
Allow to assert on headers as array

### ISSUE THREAD

**Issue by thePanz** [Orange-OpenSource/hurl#881]
Some headers are allowed to be defined multiple times (see: Vary)
RFC: https://www.rfc-editor.org/rfc/rfc7230#section-3.2.2

Would it be possible to adjust the `header` assertion accordingly?

**Comment by jcamiel** [comment]
Hi, 
If your HTTP response contains multiple `Vary` header, the header query returns a collection. For instance, given the following request / response:

```
> GET /hello HTTP/1.1
> Host: localhost:8000
> Accept: */*
> User-Agent: hurl/1.8.0-SNAPSHOT
>
* Response: (received 12 bytes in 11 ms)
*
< HTTP/1.0 200 OK
< Vary: Content-Type
< Vary: User-Agent
< Content-Type: text/html; charset=utf-8
< Content-Length: 12
< Server: Flask Server
< Date: Fri, 07 Oct 2022 20:53:35 GMT
```


You can use the `header` query like this:


```hurl
GET http://localhost:8000/hello

HTTP/* 200
[Asserts]
header "Vary" count == 2
header "Vary" includes "User-Agent"
header "Vary" includes "Content-Type"
```

The doc is really not clear about it (see https://hurl.dev/docs/asserting-response.html#header-assert) so I take the action to update it and clarify what's happening when there are multiple values for the same header.

I hope this helps you!

**Comment by thePanz** [comment]
Thanks @jcamiel , the docs are now much clear! :+1:
