### ISSUE TITLE
VSCode Plugin

### ISSUE THREAD

**Issue by SeriousM** [Orange-OpenSource/hurl#891]
Is there some work on a vscode plugin? The [File and Grammer](https://hurl.dev/docs/grammar.html) is well documented and [vscode's syntax highlighting](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) isn't too complicated.
What's your thought, should we/I create such a plugin for syntax highlighting or even autocomplete?

**Comment by jcamiel** [comment]
Hi, 

We plan to work on a Language Server extension (https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) to benefit from the Rust Hurl grammar existing code and add support for VSCode. Of course, you're welcome to try using vscode syntax highlighting, don't hesitate to ask for help if our grammar isn't clear or need correction,

**Comment by fabricereix** [comment]
The RLS is now deprecated, in favor of the Rust Analyser (https://blog.rust-lang.org/2022/07/01/RLS-deprecation.html)
Both the Rust Analyser and the vscode path can be interesting to try. I'm looking forward to see such plugins.

**Comment by SeriousM** [comment]
I'm a very experienced developer in c# but haven't wrote a syntax highlighter myself or worked with rust so far. From the documentation of vscode I see that the syntax highlighter is just for the colorful highlighting, the language server for problem identification, autocomplete support and jump-to-definiton (variables, captures, ...).
Both are essential and I guess that the syntax highlighting and autocomplete should be quite easy as the grammer is well documented. The first implementation would be at a higher level to support the main tokens (asserts, captures, ..) without deep syntax checks eg. json path.

I see that https://github.com/Orange-OpenSource/hurl/tree/master/packages/hurl_core/src contains all required tokens where I could generate typescript vscode-grammer definitions for the extension, but maybe there is an easier way? What's your thoughts?

**Comment by fabricereix** [comment]
maybe you could rely directly on the [grammar](https://github.com/Orange-OpenSource/hurl/blob/master/docs/spec/hurl.grammar)

**Comment by jcamiel** [comment]
Link #315

**Comment by deadcoder0904** [comment]
any progress on this? the syntax highlighting looks awesome on the homepage.

**Comment by SeriousM** [comment]
Closing this ticket in favor to #315
