### ISSUE TITLE
Test Report Types

### ISSUE THREAD

**Issue by nikeee** [Orange-OpenSource/hurl#921]
Request:
Adding support for the [Test-Anything-Protocol](https://testanything.org) as output format.

[Node.js 18's built-in  testing module](https://nodejs.org/api/test.html) has support for it, so it would be reasonable to think that the protocol will gain more traction.

GitHub actions added a feature called Job (or step) summaries earlier this year:
https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

There are also actions in the market place that take TAP formatted files as input and render a markdown job summary from it:
https://github.com/marketplace/actions/summary-test-results

This could really enhacne the DX of the CI/CD integration hinted in [the docs](https://hurl.dev/docs/tutorial/ci-cd-integration.html#running-tests-with-github-action).

**Comment by jcamiel** [comment]
Thanks for the issue, the TAP output will be really useful.

Related https://github.com/Orange-OpenSource/hurl/issues/601 and https://github.com/Orange-OpenSource/hurl/issues/371

**Comment by nikeee** [comment]
I've closed this issue, as it's a duplicate

**Comment by jcamiel** [comment]
Hi @nikeee I've reopened if 😄 ! This way, we'll not forget it and we can prioritise enhancements that have a lot of related issues.

**Comment by jcamiel** [comment]
Fixed by #1749
