### ISSUE TITLE
hurl 1.8.0 release build issue

### ISSUE THREAD

**Issue by chenrui333** [Orange-OpenSource/hurl#957]
👋 trying to build the latest release, but run into some regression test failure with `hurlfmt`. The error log is as below:

<details>
<summary>test error</summary>

```
thread 'main' panicked at 'Mismatch between definition and access of `color`. Could not downcast to TypeId { t: 11046744883169582909 }, need to downcast to TypeId { t: 5311595127245143337 }
', /Users/rui/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/clap-4.0.18/src/parser/error.rs:30:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abort trap: 6
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/3394674898/jobs/5643636143
relates to Homebrew/homebrew-core#114698

**Comment by jcamiel** [comment]
Hi @chenrui333 I will look into this asap. Just for your information, we've not yet release the 1.8.0 version, the release is still marked as draft (although we have create a git tag to create a GitHub release). I don't know the process of Homebrew to bump a version, how do you think I can signal Homebrew that a new release is not in draft anymore?

**Comment by jcamiel** [comment]
I've asked a question about Brew process here https://github.com/orgs/Homebrew/discussions/3879 to see how we can improve our release management.

**Comment by jcamiel** [comment]
Hi @chenrui333 we've finalized our 1.8.0 version which is now the latest release (and the issue that you've should be fixed).
Thanks for the feedback.
