### ISSUE TITLE
[RFE] "./hurl  --binary allinone.exe helloworld.hurl" support

### ISSUE THREAD

**Issue by tjyang** [Orange-OpenSource/hurl#974]
Hi 
This is a request for enhancement down the road for your consideration,
It will be cool if one can generate a static binary exe file that include the .hurl content.
So once test phase is passed. one can generate and run allinone.exe to test without disclose sensitive login info in .hurl file. 
Please just close this ticket if this RFE is not possible.

**Comment by fabricereix** [comment]
I'm not sure how hard it is to generate such an executable, especially on Windows.
I don't think we can have that included in the Hurl core functionalities., but maybe something in the contrib folder or a different project.
You can try it yourself and let us know if you have something.

**Comment by tjyang** [comment]
@fabricereix , Thanks for the reply and encouraging comment. Once I found this possible I will report back.  Closing this thread for now.

**Comment by tjyang** [comment]
I remember why (R1) I even ask for this feature.  R2 is a googling to see if Rust can do the same.
R1: https://stackoverflow.com/questions/17796043/how-to-embed-files-into-go-binaries
R2: https://stackoverflow.com/questions/27140634/how-to-embed-resources-in-rust-executable
