### ISSUE TITLE
Allow omitting version asterisk (e.g. allow `HTTP 200` rather than just `HTTP/* 200`)

### ISSUE THREAD

**Issue by jmoore34** [Orange-OpenSource/hurl#975]
When the HTTP version is not important, it would be nice if you could write e.g. `HTTP 200` instead of only `HTTP/* 200` (i.e. supporting both syntaxes). In general, I think simple, intuitive syntax is one of Hurl's strengths, and I think supporting this would help further this goal, especially because it's similar to what you might see in a browser developer console.

**Comment by fabricereix** [comment]
I like it!
We could indeed remove the version check by simply removing fully the version part.

**Comment by fabricereix** [comment]
@jcamiel 
for the grammar/AST, I would see the HTTP version as optional
```
response:
  lt*
  "HTTP" version? sp status lt
  header*
  response-section*
  body?

version:
    "/1.0"
  | "/1.1"
  | "/2"
```
